### ISSUE TITLE
Unknown system error -122 when creating new app using quick start templates

### ISSUE THREAD

**Issue by drajar** [Budibase/budibase#4092] opened 2022-01-18 18:46 UTC
I try to create new app using quick start templates. The error is:
```
Error: Unknown system error -122: Unknown system error -122, chown '/tmp/.budibase/app/car-rental-admin-panel/'
    at $ (index.a7d4a7f5.js:formatted:145683:23)
    at async HTMLButtonElement.j (index.a7d4a7f5.js:formatted:8672:16)
```
Does not meter what template I try to use.

The instance is a fresh self hosted on a debian server using docker containers.

On Windows I use Chrome.

What I need to change? Why chown is not working?

**Comment by mike12345567** [comment] 2022-01-19 16:46
Hi @drajar - i've been trying to reproduce this to not much success - can I confirm a few things with you:

1. What version of the Budibase images are you currently using?
2. What version of the docker engine, and docker-compose are you using?
3. Are you using the CLI to run your self hosted setup or have you just downloaded the compose files and are running it that way?

It appears to be an issue with our tarball utility, when it downloads the app templates it is unable to extract them due to the chown utility throwing a system error, however as this is in a docker container it should be consistent across environments, so it must be something to do with docker engine.

**Comment by drajar** [comment] 2022-01-19 17:43
1. grep image docker-compose.yaml
    image: budibase.docker.scarf.sh/budibase/apps
    image: budibase.docker.scarf.sh/budibase/worker
    image: minio/minio
    image: envoyproxy/envoy:v1.16-latest
    image: couchdb
    image: curlimages/curl
    image: redis
    image: containrrr/watchtower

Budibase ver: 1.0.43

2. Docker version 20.10.12
docker-compose version 1.25.4
docker-ce                 5:20.10.12~3-0~debian-bullseye amd64

3. used CLI downloaded with wget(doc https://docs.budibase.com/self-hosting/self-host/budibase-cli-setup)
Replaced ibmcom/couchdb3 to couchdb because ibm keeps restarting(#1909)

I can create a new app without template.

From log:
```
ERROR [1642529242323] (29 on 9d9ce90c50ab): Unknown system error -122: Unknown system error -122, chown '/tmp/.budibase/app/car-rental-admin-panel/'
    Error: Unknown system error -122: Unknown system error -122, chown '/tmp/.budibase/app/car-rental-admin-panel/'
Trace: [Error: Unknown system error -122: Unknown system error -122, chown '/tmp/.budibase/app/car-rental-admin-panel/'] {
  errno: -122,
  code: 'Unknown system error -122',
  syscall: 'chown',
  path: '/tmp/.budibase/app/car-rental-admin-panel/'
}
    at /app/dist/api/index.js:69:21
    at Generator.throw (<anonymous>)
    at rejected (/app/dist/api/index.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
INFO  [1642529242325] (29 on 9d9ce90c50ab): request errored
    res: {
      "statusCode": 500,
      "headers": {
        "vary": "Accept-Encoding",
        "content-type": "application/json; charset=utf-8",
        "content-length": "131"
      }
    }
    err: {
      "type": "Error",
      "message": "failed with status code 500",
      "stack":
          Error: failed with status code 500
              at ServerResponse.onResFinished (/app/node_modules/pino-http/logger.js:77:38)
              at ServerResponse.emit (events.js:412:35)
              at ServerResponse.emit (domain.js:475:12)
              at ServerResponse.emitted (/app/node_modules/emitter-listener/listener.js:134:21)
              at onFinish (_http_outgoing.js:792:10)
              at callback (internal/streams/writable.js:513:21)
              at afterWrite (internal/streams/writable.js:466:5)
              at afterWriteTick (internal/streams/writable.js:453:10)
              at processTicksAndRejections (internal/process/task_queues.js:81:21)
    }
```

**Comment by mike12345567** [comment] 2022-01-19 18:06
Hi @drajar - just to check is this currently running on an ARM based system? Your point 3

> replaced Replaced ibmcom/couchdb3 to couchdb

Won't actually work, Budibase depends quite heavily on a lot of the features that the IBM CouchDB 3.0 image provides, sadly at the moment because of this it will not support ARM based systems. At some point we hope to support ARM fully by building out own image of Couch - we discuss this here: https://github.com/Budibase/budibase/discussions/1647#discussioncomment-833708

**Comment by drajar** [comment] 2022-01-19 18:54
No, my system is: Linux 5.15.0-2-amd64 #1 SMP Debian 5.15.5-2 (2021-12-18) x86_64 GNU/Linux

**Comment by mike12345567** [comment] 2022-01-20 12:05
Hm that is odd in that case, you should be able to start with the IBM CouchDB image, that is the first issue that would need to be resolved.

The issue here may be with the version of Debian, Debian 5 is quite an old version - it looks like you have the Debian Bullseye (11) version of the Docker CE installed - there is likely some kernel features that are not available on such an old version; I would expect this is the root cause of the issue. I don't believe that the latest versions of Docker actually support Debian 5 - I believe the oldest distribution supported is Debian 10.

**Comment by drajar** [comment] 2022-01-20 12:10
cat /etc/debian_version
bookworm/sid

I have debian 11 testing :) is not old :)

**Comment by drajar** [comment] 2022-01-20 12:14
dpkg -l linux-image-5.15.0-2-amd64
ii  linux-image-5.15.0-2-amd64 5.15.5-2     amd64        Linux 5.15 for 64-bit PCs (signed)

5 is kernel version :)

I will change couchdb image and wil post the errors.

**Comment by drajar** [comment] 2022-01-20 12:29
budibase_couchdb-service_1
touch: cannot touch '/opt/couchdb/etc/local.d/docker.ini': Disk quota exceeded

budibase_couch-init_1
Could not resolve host: couchdb-service
sh: fg: line 1: No current job

./budi hosting --status
Budibase status
            Name                           Command                  State                             Ports
----------------------------------------------------------------------------------------------------------------------------------
bbapps                          docker-entrypoint.sh yarn  ...   Up             4001/tcp, 0.0.0.0:4002->4002/tcp,:::4002->4002/tcp
bbworker                        docker-entrypoint.sh yarn  ...   Up             4001/tcp, 0.0.0.0:4003->4003/tcp,:::4003->4003/tcp
budibase_couch-init_1           /entrypoint.sh sh -c sleep ...   Exit 2
budibase_couchdb-service_1      /docker-entrypoint.sh /opt ...   Restarting
budibase_minio-service_1        /usr/bin/docker-entrypoint ...   Up (healthy)   0.0.0.0:4004->9000/tcp,:::4004->9000/tcp
budibase_proxy-service_1        /docker-entrypoint.sh envo ...   Up             0.0.0.0:10000->10000/tcp,:::10000->10000/tcp
budibase_redis-service_1        docker-entrypoint.sh redis ...   Up             0.0.0.0:6380->6379/tcp,:::6380->6379/tcp
budibase_watchtower-service_1   /watchtower --debug --http ...   Up             0.0.0.0:6161->8080/tcp,:::6161->8080/tcp

**Comment by mike12345567** [comment] 2022-01-20 12:42
Sorry I mis-read your messages, didn't realise that was the kernel version!

This looks to be the core of all the issues in that case the `Disk quota exceeded` - this has error code `122` like you were seeing with the `chown` utility as well - I found some discussion around this here https://unix.stackexchange.com/questions/67890/disk-quota-exceeded-problem/67962
and here
https://cyberpersons.com/2020/01/25/solved-disk-quota-exceeded/

For now I'm going to close this issue out now as I don't believe there is anything that the Budibase software can do to resolve this issue as it is a host problem - not within the docker container itself.

**Closed by mike12345567** 2022-01-20 12:42 UTC
Labels: bug

**Comment by drajar** [comment] 2022-01-20 13:00
I think the problem is in how couchdb container is created by the budi cli/docker-composer; this is only container that have this problem not my linux.
