### ISSUE TITLE
signature pad form element

### ISSUE THREAD

**Issue by flozi00** [Budibase/budibase#5418] opened 2022-04-14 09:49 UTC
**Describe the feature request**
https://github.com/szimek/signature_pad

The signature pad as form element could enable more possibilitys, for example for the time sheet template

**Comment by shogunpurple** [comment] 2022-06-05 18:14
Dupe of https://github.com/Budibase/budibase/issues/4380

**Closed by shogunpurple** 2022-06-05 18:14 UTC
Labels: enhancement
