### ISSUE TITLE
QR Code scanning via webcam or phone cam

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#5020] opened 2022-03-22 20:44 UTC
QR code scanning - and taking pictures is a necessary component.

### Discussed in https://github.com/Budibase/budibase/discussions/5012

<div type='discussions-op-text'>

<sup>Originally posted by **spierepf** March 22, 2022</sup>
I'm looking at implementing an app in budibase that uses QR codes to identify physical assets. Is it possible for a budibase app to use a phone's camera or a desktop webcam to scan QR codes?</div>

**Comment by shogunpurple** [comment] 2022-03-22 23:03
On roadmap - closing as dupe of https://github.com/Budibase/budibase/issues/4379

**Closed by shogunpurple** 2022-03-22 23:03 UTC
Labels: enhancement, components
