### ISSUE TITLE
Form block: when i update a column name, the form input disappears

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#8353] opened 2022-10-21 13:49 UTC
I added a form block and connected it to my internal table. 

When I change the column name in my table (budibase db), the corresponding form input disappears.

https://vimeo.com/762652624/7747a3470d

**Comment by aptkingston** [comment] 2022-10-21 14:10
If you change the field name you'll need to select the new name in your form settings. 

You can see in the video that the form block now says there is only one field selected:
![image](https://user-images.githubusercontent.com/9075550/197215479-32df71c6-f3fb-4dd9-9cc1-dd32354a5107.png)

We could maybe add a new option for "show all fields" (defaults to yes, since that's an upcoming feature anyway), and if that is selected then we would automatically render all fields and this would stay updated with field name changes. If you pick no, then you get the current multi-select field. That would be a good enhancement, but I'll close this one off as this is all working as intended.

**Closed by aptkingston** 2022-10-21 14:10 UTC
Labels: bug
