### ISSUE TITLE
OR function in Define Filters

### ISSUE THREAD

**Issue by Hajelarohit** [Budibase/budibase#5992] opened 2022-05-20 03:11 UTC
**Describe the feature request**
Current Filters work on "AND" function, which require all conditions to be met. If there is a way to provide multiple conditions connected with a mix of AND/OR function, than that's be very helpful

**Screenshots**
in this case, i want to check if either of these dates have crossed today's date. If it meets one condition, i should get the resulting data.
![image](https://user-images.githubusercontent.com/104535363/169442801-69257780-67a6-453b-96ff-725664acb0ef.png)

**Comment by mike12345567** [comment] 2022-05-20 09:15
Closing as dupe of #5993.

**Closed by mike12345567** 2022-05-20 09:15 UTC
Labels: enhancement
