### ISSUE TITLE
App ID in Webhook URL doesn't changed to match current project after imported [Budibase version 2.0.37]

### ISSUE THREAD

**Issue by Onchulee** [Budibase/budibase#8391] opened 2022-10-25 11:30 UTC
**Hosting**
- Self
  - Method: Kubernetes
  - Budibase Version: 2.0.37

**Describe the bug**
App id from url in webhook automation doesn't changed to new app id after import project.

**To Reproduce**
1. Export project from Budibase version 1.3.12
2. Import the project from step 1 to Budibase version 2.0.37
3. Go to edit project > Automate
4. Select webhook automation
5. URL from schema, trigger and webhook setup are all contained old app id instead of new one

**Expected behavior**
URL from schema, trigger and webhook setup after import project should be regenerated to match app id of current project.

**Screenshots**
![screenshot_err_app_id_webhook](https://user-images.githubusercontent.com/40201185/197760849-1fab2a6f-3fe1-4822-baac-ade85390d428.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome (106.0.5249.119)

**Comment by melohagan** [comment] 2022-10-25 18:58
Closing as duplicate of: https://github.com/Budibase/budibase/issues/8330

**Closed by melohagan** 2022-10-25 18:58 UTC
Labels: bug
