### ISSUE TITLE
Can't remove an automation

### ISSUE THREAD

**Issue by Kurt-Aziri** [Budibase/budibase#1777] opened 2021-06-21 12:56 UTC
**Describe the bug**
Under Automate, I have quite some old automations I want to get rid of. Although it seems you can delete an automation, once I go to the 'Design' tab, and back to 'Automate' the removed automations are back
**To Reproduce**
1. Go to tab Automate
2. Click on '...' next to an automation: delete
3. Go to tab Design
4. Go to tab Automate : the deleted automation is back in the list

**Desktop (please complete the following information):**
 - OS: Win
 - Browser chrome

**Comment by shogunpurple** [comment] 2021-06-21 13:04
Thanks for the report @Kurt-Aziri - think this might be a dupe of https://github.com/Budibase/budibase/issues/1646. We'll get that one resolved this week.

**Closed** 2021-06-21 14:34 UTC
Labels: bug
