### ISSUE TITLE
[ Data ] - Changing a table removes all defined views

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#12950] opened 2024-02-04 10:02 UTC
Self Hosted 2.17.3

Reproduce
Create internal table
Create a couple of views
Make a change to the table
Views are removed

https://github.com/Budibase/budibase/assets/80512170/49c1540c-7c26-42b7-9db4-8f4bb071a2da

**Comment by melohagan** [comment] 2024-02-05 14:29
Thanks for raising @poirazis 

The video was very helpful too 👍  I am going to close it as a duplicate of this issue however: https://github.com/Budibase/budibase/issues/12470

**Closed by melohagan** 2024-02-05 14:29 UTC
Labels: bug
