### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#371] opened 2020-06-21 17:05 UTC
When I am using the builder, I want to be able to upload attachments and images to my model fields, favicons and more, so that I can use custom assets in my budibase applications.

#### Basic flow
- User uses file uploader to upload file from their machine
- File gets uploaded to S3, or used on disk if we haven't deployed
- public URL returned that is stored in couch/frontend definition files

**Comment by mjashanks** [comment] 2020-07-23 13:46
Duplicate of #492

**Closed by mjashanks** 2020-07-23 13:46 UTC
