### ISSUE TITLE
[BUDI-6663] Unable to select columns from define filters

### ISSUE THREAD

**Issue by kzkondo** [Budibase/budibase#9859] opened 2023-03-02 10:52 UTC
**Checklist**

* \[✔️ \] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker single image
  * Budibase Version: 2.3.15

**Describe the bug**
Unable to select columns from define filters

**To Reproduce**

[https://user-images.githubusercontent.com/93172658/222408105-afad68ec-ad59-4ebd-92f7-7baa103dadd2.mov](https://user-images.githubusercontent.com/93172658/222408105-afad68ec-ad59-4ebd-92f7-7baa103dadd2.mov)

**Desktop (please complete the following information):**

* OS: MacOS 12.6.3
* Browser chrome, safari
* Version latest

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-6663](https://linear.app/budibase/issue/BUDI-6663/unable-to-select-columns-from-define-filters)</sub>

**Comment by shogunpurple** [comment] 2023-03-07 15:02
Closing as dupe of [https://github.com/Budibase/budibase/issues/9909](https://github.com/Budibase/budibase/issues/9909)

**Closed by shogunpurple** 2023-03-07 15:02 UTC
Labels: bug, linear
