### ISSUE TITLE
[BUDI-6742] Cannot log in – type error followed by weird redirect

### ISSUE THREAD

**Issue by caseyatMission** [Budibase/budibase#10006] opened 2023-03-13 16:40 UTC
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: missioncloud.budibase.app

**Describe the bug**
Trying to log in to Budibase produces the following behavior. After clicking "Log in" from budibase.com, I'm taken to this url with the following type error:

<img width="1958" alt="Screenshot 2023-03-13 at 9 10 56 AM" src="https://user-images.githubusercontent.com/124637427/224762859-bed5a24e-b11c-4505-b39c-ce8b6b268016.png">

Subsequent attempts take me to `budibase.app/auth/login` for a split second before redirecting to `account.budibase.app`:

https://www.loom.com/share/375afc34ede4481082af6c40cbd75e27

If I try to navigate directly to `account.budibase.app/auth/login`, I get the same behavior.

**To Reproduce**
1. Go to Budibase.com
2. Click on Log in.
3. Get the type error message.
4. Return to Budibase.com, try to log in again.
5. Get redirected.

1. Try going directly to `account.budibase.app/auth/login`
2. Get redirected.

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Browser: Chrome 111, but 110 was also producing this behavior on Friday. (adblocking is disabled for budibase.com and .app.)

<sub>[BUDI-6742](https://linear.app/budibase/issue/BUDI-6742/cannot-log-in-type-error-followed-by-weird-redirect)</sub>

**Comment by Rory-Powell** [comment] 2023-03-14 22:48
Hi @caseyatMission. Thank you for raising this issue and including the video. Just to update you we've found the root cause of this one, I'll update again when we've deployed a fix.

**Comment by Rory-Powell** [comment] 2023-03-15 11:33
Fix deployed to budibase cloud - closing

**Closed by Rory-Powell** 2023-03-15 11:33 UTC
Labels: bug, linear
