### ISSUE TITLE
How can I return to the previous screen using action button (navigate)?

### ISSUE THREAD

**Issue by JEQ7** [Budibase/budibase#8393] opened 2022-10-25 14:12 UTC
I create a screen and that page is linked with different screens and this screen has a go back button how can I use this button to return to the previous screen?

**Comment by melohagan** [comment] 2022-10-25 14:37
Hey @JEQ7 

Closing as duplicate of: https://github.com/Budibase/budibase/issues/5420

**Closed by melohagan** 2022-10-25 14:37 UTC
