### ISSUE TITLE
Search feature in a Cards Block

### ISSUE THREAD

**Issue by jben7** [Budibase/budibase#4316] opened 2022-02-03 20:14 UTC
**Describe the bug**
When you create a Cards Block, you can define Search Columns, if you set an option menu, the search function doesn't work.

**To Reproduce**
1. Create a Cards Block
2. Set a Search Columns which type is option

**Expected behavior**
It must search and display all iteration of the selected option value

**Desktop (please complete the following information):**
 - OS: Windows 10 19041.1415
 - Browser Chrome 97.0.4692.99

**Comment by aptkingston** [comment] 2022-02-04 08:02
Hi @jben7. Could we get some more information? I've tried to reproduce this myself and it works as expected.

What datasource are you using? Internal table or SQL (and which type of SQL)?
Could you also screenshot or copy and paste the error? 

Thanks.

**Comment by jben7** [comment] 2022-02-05 12:25
![image](https://user-images.githubusercontent.com/42550761/152641911-866a9b5e-ac2c-4b9b-8902-27f9945479a5.png)
![image](https://user-images.githubusercontent.com/42550761/152641924-aa4c4c8c-4e47-4979-8844-e2b749d67876.png)
I only have internal tables, in the first screenshot, you can see my table
On the second, you can see the option menu
![image](https://user-images.githubusercontent.com/42550761/152641998-ce23b3aa-d550-4572-a7c2-8c9788956ba6.png)
On the third screenshot, you can see that when I apply the filter, nothing happen (it should show only GWANGYE GOMUN grade)

**Comment by aptkingston** [comment] 2022-02-05 12:33
Thanks for the extra details. You mentioned there was an error - could you copy and paste the error or screenshot it in the dev console so I could see what it is? Thanks.

**Comment by jben7** [comment] 2022-02-10 15:43
Hi, I don't have any information/error in devtools, how can I provide you more details ?

**Comment by aptkingston** [comment] 2022-02-10 15:49
Hi @jben7. Whenever you said "See error", I thought you meant that there was an actual error showing. Now I can see that you just meant that it did not work as you expected.

Would it be possible for you to export your app and email it to andrew@budibase.com? This will let me recreate the problem exactly! That will include your data in internal tables, so only do this if you don't have any sensitive data.

Because I can't seem to reproduce this, I'm not sure what else I can do without an app export to recreate the problem, but I would really like to get this fixed for you if I could.

**Comment by aptkingston** [comment] 2022-02-14 09:42
Thanks for sending me that @jben7. I can confirm this issue is fixed and will be included in our next release.

**Closed** 2022-02-14 16:38 UTC
Labels: bug, needs-triage
