### ISSUE TITLE
Automation: cannot use JS output to create a new row

### ISSUE THREAD

**Issue by gvlx** [Budibase/budibase#3343] opened 2021-11-12 10:29 UTC
**Describe the bug**
If I define a row object as the result of a JS action, that output is reject as an input of a "Create Row" action.

I need to create a new row on a table, but I want to calculate the new value of the fields.

**To Reproduce**
I set an automation with JS action --> "Create Row" and test it just to capture the in/out values.

I use the value on the Input of the "Create Row" to create the new object I return in the JS action.

Now the test always returns with an error on the last action.

**Expected behavior**
A new row with the calculated values.

**Screenshots**
![imagem](https://user-images.githubusercontent.com/67311/141452005-c4cfdaeb-7240-4adb-99ca-b03a09a7fd76.png)

The input to the "Create Row" show only the default values, not the values I created

![imagem](https://user-images.githubusercontent.com/67311/141452101-480c8162-c137-4518-b149-105d3692cff5.png)

**Desktop (please complete the following information):**
 - OS: W10
 - Browser Firefox 94.0,1
 - Version 0.9.185

**Additional context**
Maybe this is not a bug but a feature request?

**Comment by mike12345567** [comment] 2021-11-12 10:31
Hi @gvlx - this is a known issue documented in https://github.com/Budibase/budibase/issues/3296 - we have merged a fix for it but it has not yet been released (will be soon).

**Comment by mike12345567** [comment] 2021-11-12 10:31
closing issue as it is a duplicate of https://github.com/Budibase/budibase/issues/3296.

**Comment by mike12345567** [comment] 2021-11-12 10:41
Sorry @gvlx - just understanding what you're trying to do the `[object Object]` threw me off as that was the issue in the previous issue, you're trying to take the raw output of the JS function as the input for the `row` parameter in `Create Row` - could you please show me the way you've setup your create row action?

**Comment by gvlx** [comment] 2021-11-12 10:44
I have done nothing in the "Create Row" action except defining the affect table as I don't want to use the input dialog.

**Comment by mike12345567** [comment] 2021-11-12 10:48
> I have done nothing in the "Create Row" action except defining the affected table as I don't want to use the input dialog.

I see, right now there isn't really a way to take the raw output from another action and completely fill in a row for the automation - the error shouldn't appear as `[object Object]` so I'll look into that and give it a more clean error explain what is wrong. The way you would do this is the your `return test` of the JS script will need to be used in one of the inputs for the create row like:
![image](https://user-images.githubusercontent.com/4407001/141454876-6157521b-030a-4fc6-8efb-8f931bd71b93.png)
Where the `{{ steps.1.value }}` is the output of the JS Script.

I don't think it would be possible for Budibase to do this without the user specifying the various components of the row as this could be quite dangerous and would have implications for a lot of other automation actions.

**Comment by gvlx** [comment] 2021-11-12 11:15
OK, I misunderstood the usefulness of this action.

In my case, when I create a new row, I only need to specify the `required` fields.

Using binding values, I could solve most of theses cases, but for some field types, there is no option to do this (for instance, option fields).

Raised #3345 for this.

**Comment by mike12345567** [comment] 2021-11-12 11:16
No problem, i've made an update to the automation error handler to make sure it will always convert JS objects correctly into something human-readable as that would have made this more obvious.
![image](https://user-images.githubusercontent.com/4407001/141458568-3870d6b0-c176-4d4e-a368-3b35758dc955.png)

Going to close this issue as I think #3345 covers the bigger issues that need resolved here.

**Closed by mike12345567** 2021-11-12 11:16 UTC
Labels: bug
