### ISSUE TITLE
Unable to create EDIT form screen

### ISSUE THREAD

**Issue by emeany** [Budibase/budibase#14780] opened 2024-10-11 18:30 UTC
Seems to be related to:
(https://github.com/Budibase/budibase/issues/14771)

**Describe the bug**
Attempting to create a new screen using the wizard fails with error message: 'Error creating screens'
Response obj:
{
    "message": "Invalid body - \"routing.roleId\" is required",
    "json": {
        "message": "Invalid body - \"routing.roleId\" is required",
        "status": 400
    },
    "status": 400,
    "url": "https://swvl.budibase.app/api/screens",
    "method": "POST",
    "handled": true,
    "suppressErrors": false
}

**To Reproduce**
1. Click the plus icon to make a new screen from the Design tab
2. Choose type 'Form'
3. Select a table datasource
4. Choose type 'Create a new row' or type 'Update an Existing row'

**Expected behavior**
A screen is is generated

![image](https://github.com/user-attachments/assets/37f55ab5-0ff8-4c5a-a1c8-66bf5d3a50ba)
  
Chrome browser
Noticed the issue after updating my app this morning

**Comment by ConorWebb96** [comment] 2024-10-14 06:54
Looks like it will be fixed on the next release. Can you try again after the next release is out `2.32.18` is the version it will be released with.

**Comment by ConorWebb96** [comment] 2024-10-22 09:46
Hey @emeany,

I'm going to close this as I haven't heard back and wasn't able to recreate it on the latest version of Budibase again today. If this is still an issue.

Can you add more context by following the below template. Thanks for this!

**Checklist**
- [ ] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: <method> 
  - Budibase Version: <version> 
  - App Version: <version> 
- Cloud
  - Tenant ID: <tenantId> 

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.
  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Closed by ConorWebb96** 2024-10-22 09:46 UTC
Labels: bug, awaiting response

**Comment by emeany** [comment] 2024-10-29 18:13
@ConorWebb96,

Sorry for going awol. The issue was resolved after the update.

**Comment by ConorWebb96** [comment] 2024-10-30 13:07
No worries @emeany,

Going to change this from not planned to fixed. 👍
