### ISSUE TITLE
Cannot configure links conditionally - console error

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3665] opened 2021-12-03 11:15 UTC
Steps
1. Go to layout
2. Click on layout
3. Click `Configure Conditions`
4. Choose `Update Setting > Links`
5. Click `Configure Links`
RESULT: nothing happens & I get a console error:

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'forEach')
    at Object.OK.t.$$.update (index.8b07ec4f.js:1254)
    at io (vendor.470042a4.js:4)
    at new NK (index.8b07ec4f.js:1254)
    at Array.DK (index.8b07ec4f.js:1254)
    at Iu (vendor.470042a4.js:1)
    at Array.LA (index.8b07ec4f.js:20)
    at Iu (vendor.470042a4.js:1)
    at Vw (vendor.470042a4.js:6)
    at io (vendor.470042a4.js:4)
    at new HX (vendor.470042a4.js:6)
```

**Comment by aptkingston** [comment] 2021-12-03 11:28
Dupe of https://github.com/Budibase/budibase/issues/3656 but this one has better reproduction steps!

**Closed** 2022-01-11 10:12 UTC
Labels: bug
