### ISSUE TITLE
Add possibility to create own handlebars helpers (and shared js library)

### ISSUE THREAD

**Issue by leolivier** [Budibase/budibase#12730] opened 2024-01-08 14:53 UTC
Hi
Handlebars provides the possibility to create its own helpers using the registerHelper javascript function (see https://handlebarsjs.com/guide/block-helpers.html#basic-blocks for instance)
I think it would be a great enhancement.

(And as, for doing that, I think you need to define some place where to store some  javascript code that can be shared amongst filters, conditions, fields, ...), it would also be a great enhancement to be able to define shared JS functions for JS bindings...

EDIT: can be seen the reverse way actually: if you provide some place to define some shared JS functions, we'll be able to use it for defining own handlebars ;)

**Comment by melohagan** [comment] 2024-01-15 10:53
Closing as duplicate of: https://github.com/Budibase/budibase/issues/3571

**Closed by melohagan** 2024-01-15 10:53 UTC
