### ISSUE TITLE
Updating existing app causes "Database does not exist" after being published

### ISSUE THREAD

**Issue by funkymule** [Budibase/budibase#4093] opened 2022-01-18 19:04 UTC
**Describe the bug**
When I updated existing apps to the 1.0.43 version, then publish the app, it displays
`{"message":"Database does not exist.","status":404}`
upon opening.

**To Reproduce**
1. Open an app created in an older version (mine was 1.0.25).
2. Click the `App Version` button in the upper right corner (looks like a refresh button...is quite confusing to users).
3. Accept the update to 1.0.43.
4. (Re)publish the application.
5. Go back to Budibase home screen.
6. Click `View published app` on the newly updated app
7. A white screen displays `{"message":"Database does not exist.","status":404}`

**Expected behavior**
The newly published app opens

**Screenshots**
![image](https://user-images.githubusercontent.com/4054389/150002038-f571092d-ea0c-4174-9644-a48a4b2d1aa1.png)

**Comment by mike12345567** [comment] 2022-01-18 19:35
Hi @funkymule - I gave this a go myself, setup a Budibase environment running `v1.0.25`, created an app, added some screens, published it - then updated the environment to `v1.0.43` then upgraded the app and re-published it, when I viewed the app it was still functioning correctly.

Could you let me know a few things - 
1. We changed the way apps are accessed in the latest versions Budibase, it now accesses them via `/app/<app_name>` as the URL - I'm wondering if something went wrong with this making the app inaccessible - could you share the resource component of the URL?
2. How did you perform the update, did you do it through the command line, or did you use the update section of Budibase to update via Watchtower?
3. Just wondering if theres any console errors, or which network request is specifically failing, might help diagnose.

**Comment by funkymule** [comment] 2022-01-18 19:35
Actually, this error occurs for several published apps that were not upgraded or republished. :(
Every app that has a Data Source defined gives the same error.

**Comment by funkymule** [comment] 2022-01-18 19:37
> 

The URL is `/app/App%20Name`

**Comment by sergey-dme** [comment] 2022-01-18 19:40
I faced with the same problem after update to v1.0.42 yesterday. Unpublish-Publish-Unpublish-Publish (two times) helped in my case.

**Comment by mike12345567** [comment] 2022-01-18 19:42
Hi @funkymule - what type of datasource is it that seems to be linked to the issue? Or is it just any datasource existing seems to cause it?

**Comment by funkymule** [comment] 2022-01-18 20:11
We only use SQL Server data sources, so I can't tell you if it's due to a SQL Server data source, or just because it has a data source in general.

And...to make it more confusing...of all the applications with SQL Server data sources...ONE of them is working. :o

**Comment by funkymule** [comment] 2022-01-18 20:12
> I faced with the same problem after update to v1.0.42 yesterday. For update I use CLI. Unpublish-Publish-Unpublish-Publish (two times) and docker restart helped in my case.

I'll give it a shot!!!

**Comment by mike12345567** [comment] 2022-01-18 20:48
Hi @funkymule - found the issue - I think its to do with apps that have uppercase letters in the app name - these will generate invalid URLs. if you try `/app%20name` instead of `/App%20Name` I believe it should work.

For now if you unpublish the broken apps and rename the apps to all lowercase it'll fix the link they generate, although I'll have an actual fix out for it soon.

**Comment by funkymule** [comment] 2022-01-18 21:19
> Hi @funkymule - found the issue - I think its to do with apps that have uppercase letters in the app name - these will generate invalid URLs. if you try `/app%20name` instead of `/App%20Name` I believe it should work.
> 
> For now if you unpublish the broken apps and rename the apps to all lowercase it'll fix the link they generate, although I'll have an actual fix out for it soon.

@mike12345567 , I'll give it a look-see.
What I can say is that the application with the URL `app/Waste%20Input` loads properly, even though there are uppercase letters in the URL.

**Comment by funkymule** [comment] 2022-01-18 22:08
So if I change the URL to lowercase on the browser's address bar, you think it should work? I've tried changing the casing to all lowercase manually, and it doesn't change the behavior.

**Comment by mike12345567** [comment] 2022-01-18 22:25
Sorry just realised, you'll need to change the app name itself, as the issue is server-side, if you `unpublish` the app, you'll be able to edit it, in which you can change the name, if you change it to all lower case it should then work!

**Comment by funkymule** [comment] 2022-01-18 22:42
Well...not a great solution but this works:

- Unpublish the application `My App`
- Rename the application `My App` to `My App2`
- _Refresh the page_ (Budibase thinks the original name is still taken if you don't refresh the page)
- Rename the application from `My App2` to `My App`
- Publish `My App`

It works, but it's undesirable as the apps have unfinished, unpublished and untested changes that now must be published. And since there's no way to see what's changed since last publish, I can't undo pending changes. :(

But...it's better than apps not loading.

**Comment by mike12345567** [comment] 2022-01-18 23:26
Yes sorry about the issue, we'll be pushing a fix for this soon, from the PR #4095 - once it's released you won't need to do that anymore!

**Comment by mike12345567** [comment] 2022-01-19 16:17
Hi @funkymule - just to let you know `v1.0.44` has been released, this should resolve the issue for you.

**Closed** 2022-01-19 16:18 UTC
Labels: bug

**Comment by funkymule** [comment] 2022-01-19 17:27
> Hi @funkymule - just to let you know `v1.0.44` has been released, this should resolve the issue for you - going to close this for now, if it continues after update you can let me know and we can re-open to continue research.

Thanks for the quick attention to this!

**Comment by stellarfinn** [comment] 2022-02-16 23:44
I'm having the same issue exact issue today. Public page, public database. Budibase cloud though. Any ideas?

**Comment by Rory-Powell** [comment] 2022-02-17 09:53
@stellarfinn if you email the link to the app to rory@budibase.com I will investigate
