### ISSUE TITLE
Area chart resizes when hovered

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#982] opened 2021-01-11 10:56 UTC
**Describe the bug**
When you hover over the area chat, it changes in size or alters padding/margin.

**To Reproduce**
https://www.loom.com/share/c58cb8834beb4dba9f7ae158eee16bf9

**Expected behavior**
The chart should keep its shape.

**Desktop (please complete the following information):**
 - Mac, electron

**Comment by aptkingston** [comment] 2021-02-22 15:52
I can't seem to reproduce this - could this have been an accidental case of maybe defining the hover styles to have padding, while the normal styles didn't have padding (or vice versa)? All the charts share the exact same markup, so if this was an issue with one chart, it would likely be an issue with all of them. The loom link seems broken so I can't watch it, but I definitely think this is likely just the configured styles having different padding set for normal and hover.

**Comment by joebudi** [comment] 2021-02-22 15:55
It was a while back, so I am not too sure. If it is working on your end, mark it as resolved.

**Comment by aptkingston** [comment] 2021-02-22 18:48
Yep, seems to be all good so I'll close this one off.

**Closed by aptkingston** 2021-02-22 18:48 UTC
Labels: bug
