### ISSUE TITLE
[BUDI-7101] Custom MySQL update with date like value saves as Date instead of Text

### ISSUE THREAD

**Issue by samg666** [Budibase/budibase#6346] opened 2022-06-16 08:28 UTC
Hello,

Recently I tried to update a record(using custom SQL), and found that if I input something like `
202205-1500` on the text field, then Budibase implicity convert it to `2022-05-15 00:00:00.000`(I am using text field on Budibase, and MySQL field type is varchar). On the MySQL query logs, I found the raw update is `update tbl_bills SET InvoiceID=concat('', '2022-05-15 00:00:00.000', '')`. 

It seems Budibase will verify if the string is a datetime, if it's a date like string then will convert it to something like `2022-05-15 00:00:00.000`. I found this issue happens on all text fileds. 

<sub>[BUDI-7101](https://linear.app/budibase/issue/BUDI-7101/custom-mysql-update-with-date-like-value-saves-as-date-instead-of-text)</sub>

**Comment by melohagan** [comment] 2022-10-17 07:06
Closing as duplicate of: https://github.com/Budibase/budibase/issues/7887

**Comment by melohagan** [comment] 2022-11-28 15:22
Have to re-open this issue because the fix for the duplicate only covers array values from Multi-select pickers, e.g. `1,2,2017`

This scenario `202205-1500` is still a problem. The underlying issue of not knowing the data type (date or text) at the point of calling **bindingTypeCoerce** still exists.

**Comment by enpro-github** [comment] 2023-06-08 20:43
will this issue be fixed soon?  It is causing a lot of issues for us.  Thanks

**Closed** 2023-06-15 10:52 UTC
Labels: bug, env - production, firestorm, linear
