### ISSUE TITLE
[BUDI-7823] Curl on Minio-Docker-Image not aviailible anymore

### ISSUE THREAD

**Issue by darkspiret** [Budibase/budibase#12526] opened 2023-12-08 01:03 UTC
**Checklist**
- [x ] I have searched budibase discussions and github issues to check if my issue already exists
I found a similar one: https://github.com/Budibase/budibase/pull/12279

**Hosting**
- Self
  - Method: docker-compose.yml + portainer
  - Budibase Version: latest
  - App Version: latest

**Describe the bug**
curl is not aviailible on the minio image anymore, the healthcheck is not working.

Error: 
```
OCI runtime exec failed: exec failed: unable to start container process: exec: "curl": executable file not found in $PATH: unknown
```
**To Reproduce**
1. create a new budibase-stack with the docker-compose.yaml : https://raw.githubusercontent.com/Budibase/budibase/master/hosting/docker-compose.yaml || https://github.com/Budibase/budibase/blob/master/hosting/docker-compose.yaml
2. the minio container will be unhealthy

**Solution**

change the healtchek from:
```
old: test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
```
to
```
new: test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
```

<sub>[BUDI-7823](https://linear.app/budibase/issue/BUDI-7823/curl-on-minio-docker-image-not-aviailible-anymore)</sub>

**Comment by melohagan** [comment] 2023-12-08 12:56
Thanks @darkspiret but closing as duplicate of: https://github.com/Budibase/budibase/issues/12491

**Closed** 2023-12-08 15:52 UTC
Labels: bug, linear, Medium priority
