### ISSUE TITLE
Account automatically deleted.

### ISSUE THREAD

**Issue by raventechnologiesinc** [Budibase/budibase#13090] opened 2024-02-20 22:44 UTC
**Checklist**
- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
raventech.budibase.app -->

**Describe the bug**
My account got automatically blocked after a QUOTA LIMIT was reached.
I created a new account and upload original app.
Everything runs fine. But such a hassle to repoint all domain redirects

To reauthorize my users I have to delete emails from my old account.
Every time I attempt to login to my old account to delete emails.

The NEW account app crashes with

{
    "message": "Error creating account user activity: {\"message\":\"Unauthorized\",\"status\":403}",
    "status": 500
}

These two accounts are in no way link because they have unique emails.
How can code image from one app crashed anohter?

How do I get into my old account?

**Desktop (please complete the following information):**
 - WIN11
 - Chrome
 - latest

**Comment by melohagan** [comment] 2024-02-27 14:47
Closing as duplicate of: https://github.com/Budibase/budibase/issues/13087

Please don't raise multiple issues for the same problem.

**Closed by melohagan** 2024-02-27 14:47 UTC
Labels: bug
