### ISSUE TITLE
[BUDI-6924] Empty .update() call detected error displayed when updating a table record from the side panel

### ISSUE THREAD

**Issue by kyousry** [Budibase/budibase#10387] opened 2023-04-22 18:32 UTC
-------------------environment details
I am using the free plan on the cloud
version of Budibase:  2.5.7
Data Source: External MySQL Cloud Server
Tenant ID: test500
app name: my-first-app
OS: windows
Browser: Chrome 112.0.5615.121

-------------------bug description
when trying to update a table from the side panel
it displays a red popup with the below message:
Empty .update() call detected! Update data does not contain any values to update. This will result in a faulty query. Table: teams2. Columns: .

-------------------bug details
the row is updated though
I can see the correct/expected new value after refresh
so it displays the error, plus update the row.

the table I am trying to update is (employees) linked to another (teams) via one to many relationship 

steps to reproduce
display a screen with a table block
click one row of the table
sid epanel shows
update values
press save
    error shows
table gets updated

Expected behaviour
error should not be displayed

<sub>[BUDI-6924](https://linear.app/budibase/issue/BUDI-6924/empty-update-call-detected-error-displayed-when-updating-a-table)</sub>

**Comment by kyousry** [comment] 2023-04-25 14:00
here is the DB schema, I tried with both postgres and MySQL , both show the same error
below is Postgres schema

CREATE TABLE IF NOT EXISTS teams (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL 
); 

CREATE TABLE IF NOT EXISTS employees (
    id SERIAL PRIMARY KEY,
    last_name VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,

    reporting_to INT NOT NULL,
    team_id INT,

    CONSTRAINT fk_employee 
        FOREIGN KEY(team_id)  
        REFERENCES teams(id) 
);


INSERT INTO teams (name) VALUES ('CRM');
INSERT INTO teams (name) VALUES ('Support');
INSERT INTO teams (name) VALUES ('Testing');

INSERT INTO employees ( first_name, last_name, title,  reporting_to, team_id)  
    VALUES (  'Khaled' , 'Ahmed' , 'Team Manager',  2, 1);

INSERT INTO employees ( first_name, last_name, title,  reporting_to, team_id)  
    VALUES ( 'Aya' , 'Fahmy' , 'Senior Developer',  1, 2);

**Comment by adrinr** [comment] 2023-05-23 10:36
Hello @kyousry. I could not reproduce the issue, neither using MySQL nor Postgres. Could you please provide an app export to be able to reproduce it from our end?

**Comment by pierreboudes** [comment] 2023-05-23 16:53
Hi, I have the same bug which popped while I was investigating another one. I can share an export and/or fill my own detailed issue as you prefer. The bug arise when creating a new "organisation" linked to two "persons" via a one to many relationship, on a self hosted docker-compose based installation (freshly updated) while using postgresql, and a list view template.

**Comment by adrinr** [comment] 2023-06-23 15:18
Closed as duplicated of https://github.com/Budibase/budibase/issues/10688

**Closed** 2023-08-08 10:02 UTC
Labels: bug, firestorm, linear
