### ISSUE TITLE
Error when submitting new row: Id can't be blank

### ISSUE THREAD

**Issue by kekonn** [Budibase/budibase#10158] opened 2023-03-30 07:03 UTC
**Checklist**
```[tasklist]
- [x] I have searched budibase discussions and github issues to check if my issue already exists
```

**Hosting**

- Self
  - Method: docker 
  - Budibase Version: 2.4.32 
  - App Version: N/A 

**Describe the bug**
After connecting to an empty database and adding some tables, I wanted to add a row. I click `Add row` and fill in the text fields. When I click submit, nothing happens. When checking the network tab in the browser dev tools, I see a 500 error is returned. 
When viewing the auto columns I do notice two ID columns, even though there is only one Id column in the database. This happens on all the tables I generated. I have already tried to fetch all tables again, but the double id columns remain.

1. Please don't hide errors. They should be displayed to the user.
2. Why do I need to fill in an ID? it is an auto column, the value should be autogenerated. The form doesn't even provide an ID field to fill in.
3. 500 seems like strange error code for this. I would expect a 400 (Bad Request)

request payload to insert row:
```json
{
    "Apartment": [],
    "Floors": [],
    "Columns": [],
    "Address": "De Roest d'Alkemadelaan 2-4, 2600 Berchem",
    "Name": "Regent 6",
    "tableId": "datasource_plus_ea810a5136f44524b345283a7f4729f9__Buildings"
}
```

Server response:
```json
{"status":500,"validationErrors":{"id":["can't be blank"]}}
```

**To Reproduce**
1. Create a new app
4. Connect an empty mysql database
5. Add a table
6. Try to add a row to that table

**Expected behavior**
Row is inserted because all required column fields in the form are filled in.

**Screenshots**
![Table structure](https://user-images.githubusercontent.com/149670/228755182-7fb90de9-f23c-4a48-a1a7-1b32548b3495.png)
  
**App Export**
Not comfortable doing this, since that might expose the DB CA cert to environments beyond my control.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser Firefox
 - Version unknown (not at that machine atm)

**Additional context**
Please let me know if you want to get access to my budibase server. I will need some data in order to allow you in.

**Comment by shogunpurple** [comment] 2023-03-30 10:07
Dupe of https://github.com/Budibase/budibase/issues/10142

**Closed by shogunpurple** 2023-03-30 10:07 UTC
Labels: bug
