### ISSUE TITLE
[BUDI-7421] REST Query - query parameters updated with binding.binding.binding... repeated

### ISSUE THREAD

**Issue by hawkinsjon** [Budibase/budibase#11582] opened 2023-08-23 14:32 UTC
**Checklist**

* \[x \] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: DO
  * Budibase Version: 2.9.25

**Describe the bug**
binding. prefix keeps adding to my bindings. I believe this is happening upon save but not entirely sure.

**To Reproduce**
I'm not entierly sure how this is happening. I was setting up a data source to read from the public reddit search API. Through normal activity working with bindings and editing the query, I noticed the binding. prefix would begin to stack.

**Expected behavior**
For the binding to be recognized and alert me that it's recognized after I type. The same type ahead function that was recently released would be nice to have here as well or some confirmation. When binding. appears in my binding, that serves as good confirmation too. Obviously just not over and over again :)

**Screenshots**

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/1158452b-68a8-4043-a3ca-c311510a204a/d30f1625-466e-49e3-8e0b-fa323aea7903?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC8xMTU4NDUyYi02OGE4LTQwNDMtYTNjYS1jMzExNTEwYTIwNGEvZDMwZjE2MjUtNDY2ZS00OWUzLThlMGItZmEzMjNhZWE3OTAzIiwiaWF0IjoxNjkyODAyNDg3LCJleHAiOjE2OTI4ODg4ODd9.aAb0cLBWTveqwMTSHhZ5ADxFjau7dQKM7nFPYKBqB8M)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7421](https://linear.app/budibase/issue/BUDI-7421/rest-query-query-parameters-updated-with-bindingbindingbinding)</sub>

**Comment by melohagan** [comment] 2023-08-23 16:34
Thanks for raising @hawkinsjon but I am going to close this as a duplicate of: https://github.com/Budibase/budibase/issues/9583

**Comment by hawkinsjon** [comment] 2023-08-23 16:35
Oops sorry about that @melohagan, missed it.

**Closed by melohagan** 2023-08-23 16:34 UTC
Labels: bug, linear

**Comment by melohagan** [comment] 2023-08-23 16:36
> Oops sorry about that @melohagan, missed it.

No worries at all, I've updated the title of the other issue to make it a little easier to find.
