### ISSUE TITLE
Bugs in Designer [Size: Width/Heigh]

### ISSUE THREAD

**Issue by Den4ik1992** [Budibase/budibase#9455] opened 2023-01-26 22:43 UTC
Hallo Budibase Team ,
I am using Budibase 2.2.22 with Docker Compose on a ubuntu oracle vps and use a Google Chrome Browser on my Windows 11.

I can't make the button completely full-width across the entire page, only in height:
![Button](https://user-images.githubusercontent.com/82113641/214966120-1f890542-63bc-4fab-8a18-e467cebac7eb.gif)

I don't see any effect after changing the width of the form:
![Forms](https://user-images.githubusercontent.com/82113641/214966130-33e3deea-5847-4d75-a405-4e1324d3d304.gif)

I can't change the image size, it only changes in the designer but not in the preview/publish:
![Picture](https://user-images.githubusercontent.com/82113641/214966211-3705a014-ed26-4309-a623-6629adb5b22d.gif)

Am I doing something fundamentally wrong or is it a bug ?

Thank you for any answer ;)

**Comment by melohagan** [comment] 2023-01-31 11:28
Closing as duplicate of https://github.com/Budibase/budibase/issues/8750

**Closed by melohagan** 2023-01-31 11:28 UTC
Labels: bug, sev5 - low, env - production
