### ISSUE TITLE
Query result change - Javascript binding for execute query is `undefined`

### ISSUE THREAD

**Issue by raventechsaigon** [Budibase/budibase#14866] opened 2024-10-24 15:59 UTC
**Checklist**
- [ X ] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Cloud
  - Tenant ID: <tenantId> <!-- shown in URL as ship2vietnam.budibase.app

**Describe the bug**
Object object error on all apps

We haven't made any changes to our code for months.
All the sudden Object Object errors popping up every where.
Our MySql server is up and connecting.
We can still get tables in builder.

Live apps all crashing.

**Comment by raventechsaigon** [comment] 2024-10-24 16:05
It seems all JAVASCRIPT  erroring out
Query are coming back with different JSON format

![image](https://github.com/user-attachments/assets/0db599a3-c303-4811-b9ee-55c09e930993)

**Comment by mike12345567** [comment] 2024-10-24 17:14
Hi @raventechsaigon - I've attempted to re-create this in a few different formats, I assume this is a MySQL query that you are attempting to execute?

What has the response been updated to - can you check the format to see if an error is now occurring? The MySQL and REST queries I have tried all return the response I would expect (top level `data` property).

Also - do you know when this issue started to occur?

**Comment by ConorWebb96** [comment] 2024-11-19 13:36
Closing, can't reproduce and no followup.

**Closed by ConorWebb96** 2024-11-19 13:36 UTC
Labels: bug, awaiting response
