### ISSUE TITLE
Javascript executed multiple times

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3964] opened 2022-01-07 12:08 UTC
### Discussed in https://github.com/Budibase/budibase/discussions/3955

<div type='discussions-op-text'>

<sup>Originally posted by **ryzam** January  7, 2022</sup>
Hi guys,

In my javascript function I just add simple log console when update state for debugging purpose but I realize when execute the function budibase will call multiple times even then action only call one Update State

![image](https://user-images.githubusercontent.com/597759/148494627-da3786c4-c5d3-49a7-ad75-94660131013a.png)

![image](https://user-images.githubusercontent.com/597759/148494739-792e26f3-395f-4f2d-830b-d54472613f9a.png)

![image](https://user-images.githubusercontent.com/597759/148494893-8fa6dc39-bff5-4f68-a6da-0e2b42bf9206.png)

</div>

I would add to this - the state also gets update multiple times **before** the button is clicked. In the image below, the red box is before click. The blue box is after click...

![image](https://user-images.githubusercontent.com/3524181/148542120-8f678697-31c0-4bf8-9930-edeba9505a0a.png)

**Comment by aptkingston** [comment] 2022-01-07 14:52
I think I answered something about this before... there will be definitely be a closed issue somewhere about this.

But basically this is just how it's supposed to work. Bindings (including JS bindings) get evaluated frequently. In this example, although the "set state" action only gets evaluated on click, the value that is going to be set is computed beforehand, and is computed again any time context changes.

This isn't a problem unless we started providing functionality to JS bindings that could cause mutations to the DOM or to app state, but currently this is completely fine other than the fact it seems confusing as to why it runs so often.

If there is ever an issue caused by this behaviour then we could consider that a bug, but for now this is all working as intended.

**Comment by aptkingston** [comment] 2022-01-07 15:07
Just on the above point - my recent JSON PR includes the new functionality of button action outputs. When that is merged this behaviour won't actually happen because button actions won't be enriched until they are about to be executed.

I have another PR up for REST query pagination which includes some performance enhancements that might reduce the frequency of these unnecessary enrichments as well.

**Closed** 2022-01-12 15:44 UTC
Labels: bug
