### ISSUE TITLE
Issue when saving a form in a modal or side panel with a timeout / RESULT_CODE_HUNG error

### ISSUE THREAD

**Issue by L42xyz** [Budibase/budibase#13095] opened 2024-02-21 10:18 UTC
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: groupe3b

**Describe the bug**
When saving a form block in a side panel or in a modal, the page often freezes and I get a RESULT_CODE_HUNG on Google Chrome. I have to wait for Chrome to ask me to kill the page (page not responding, do you want to quit) to be able to reload and continue my work. The form is correctly saved but it slows down a lot the work I can do. This is not happening all the time but it is very frequent and it happens on multiple screens and forms on my application.

**Desktop :**
 - OS: Mac OS 14.2.1
 - Browser : Chrome 121.0 (last update but the problem started before)
 - Budibase Version : 2.20.10 
 - Database : Internal Budibase DB

**Comment by melohagan** [comment] 2024-02-27 14:44
Closing as duplicate of: https://github.com/Budibase/budibase/issues/13105

**Closed by melohagan** 2024-02-27 14:44 UTC
Labels: bug
