### ISSUE TITLE
display column is last not first in preview/published when table source is data provider

### ISSUE THREAD

**Issue by otichy** [Budibase/budibase#15011] opened 2024-11-14 20:28 UTC
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: ffuk

**Describe the bug**
When data source for the table is data provider, the display column (that should be shown first) is shown first only when editing, but in preview or published app, it is actually last.

See the column full_name in the two screenshots.

This does not happen when the data source is directly a Postgres table. 

**To Reproduce**
1. Generate table from data (e.g. a Postgres table, where you have a display column set) with the modal to edit the table
2. Add a data provider for the same data source
3. Switch the table to the data source
4. Move around/hide some of the display columns (sometimes, when I don't change anything, it works ok)
5. Click preview

**Expected behavior**
The display column should be first, but is last in the preview (but first in design)

**Screenshots**
![image](https://github.com/user-attachments/assets/2b39015e-7af8-406b-b210-9875908fe989)
![image](https://github.com/user-attachments/assets/4ccd6071-abb0-46a0-8d62-8e1b302750bc)

  
**App Export**
(https://github.com/user-attachments/files/17757328/ibiblio-export-1731615516518.tar.gz)

**Comment by otichy** [comment] 2024-11-14 20:28
The odd behaviour can be reset by switching the data source from data provider to the postgres table and back, but after any change to how the columns are displayed, the bug is back.

**Comment by ConorWebb96** [comment] 2024-11-15 08:36
Marking this as a duplicate of this issue. https://github.com/Budibase/budibase/issues/13827 It's not the exact same issue, but it comes under the weird behavior of having a data provider as the source of a table. Rather than referencing a table as the source directly.

**Closed by ConorWebb96** 2024-11-15 08:36 UTC
Labels: bug
