### ISSUE TITLE
Map is slow to load with very little data

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#5230] opened 2022-04-04 10:06 UTC
**Describe the bug**
It's taking a few seconds to load the map with very little data:
https://www.loom.com/share/6f7bc41c0fce498ea67ed50324e86d60
Changes to the size props are not reflected in the preview.

**Comment by aptkingston** [comment] 2022-04-04 10:21
Thats the data provider itself that's loading though - so it looks like maybe prod is just being slow. I imagine it would be the same speed of loading no matter what the component inside was.

And something is wrong with your builder because the component isn't selected in the preview when you change the height. I can confirm that changing the height setting definitely does get updated live in the preview.

**Comment by shogunpurple** [comment] 2022-04-04 14:42
Seems like this one was a infra issue that has since been resolved. Closing for now

**Closed by shogunpurple** 2022-04-04 14:42 UTC
Labels: bug
