### ISSUE TITLE
Update Form step on screen load from url var/param

### ISSUE THREAD

**Issue by MaxBernstetter** [Budibase/budibase#10178] opened 2023-03-31 12:41 UTC
Hey,

I would like to update the form step within a screen at the screen loading dynamically by a param or variable within the url. Is this possible? Currently, the form is not selectable within the "on screen load" -> "Set form step" action.

![image](https://user-images.githubusercontent.com/77627676/229122677-abd2b479-d0e0-4ec2-8eed-cba7a37c37b6.png)

**Comment by melohagan** [comment] 2023-08-07 19:32
Closing as duplicate of: https://github.com/Budibase/budibase/issues/9323

When form step bindings are available, then you will be able to use the URL variables and / or *On screen load* **Change Form Step** action.

**Closed by melohagan** 2023-08-07 19:32 UTC
Labels: enhancement, long-term
