### ISSUE TITLE
Payload Too Large - Upload large video files.

### ISSUE THREAD

**Issue by Elliot-Construct** [Budibase/budibase#14259] opened 2024-07-26 16:23 UTC
**Checklist**
- [x] I have searched budibase discussions and GitHub issues to check if my issue already exists.

**Hosting**
- Self
  - Method: docker-compose multi image
  - Budibase Version: 1.0.105

**Describe the bug**
When using the file uploader to upload videos that are multiple gigabytes, I receive the message "Payload Too Large."

**To Reproduce**
1. Go to the file uploader component.
2. Attempt to upload a video file that is several gigabytes in size.
3. Observe the error message "Payload Too Large."

**Expected behavior**
The file uploader should be able to handle large video files without throwing a "Payload Too Large" error.

**Comment by ConorWebb96** [comment] 2024-07-30 10:51
Closing this issue as its not a bug.<br><br>The cap is 20mb per file. We may add an environment variable for this for self-host users at some point. For cloud this is unlikely to change.  <br><br>Feel free to use [s3](https://docs.budibase.com/docs/s3) if you wish to upload larger files. I believe the limit per file here is 5gbs. You can find out more information on the s3 uploader component [here](https://docs.budibase.com/docs/s3-file-upload).

**Closed** 2024-07-30 10:51 UTC
Labels: bug
