### ISSUE TITLE
Single Docker Image Deployment

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#5202] opened 2022-04-01 10:18 UTC
**COS**
- Allow budibase to be run in a single docker image

**Notes**
- Assess impact a single docker image has on our deploy targets
- What does this mean for compose
- Needs tested on ARM

**Comment by mike12345567** [comment] 2022-04-05 09:59
Still required for full feature completion:
1. Adding single image build into CI pipeline, as following:
    * adding `build:docker:single` to
        * `docker:build`
        * `docker:build:develop` (Be good to have develop versions of this image for QA)
    * updating `release-to-dockerhub.sh` to include the Budibase image
    * updating `release-selfhost.yml` to push the latest tag
2. Merging all `nginx.conf` files, right now there is a separate image for the K8S/Docker compose setup which is built with HBS, would be good to merge the single docker file NGINX conf into this build process as well.
3. Exposing more environmental options - right now you can override any of the supplied variables on startup, it would be good to provide these in an .env file as we do with compose and document how to use this in a command.
4. Image size reduction and optimisation, for both the single image and for the `apps` and `worker` images used in the compose/K8S installs.
5. Volume management, some planning around how this will work in the single docker file deployment.

**Comment by aderici** [comment] 2022-05-07 15:20
I spent quite some time to get this dockerfile for single image working. all went well but i'm stuck at one specific point. would really appreciate any help you could provide : 

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/6830693/167260634-b8ec14fd-db7c-404e-a6eb-b85e028cd3b5.png">

@mike12345567

**Comment by shogunpurple** [comment] 2022-05-23 07:57
Some futher context on this - we have decided on the extent of the single image and where it will be used. 

- The current docker-compose option is still the preferred option due to the ability to run everything separately, with a cleaner separation of volumes
- We will add a section to the docs for users to run a single docker image, along with all of the options that it provides
- We will replace the digitalocean one click deployment with the single image
- The single image will be the standard method for all future self hosted PaaS like templates - azure, heroku, linode, etc

Timeline for completion on the single image is around the next 2-3 weeks, as we set up the CI pipelines and work on the tasks defined by @mike12345567 above.

**Comment by aderici** [comment] 2022-05-23 14:11
Thanks @shogunpurple really happy to see a timeline for this. For Azure Appservice there are 2 requirements

1) all important data should be written into somewhere under /home folder within the docker image. Azure Appservice will only persist that folder. This is really important so that we can easily make azure persist our data for couchdb and minio. (I assume there's no need to persist redis data between restarts?)

2) its a nice convenience to be able to ssh into the docker container. In order to do that we need to install ssh and have a static (or configurable through environment variables) account set up. See the section "enable ssh" https://docs.microsoft.com/en-us/azure/app-service/configure-custom-container?pivots=container-linux

Again thanks and happy to see a timeline for single image option,

**Comment by jonnymccullagh** [comment] 2022-06-27 08:03
Hi @aderici I have just merged some changes in the budibase repo to try to help you build a container image for Azure App Service. There is an associated [README.md](https://github.com/Budibase/budibase/tree/develop/hosting/single) file with instructions on how to build the single image. 
Please let us know how you get on and if we need to make any further changes to support your usage.

**Comment by aderici** [comment] 2022-07-05 01:51
@jonnymccullagh thank you so much for looking into this. I'll try this and will let you know if i run into any issues. 

I followed a quite different approach and would like to share that with you as well. I have created an sh file which does docker pull for app and worker containers and copy pastes the already compiled app folders from them and then builds a single container using those folders. I went into this path because i could not compile the app on my own successfully.

I will try and use your files going forward,

Thanks again,

**Comment by aderici** [comment] 2022-07-12 22:46
Hi, just seen the june release announcement that also mentions single docker on docker hub. Unfortunately it does not run as advertised on M1 mac as the oracle db module has no corresponding binaries built for arm platform. I have faced this issue when building my own single image as well, had to specifically force platform amd64. You may want to re-visit your claim of this running on arm : 
<img width="676" alt="image" src="https://user-images.githubusercontent.com/6830693/178611047-7889a5ad-36d5-49f5-a15b-9b7c79c507e8.png">

**Comment by mike12345567** [comment] 2022-07-13 13:47
Hi @aderici - we've just pushed 1.1.3 which should resolve the issues with ARM + Oracle client lib.

https://hub.docker.com/layers/budibase/budibase/budibase/latest/images/sha256-7c7cb6cca6eb320088f74c3b8aaffac12458c4004bbb35cfdf8d0371292643b1?context=explore

**Comment by aderici** [comment] 2022-07-13 17:43
Thank you! I can confirm after re-pulling the image it runs as expected on M1 Mac!

**Closed** 2022-07-25 08:57 UTC
Labels: infrastructure, needs-triage

**Comment by AlejandroFNadal** [comment] 2023-05-01 07:32
Hi @mike12345567 , a minor thing (tagging you because you closed this one)
I have installed budibase in a raspi and I am using the single image. The budibase CLI tells me I have to go to localhost:10000 after installing, but in fact, I have to go to the port 8000. I only realized this after going inside the docker-compose.yaml.

Also, when asking for help in the terminal, it is a bit confusing I think:
`
```
X@X:~/budi $ sudo budi hosting
Error - Unknown hosting option.
Usage: budi hosting [options]

Controls self hosting on the Budibase platform.

Options:
  --init [type]                   Configure a self hosted platform in current directory, type can be unspecified, 'quick' or 'single'.
  --start                         Start the configured platform in current directory.
  --status                        Check the status of currently running services.
  --stop                          Stop the configured platform in the current directory.
  --update                        Update the Budibase images to the latest version.
  --watch-plugin-dir [directory]  Add plugin directory watching to a Budibase install.
  --gen-user                      Create an admin user automatically as part of first start.
  --single                        Specify this with init to use the single image.
  `
```
  
  So, should a person run sudo budi hosting --init single or sudo budi hosting --init --single ? Because both of them run, but one gave me a broken install and the other worked (right now I don't remember which)
  
  I can create a bug report for these if you want, but it felt more proper to add this here.
  
  This bug report should also be put in the budibase docs I think, because the docs just say that you have to put arm as the platform in couchdb, but that doesn't work, and the single image seems to be the simpler solution.
