### ISSUE TITLE
Can not import VIEWs from Postgres

### ISSUE THREAD

**Issue by MrChadMWood** [Budibase/budibase#12179] opened 2023-10-25 23:07 UTC
**Checklist**
- [ ] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker
  - Budibase Version: 2.11.41

**Describe the bug**
Attempting to import a VIEW from postgres. It says a PK is required. 

**Expected behavior**
I want to give users the ability to monitor views via the Table components, just as they would monitor a table.
This is so that I can create pretty human-readible versions of tables in the database, and serve that to my users.

**Screenshots**
![image](https://github.com/Budibase/budibase/assets/90083658/00b050c9-1209-445e-bb30-5e4b70acfef0)

 
**Desktop (please complete the following information):**
 - OS: Linux

**Comment by mike12345567** [comment] 2023-10-26 09:24
Hi @MrChadMWood - closing as duplicate of: https://github.com/Budibase/budibase/issues/6216

**Closed by mike12345567** 2023-10-26 09:24 UTC
Labels: bug
