### ISSUE TITLE
"Your published app date" never updates

### ISSUE THREAD

**Issue by dewdeded** [Budibase/budibase#7613] opened 2022-09-04 09:26 UTC
"Your published app date" never updates in the design view.
"Your published app date" in the management view under app status shows a different date versus the on in the design view. But the date shown there is also incorret and not up-to-date, for example we publish daily and it shows: "Last published 19 days ago".

Version: 1.3.4 (App and Budibase)    --- but bug existed before
Self-hosted via Docker

**Comment by melohagan** [comment] 2022-10-26 09:24
Hey @dewdeded 

I'm going to close this issue. 
If the bug still persists please fill out the bug template, including reproduction steps and screenshots.

**Closed by melohagan** 2022-10-26 09:24 UTC
Labels: bug

**Comment by melohagan** [comment] 2022-10-27 11:12
May also be a duplicate of this: https://github.com/Budibase/budibase/issues/5557

**Comment by AlejandroFNadal** [comment] 2022-11-23 11:48
Could this issue be reopened? Or should I create a new one following the template? I can confirm it is happening.
![image](https://user-images.githubusercontent.com/32724827/203539342-6ba077d3-8a2e-4e1c-88b5-748a9eb22524.png)
I publish very often (a few times per day) but this always says 20 days ago.

**Comment by melohagan** [comment] 2022-11-23 11:51
> Could this issue be reopened? Or should I create a new one following the template? I can confirm it is happening. ![image](https://user-images.githubusercontent.com/32724827/203539342-6ba077d3-8a2e-4e1c-88b5-748a9eb22524.png) I publish very often (a few times per day) but this always says 20 days ago.

Thanks for the screenshot Alejandro. If you could create a new bug following the template that would be much appreciated!
