### ISSUE TITLE
Data can't be selected in all chart if Data Provider is in DATA/JSON option.

### ISSUE THREAD

**Issue by faithli0929** [Budibase/budibase#12974] opened 2024-02-06 18:09 UTC
This is my java code. I use a third Data Provider to calculate the paidOrders data and collectionData coming by restAPI.
After I get the result, the data is not selectable in all of the chart.

This is my result:
[{"id":4161779,"name":"1","totalQuantity":1008},{"id":4161780,"name":"2","totalQuantity":1008}]

This is my code in the third Data Provider choose by DATA/JSON option:
const paidOrders = $("123New Data Provider.Rows");
const collectionData = $("1234New Data Provider.Rows");

// Create an object to store the total quantity by collection ID and name
const collectionTotals = {};

// Iterate through the paid orders
paidOrders.forEach(order => {
    const { productId, Quantity } = order;

    // Find the corresponding collection data for the product
    const productCollections = collectionData.filter(collection => collection.productId === productId);

    // Iterate through each collection for the product
    productCollections.forEach(collection => {
        const { collectionId, collectionName } = collection;

        // Check if the collection name is not "首頁推薦" or "新品推薦" or "人氣推薦"
        if (collectionName !== "首頁推薦" && collectionName !== "新品推薦" && collectionName !== "人氣推薦") {
            // Calculate the total quantity for the collection ID and name
            if (!collectionTotals[collectionId]) {
                collectionTotals[collectionId] = { id: collectionId, name: collectionName, totalQuantity: 0 };
            }

            collectionTotals[collectionId].totalQuantity += Quantity;
        }
    });

});

// Convert the collectionTotals object to an array for easy iteration
const output = Object.values(collectionTotals);

// Print the output array
return JSON.stringify(output);

<img width="326" alt="cap 2024-02-07 上午2 07 06" src="https://github.com/Budibase/budibase/assets/128820090/6bb52435-c4ae-46aa-8c2e-3b2cd515b98c">

<img width="313" alt="cap 2024-02-07 上午2 08 06" src="https://github.com/Budibase/budibase/assets/128820090/9a1713dc-4d91-4764-8476-a5b07a15e087">

**Comment by melohagan** [comment] 2024-02-07 08:37
Closing as duplicate of: https://github.com/Budibase/budibase/issues/12423

**Closed by melohagan** 2024-02-07 08:37 UTC
Labels: bug
