### ISSUE TITLE
Bad Request when running large REST query

### ISSUE THREAD

**Issue by Gomeyy** [Budibase/budibase#4057] opened 2022-01-16 16:49 UTC
**Describe the bug**
Sometimes getting 'bad request' when a REST query responds with over 20000 items, at 40000 items I am unable to successfully run the query ever.

**To Reproduce**
1. Create a rest query with a response of over 20000 items

**Expected behavior**
Longer response time

**Screenshots**
![image](https://user-images.githubusercontent.com/22477051/149669148-62c144d0-8acf-467d-9e31-4a922bc12d97.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 97.0.4692.71

**Additional context**

**Comment by shogunpurple** [comment] 2022-01-17 09:07
Hi @Gomeyy - is this running self-hosted or in the cloud? If running in the cloud, we have a specified limit for queries so that they can't take too long, and put unneccessary load on the server. If running self-hosted, we now have a QUERY_THREAD_TIMEOUT environment variable that can be set, which will allow you to control the timeout for your queries.

Changing this to an enhancement as it's by design.

**Comment by Gomeyy** [comment] 2022-01-17 14:31
Great! I am running self-hosted, I took a look in docker-compose.yaml and envoy.yaml, I was unable to find QUERY_THREAD_TIMEOUT could you direct me to where to set this?
Thanks

**Comment by mike12345567** [comment] 2022-01-18 14:20
Hi @Gomeyy - you may need to update your Budibase installation to the latest version to make use of this feature, but you should be able to add something like `QUERY_THREAD_TIMEOUT: 20000` (20 seconds) to your `.env` file or the `hosting.properties` file, depending on how you run your docker-composed environment. These files should be in the same directory as your `docker-compose.yaml` file.

Closing this issue as it should be resolved, feel free to re-open if this doesn't solve the issue.

**Closed by mike12345567** 2022-01-18 14:20 UTC
Labels: enhancement

**Comment by Gomeyy** [comment] 2022-01-18 15:11
Hi @mike12345567 - That indeed solved the issue when running the query on the data page, but when using that query with a data provider in a published app it still gives bad requests.
Thanks for all the help, much appreciated.

**Comment by mike12345567** [comment] 2022-01-18 15:23
Hi @Gomeyy - what is the error you're getting in the published app?

**Comment by Gomeyy** [comment] 2022-01-18 15:58
Hi @mike12345567 - 
![image](https://user-images.githubusercontent.com/22477051/149972645-c56b8cd3-a99d-415f-8857-e272a5a4cad7.png)

**Comment by mike12345567** [comment] 2022-01-18 16:01
@Gomeyy - would it be possible to see what the error is in the network tab? You should be able to find the request throwing the 400 and Preview its response.

**Comment by Gomeyy** [comment] 2022-01-18 16:17
@mike12345567 
![image](https://user-images.githubusercontent.com/22477051/149975611-7e3715fe-a7e7-480d-ad2a-0238e5c5dd1b.png)
Its currently fetching api data between two dates, if I lower the range it runs with no error, but once I go the full month it gives me the same bad request as before
