### ISSUE TITLE
[BUDI-6992] Table disappears from side bar when changing display name until refresh

### ISSUE THREAD

**Issue by doingandlearning** [Budibase/budibase#10565] opened 2023-05-12 14:03 UTC
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: Docker
  - Budibase Version: 2.6.9

**Describe the bug**
Given I'm using a postgres database, when I change the display column of the table, then the table is removed from the list on the side panel until refresh.

**Expected behavior**
I'd expect the table to stay on the list with no change

**Screenshots**
https://share.cleanshot.com/TjmBwbQF
  

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome

<sub>[BUDI-6992](https://linear.app/budibase/issue/BUDI-6992/table-disappears-from-side-bar-when-changing-display-name-until)</sub>

**Comment by melohagan** [comment] 2023-05-30 14:20
Could not reproduce - closing for now!

**Comment by doingandlearning** [comment] 2023-06-01 10:59
Hey - this is still an issue for me and I can reproduce it with different apps, datasources and computers running BB with Docker locally.

- There are no log messages when it happens
- There is a 200 request to /api/tables and the column does move to the front
- The table is still gone from the listing until a refresh

**Comment by melohagan** [comment] 2023-06-09 14:43
The recent code merge didn't fully resolve this one unfortunately.

The table still disappears on the very first change of the display column. After refreshing the page then it cannot be reproduced. 
Have to explore this one further.

**Comment by Nezteb** [comment] 2023-06-14 14:44
I can reproduce this but only when modifying the original automated column orders. If I import a table into Budibase and it automatically uses `inserted_at` as the display column, changing it to `id` will cause the table to disappear from the sidebar:

https://github.com/Budibase/budibase/assets/3588798/4237e8ab-9fdb-4b32-b052-2e3143d0d657

**Closed** 2023-06-21 14:37 UTC
Labels: bug, env - production, linear, Medium priority, bb-data-ui
