### ISSUE TITLE
Support Attachments in External Data Sources

### ISSUE THREAD

**Issue by daawaan4U** [Budibase/budibase#5486] opened 2022-04-19 13:51 UTC
**Describe the feature request**
Since attachments are stored as their metadata in the form of JSON objects in the underlying CouchDB for BudibaseDB, external data sources should be able to store it as well. Some of the external data sources that have been integrated into Budibase already natively support storing JSON and the remaining datasources can fall back to storing the JSON objects as texts/varchar/string instead

**Comment by hotemetoot** [comment] 2022-06-23 14:05
This would be a great feature yes

**Comment by jmlaurenti** [comment] 2022-08-04 09:57
Hi, 
I totally agree with @hotemetoot and @daawaan : there are so many scenarios in real life where using an external SQL DB is mandatory, that having the ability to store attachments (invoice PDF for instance) is more than useful, especially as the S3 component does not currently work with embedded minIO...

Anything we can do to have this enhancement to be considered ? :-)

**Comment by lburtwistle** [comment] 2022-08-05 21:20
Agree with @jmlaurenti @hotemetoot @daawaan.  I have a client that wants to keep their data in SQL but also loves the idea of having the application itself hosted in the cloud.  Attachment control for SQL is a must for me., so I can keep all their data within one approved data source.

**Comment by sergey-vin** [comment] 2022-08-30 16:40
+1, Really need this feature.
"S3 file upload" doesn't seem to work as a replacement of Attachments, and there's no other way to manage image galleries easily other by using attachments.
But attachments are not available for external DBs.

**Comment by melohagan** [comment] 2022-10-13 13:05
Closing as duplicate of: https://github.com/Budibase/budibase/issues/4302

**Closed by melohagan** 2022-10-13 13:05 UTC
Labels: enhancement
