### ISSUE TITLE
Adding / editing a record - Can enter null into a required field

### ISSUE THREAD

**Issue by Conor-Mack** [Budibase/budibase#461] opened 2020-07-16 10:53 UTC
When adding / editing a record, I can save null into a required field by adding some text to the required field, then removing it and clicking save before blurring from the field.

**Comment by shogunpurple** [comment] 2020-07-16 10:58
Think this is a dupe of https://github.com/Budibase/budibase/issues/454

**Comment by Conor-Mack** [comment] 2020-07-16 11:34
The required checkbox does seem to work though. It does stop me from adding a record and skipping a required field

**Closed** 2020-07-20 13:13 UTC
