### ISSUE TITLE
Not able to add filter for Data Provider conditions 

### ISSUE THREAD

**Issue by simonsilvalauinger** [Budibase/budibase#6015] opened 2022-05-21 20:58 UTC
**Hosting**
- Cloud

**Describe the bug**
Adding a filter for a Data Provider does not work. The button "Add filter" does nothing.
I added a Data Provider and added a filter condition, but defining the filter itself is not possible. Clicking on the button "Define filters" works, but adding a filter doesn't work. The button "Add filter" does nothing.

**To Reproduce**
1. Add a Data Provider
2. Click on "Configure Conditions"
3. Add an "Update setting" condition
4. Add a IF setting
5. Click on "Define filters"
6. Click on "Add filter"

**Expected behavior**
The filter selection to open

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser Firefox
 - Version 100.0.2

Thank you for your help!

**Comment by aptkingston** [comment] 2022-05-22 14:08
Hi @simonsilvalauinger. So you're adding a condition to dynamically update the data provider filters? So you set up a condition that looks something like this:
<img width="1327" alt="image" src="https://user-images.githubusercontent.com/9075550/169699100-b91c6d55-d1e1-4057-ae60-883057757d8b.png">

And then you get a drawer like this when you press "define filters":
<img width="1327" alt="image" src="https://user-images.githubusercontent.com/9075550/169699132-eade709a-f328-4a9c-b575-b57a8c787d52.png">

But at this stage, pressing add filter does nothing? It should show a new empty filter like this:
<img width="1327" alt="image" src="https://user-images.githubusercontent.com/9075550/169699247-18a517df-7eba-4ed7-baae-a7bd5ceaef8d.png">

I've followed your flow and it works for me. Could you send a screenshot of what you see whenever you click "add filter"?

Could you also check the browser console if any errors are being thrown?

**Comment by aptkingston** [comment] 2022-06-10 07:59
Closing this off as no further information was provided and I can't reproduce this.

**Closed by aptkingston** 2022-06-10 07:59 UTC
Labels: bug
