### ISSUE TITLE
REST Query result caching

### ISSUE THREAD

**Issue by fshubthunfischbaum** [Budibase/budibase#10325] opened 2023-04-17 16:24 UTC
Hey everyone, I'm very new to Budibase so I might overlook something here. 
I'm not good at coding, that's why I choose Budibase as my platform.

My Webapp needs a lot of REST input to function. Every time, someone loads the webpage REST Queries are fired.
If I continue using my APIs like that, my wallet is going to have a breakdown. It would be a nice feature to cache the query results for some time, before it is firing the next get request. Maybe there is even a way to do this today? Am I overlooking something here? :)

Best regards

**Comment by melohagan** [comment] 2023-04-18 12:43
Closing as duplicate of: https://github.com/Budibase/budibase/issues/5917

**Closed by melohagan** 2023-04-18 12:43 UTC
Labels: enhancement
