### ISSUE TITLE
[BUDI-7085] Multiple dev collab: User has to refresh when the last user leaves the app to get design/automation access

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#10785] opened 2023-06-05 11:38 UTC
**Checklist**

* [ ] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Cloud - qa env
  * Tenant ID: martin

**Describe the bug**
When a user is collaborating with another in the data section, and the user that currently has design/automation privilege leaves, the other user has to refresh to get access to design/automation.

**To Reproduce**

1. Log in with 2 accounts and access the same app
2. Leave the app with the first account
3. The other user is the only user in the "room" but needs to refresh to get the design/automation access

**Expected behavior**
Should update automatically through the websocket when the first user leaves the room.

**Screenshots**
[https://jam.dev/c/39010384-1309-4dc8-a523-e5f0bbc712ab](https://jam.dev/c/39010384-1309-4dc8-a523-e5f0bbc712ab)

**App Export**
N/A

**Desktop (please complete the following information):**

* OS: OSX Ventura 13.0.1
* Browser Chrome
* Version 113.0.5672.126 (Official Build) (arm64)

**Additional context**

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7085](https://linear.app/budibase/issue/BUDI-7085/multiple-dev-collab-user-has-to-refresh-when-the-last-user-leaves-the)</sub>

**Comment by aptkingston** [comment] 2023-06-05 12:59
Closing as dupe of #10786.

**Closed by aptkingston** 2023-06-05 12:59 UTC
Labels: bug, sev1 - critical, avalanche
