### ISSUE TITLE
Attached images not showing in deployed app

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#847] opened 2020-11-09 20:46 UTC
**Describe the bug**
Attached images, source from a table in the backend are not showing in the deployed app when added to a card.

**To Reproduce**
1. add attachment column to table
2. add image to row
3. remove grid component and replace with repeater and card
4. Bind image column to card
5. Deploy app
6. Check list page

**Expected behavior**
Image should display

**Screenshots**
![Screenshot 2020-11-09 at 20 42 32](https://user-images.githubusercontent.com/49767913/98594421-8b428f80-22cc-11eb-91bb-8931d5f1933d.png)
![Screenshot 2020-11-09 at 20 42 59](https://user-images.githubusercontent.com/49767913/98594426-8d0c5300-22cc-11eb-9aff-04f2aa45b3af.png)

**Desktop (please complete the following information):**
 - Mac

**Comment by shogunpurple** [comment] 2020-11-09 20:46
Dupe of https://github.com/Budibase/budibase/issues/820

**Comment by shogunpurple** [comment] 2020-11-11 15:44
Closing due to dupe above

**Closed by shogunpurple** 2020-11-11 15:44 UTC
Labels: bug
