### ISSUE TITLE
Export to CSV

### ISSUE THREAD

**Issue by PaulMcF1987** [Budibase/budibase#6173] opened 2022-06-02 11:30 UTC
Whenever I try to Export Data, I get the error `There was an error exporting the data`

See video [Here](https://share.vidyard.com/watch/TbQL1uofGre6SMvXTp5Fia?)

Another issue I have with this (Although I am not 110% sure as I cannot get the export to work) is that you will only be able to export the number of records that are showing on the table.
If for example the table is set to display 20 records and someone needs to export 100 records then this would mean doing 5 separate exports and then copying them all onto one document.

In another low code environment that I use, when I chose to export data, it gives me options (similar to the filter function on Budibase) so that I can chose to export depending on column data, this can be set within dates ranges either from dates in a certain table column or the date created/edited etc...

Would this be something that is in the pipeline?

---------------------------------------------------------------------------------------------------------------------------------

Thought the above issue was sorted but apparently not.
I managed to make a couple of exports and then got the same error again.

**Comment by shogunpurple** [comment] 2022-06-02 18:55
Closing as dupe of https://github.com/Budibase/budibase/issues/6175

**Closed by shogunpurple** 2022-06-02 18:55 UTC
Labels: bug
