### ISSUE TITLE
Views do not play nice with Tables

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#1552] opened 2021-05-25 12:18 UTC
**Describe the bug**
When you connect a table to a data provider that is fetching data from a view, the user is presented with two issues:

1. The table displays the rows from the view, but also a lot of empty rows, and for some reason, one of the rows with content is left to the end. I am not sure if this is a rendering issue or not.

2. You cannot select what columns to show within the table. When you click to add a column, nothing happens.

![Screenshot 2021-05-25 at 13 15 38](https://user-images.githubusercontent.com/49767913/119496729-b4ec7100-bd5b-11eb-8da3-d02b4433b205.png)

**Comment by aptkingston** [comment] 2021-05-25 14:28
Can't seem to reproduce this, and I've tried with filters, calculations and group by applied. Did you maybe set up the data provider against the view, and then go and apply a calculation to the view after that? There is view metadata that needs to be passed down, so can you try changing the data provider source to something else, and then changing it back to your view?

**Comment by aptkingston** [comment] 2021-05-26 08:21
@joebudi are you happy to close this for now then since you said you got it working after a refresh?

**Comment by joebudi** [comment] 2021-05-26 08:52
yes @aptkingston

**Closed** 2021-05-26 08:57 UTC
Labels: bug
