### ISSUE TITLE
[BUDI-6705] Custom query cannot run functions from PostgreSQL extensions

### ISSUE THREAD

**Issue by leonzaher** [Budibase/budibase#9932] opened 2023-03-07 21:10 UTC
**Hosting**

- Self
  - Method: digital ocean 
  - Budibase Version: 2.4.3 

**Describe the bug**
Custom query cannot run functions from PostgreSQL extensions. As an example, when using pgcrypto functions in PostgreSQL (following [this](https://x-team.com/blog/storing-secure-passwords-with-postgresql/) guide), Budibase throws error `Query Error: error: function gen_salt(unknown) does not exist`.

**To Reproduce**
1. Install pgcrypto extension to PostgreSQL
2. Create new custom query in Budibase, which executes
`INSERT INTO users (email, password) VALUES (
  'johndoe@mail.com',
  crypt('johnspassword', gen_salt('bf'))
);`
4. Run the query
5. Query fails with popup showing the above mentioned error

**Expected behavior**
Query succeeds with desired result being returned as the result of query.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

<sub>[BUDI-6705](https://linear.app/budibase/issue/BUDI-6705/custom-query-cannot-run-functions-from-postgresql-extensions)</sub>

**Comment by shogunpurple** [comment] 2023-03-07 21:11
@leonzaher do you definitely have it turned on for the database that you are connecting to? Can you run the same query from PGAdmin or the CLI?

`CREATE EXTENSION IF NOT EXISTS pgcrypto;`

**Comment by leonzaher** [comment] 2023-03-07 21:25
@shogunpurple yep, tried from Datagrip as well as directly using psql

**Comment by shogunpurple** [comment] 2023-03-08 11:11
Thanks @leonzaher - I'll try and reproduce on a fresh instance

**Comment by shogunpurple** [comment] 2023-03-14 14:57
@leonzaher I was not able to reproduce this on a self hosted instance with pgcrypto - it works as expected. Closing for now

**Closed by shogunpurple** 2023-03-14 14:57 UTC
Labels: bug, linear

**Comment by shogunpurple** [comment] 2023-03-14 15:13
I was not able to reproduce this on a self hosted instance with pgcrypto - it works as expected. Are you still having this issue?

**Comment by shogunpurple** [comment] 2023-03-14 15:13
@leonzaher I was not able to reproduce this on a self hosted instance with pgcrypto - it works as expected. Closing for now

**Comment by dominikjannis** [comment] 2023-03-17 15:41
I encounter the exact same error. 
error: function update_attributes_courses(unknown, unknown) does not exist.
it gets called like this:
`````
select update_attributes_courses({{attribute_id}},{{new_courses}})
`````
this is the function in question:
````
CREATE OR REPLACE FUNCTION update_attributes_courses(
  _attribute_id integer,
  _new_course_ids integer[]
) RETURNS void AS $$
DECLARE
  _existing_course_ids integer[];
  _course_id integer;
BEGIN
  -- Remove all existing relations for the given attribute_id
  DELETE FROM hia.attributes_courses
  WHERE attribute_id = _attribute_id;

  -- Add new relations for the given course ids
  IF array_length(_new_course_ids, 1) > 0 THEN
    FOREACH _course_id IN ARRAY _new_course_ids
    LOOP
      INSERT INTO hia.attributes_courses(attribute_id, course_id)
      VALUES (_attribute_id, _course_id);
    END LOOP;
  END IF;

  SELECT array_agg(course_id) INTO _existing_course_ids
  FROM hia.attributes_courses
  WHERE attribute_id = _attribute_id;

  RAISE NOTICE 'Updated course ids: %', _existing_course_ids;

END;
$$ LANGUAGE plpgsql;

````
this is intended to update m2m relations as a workaround, because the budibase postgres adapter does not remove relations correctly in the auto generated screens for me, it just adds new ones, unselected ones do not get removed.
And since budibase seems to make prepared statements out of all queries, i am currently not aware of another way of archiving this functionality than with a stored procedure/function.
