### ISSUE TITLE
Conditional UI  - apply colours conditionally

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3824] opened 2021-12-17 16:29 UTC
### Discussed in https://github.com/Budibase/budibase/discussions/3312

<div type='discussions-op-text'>

<sup>Originally posted by **ryzam** November 10, 2021</sup>
Hi budibase , I would suggest update setting in configuration conditions to have more control settings like set hide/show by default without checking value condition.</div>

**Comment by aptkingston** [comment] 2021-12-17 18:19
Closing as dupe of #3822 since once we add styles, all styles will be possible to edit via conditional UI.

**Closed by aptkingston** 2021-12-17 18:19 UTC
Labels: enhancement, binding
