### ISSUE TITLE
S3 Upload component missing data sources in list

### ISSUE THREAD

**Issue by JJenns93** [Budibase/budibase#11910] opened 2023-09-27 14:40 UTC
**Checklist**
- [YES] I have searched Budibase discussions and GitHub issues to check if my issue already exists

**Hosting**

  - Budibase Version: <version>  2.10.12.
  - 
**Describe the bug**
Hi, having trouble with the S3 upload component. I have connected up the S3 source and it is pulling through the images in the AWS bucket fine so I know that Budibase is definitely connected via the S3 source, however when I follow the steps to hook up the S3 upload component there is never any data sources available in the list to connect to.
 
If anyone can assist on this would be much appreciated!  
Thanks in advance.

**To Reproduce**
these are the step I have been following (for context): https://docs.budibase.com/docs/s3-file-upload

**Expected behavior**
For my "Data sources" to be available to hook up to the S3 upload component in the "data sources" dropdown  

**Screenshots**
![image](https://github.com/Budibase/budibase/assets/146208510/50cb362e-7795-4c33-981a-a4ad90385539)
![image](https://github.com/Budibase/budibase/assets/146208510/d7d87d34-ef54-4481-bf3e-d59637b1eea9)

 

**Desktop (please complete the following information):**
 - Browser [Chrome]

**Comment by melohagan** [comment] 2023-09-27 20:37
Hey @JJenns93 

As discussed on Discord, you simply needed to omit the endpoint URL.

Closing as duplicate of: https://github.com/Budibase/budibase/issues/11687

**Closed by melohagan** 2023-09-27 20:37 UTC
Labels: bug
