### ISSUE TITLE
No values in the header row Fill the first row with header values before trying to interact with rows

### ISSUE THREAD

**Issue by safetyjpei** [Budibase/budibase#11961] opened 2023-10-03 14:14 UTC
When I try to fetch my sheets from my google sheet I get an error saying "No values in the header row Fill the first row with header values before trying to interact with rows", however there are infact values in the header row and they have not changed. 

Looking for tips.
--CB

**Comment by mike12345567** [comment] 2023-10-03 17:23
Hi @safetyjpei - is it possible this is a duplicate of: https://github.com/Budibase/budibase/issues/11613 - do you have other tabs in your sheet which do not contain a header row?

**Comment by safetyjpei** [comment] 2023-10-03 17:38
Not from the sheet that I am selecting.

**Comment by mike12345567** [comment] 2023-10-04 09:54
would it be possible for you to provide a screenshot of the tabs within your sheet? Or perhaps an export of the sheet/sheets involved for testing? If you can re-create the issue with a dummy sheet and provide us access in some form it might be easier for us to re-create.

**Closed** 2023-11-21 14:34 UTC
Labels: bug, awaiting response
