### ISSUE TITLE
Table columns of internal data tables are sorted in opposite direction as defined in designer

### ISSUE THREAD

**Issue by arminus** [Budibase/budibase#11385] opened 2023-07-27 16:19 UTC
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker compose
  - Budibase Version: 2.8.14
  - App Version:  N/A

**Describe the bug**
Table columns of internal data tables are sorted in opposite direction as defined in designer

**To Reproduce**
1. Create a BudibaseDB table "Test", columns FirstName, LastName
2. Create a TableBlock in the designer, add the Test table as Data source
3. Configure columns, Add all columns -> order of the columns is FirstName, LastName, DOB
4. Add on more column "DOB" in the BudiBase table
5. Go back to the designer, TableBlock, Rest Columns, Add all columns
6. From now on, the order of the columns will always be in the opposite direction, see screenshot below
7. Only way to workaround that is to manually revert the sort order in the opposite direction

**Expected behavior**
Table column order should follow the order as sorted in the designer's column configuration

**Screenshots**
![2023-07-27_180508](https://github.com/Budibase/budibase/assets/683680/1a2a5924-eaa7-4515-80fe-cbbd16c6022e)
  
**App Export**
[ColumnTest-export-1690474633178.tar.gz](https://github.com/Budibase/budibase/files/12185664/ColumnTest-export-1690474633178.tar.gz)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 115.0.2

**Additional context**
N/A

**Comment by melohagan** [comment] 2023-07-31 10:50
Thanks for raising @arminus however I am going to close as a dupe of: https://github.com/Budibase/budibase/issues/10689

**Closed by melohagan** 2023-07-31 10:50 UTC
Labels: bug
