### ISSUE TITLE
PostGres Relationships broken

### ISSUE THREAD

**Issue by gravyplaya** [Budibase/budibase#15134] opened 2024-12-05 22:43 UTC
**Checklist**
- [ X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
Self hosted Docker w/ postgres

**Describe the bug**
I'm not sure what happened but I'm connected to postgres and all of a sudden the data in the relationship columns are gone.. I still see the relationships listed in the relationships tab. But all the data I had in the columns is gone. How does this happen and how can I get this data back?

**To Reproduce**
1. Go to any one of the necessary tables and see the values for the relationships are gone. (see screenshots)

**Expected behavior**
Data stays intact

**Screenshots**
![SCR-20241205-pmny](https://github.com/user-attachments/assets/ef01f9e9-d6c2-4757-8896-5c5d2b7d7766)
![SCR-20241205-pmjg](https://github.com/user-attachments/assets/ce8ea539-3a64-48b4-a475-df0180778599)
![SCR-20241205-plyx](https://github.com/user-attachments/assets/2e85192e-f3b2-4add-9b11-9dd7c20f0b74)
  

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser:  Chrome
 - Version: latest

**Comment by mike12345567** [comment] 2024-12-05 22:58
Hi @gravyplaya - could you should the configuration of some of the relationships? From the first screenshot it appears as if the foreign key column is empty, which would mean that the data does not contain a relationship.

**Comment by gravyplaya** [comment] 2024-12-06 06:37
Version 3.2.1. Last updated Nov 11th. 

<img width="583" alt="SCR-20241206-ciki" src="https://github.com/user-attachments/assets/68a9c6b2-5cc0-4dc2-bfd1-fb812831ddbc">
<img width="579" alt="SCR-20241206-cihu" src="https://github.com/user-attachments/assets/4da023cb-87bb-49cf-9aff-b9c443a988bd">
<img width="572" alt="SCR-20241206-cifj" src="https://github.com/user-attachments/assets/717b1d52-aca7-41f9-bebd-16db0681b1b0">

**Comment by mike12345567** [comment] 2024-12-06 10:36
Hi @gravyplaya - in the screenshot you provided, the `fk_Accounts_Equipment` appears to be empty in the database, which would mean there is infact no relationships. Can you confirm that the foreign key column does actually contain values in the database? If it is infact empty this would be expected behaviour.

**Comment by gravyplaya** [comment] 2024-12-06 17:48
Thats my problem is that the foreign key column HAD data in it. Then I checked yesterday and it was all gone.

**Comment by gravyplaya** [comment] 2024-12-06 20:11
I synced the postgresdb to another client to read the tables and the relationships data are still there.

**Comment by mike12345567** [comment] 2024-12-09 12:08
Hi @gravyplaya - has the schema of your Postgres table changed in anyway since you first imported it to Budibase? Budibase will not automatically sync any schema changes that have occurred, you'll need to refetch the tables when this happens. You may also need to rebuild the relationship columns if the foreign key column has changed in someway - again Budibase won't automatically detect if the column was renamed etc. Details on this can be found here: https://docs.budibase.com/docs/sql-datasource#fetching-tables

**Comment by mike12345567** [comment] 2024-12-11 10:12
Hi @gravyplaya - have the relationships been restored at this point? I'm unsure if there is anything that can be done from our side - given that the foreign key column was empty this is outside of Budibase's control.

**Comment by mike12345567** [comment] 2024-12-12 12:19
Closing as issue appears to be resolved.

**Closed by mike12345567** 2024-12-12 12:19 UTC
Labels: bug, awaiting response
