### ISSUE TITLE
Improve Table formatting

### ISSUE THREAD

**Issue by gvlx** [Budibase/budibase#3273] opened 2021-11-07 10:26 UTC
**Describe the feature request**
Tables are one of the most used elements in data entry, but also one of the most complicated to design.

The setting pane of the table element requires a lot of improvements, some of which I mention here, hoping other will add more details later on.

**Improvements:**

- [x] Column selection (which columns/fields are included)
- [x] Column sorting (order the fields are presented)
- [x] Column size
- [ ] Column formatting (other than size)
- [ ] Cell content rendering choices (img size, ratio)
- [ ] Cell links (cell has a link)
- [x] Row selector (row select check box)
- [x] Row links (row has/is a link)
- [ ] Row sorting (column based and expression based)
- [ ] Table formatting: borders, color patterns, banding, etc.
- [ ] Header formatting
- [ ] Automatic columns and rows for aggregation formulas (sum, count, etc)

**Sugestions**
Creating a new 'complex table' element which behaves like a Repeater but with automatic header row and row sorting and selector mechanisms. Each added element creates its header entry automatically.

**Comment by gvlx** [comment] 2021-11-07 11:26
I've just noticed (still a newbie here): the table element is a container.

Some (most) of the above can be solved if each added element can have a property to create its header.
This would mean the table would be used without any visible columns.

Right now (0.9.177) it is left without a header:
![imagem](https://user-images.githubusercontent.com/67311/140642956-42b809a0-2074-414b-9030-c548190c8a8a.png)

**Comment by gvlx** [comment] 2021-11-08 00:38
Linking to issue  #1694 .

**Comment by mjashanks** [comment] 2021-11-12 12:04
Thanks @gvlx - linking to this discussion also: https://github.com/Budibase/budibase/discussions/1913

Note that you can currently change the Column selection and ordering...

1. Unselect all columns
2. Select columns in the order you want them to appear

**Comment by gvlx** [comment] 2021-11-12 12:13
Thank you, 
I was already using that feature ;)

**Comment by marco-santulli** [comment] 2021-11-22 22:44
I agree that being able to "enhance" the current table with a couple of features would be of great help.  I would suggest:
1. one can already add buttons and paragraphs to a table as extra column, but one must be able to specify a "name" for that column like in gvlx comment above;
2. it might be necessary to give a "readable" name to a column.  The column names currently come from a DB in many cases, so it might not be very user friendly (without also considering the future need for i8n.
3. make the table cells writeable like in an excel, best with auto-save / undo or the option to "save" with a button
4. would be good to have the usual table perks from the end-user side: (sort, filter, download csv/xls)

**Comment by AndrewSav** [comment] 2022-01-22 06:32
Do we need to keep posting +1s to keep this open?

**Comment by Rory-Powell** [comment] 2022-01-22 09:36
@AndrewSav we no longer automatically close stale issues

**Comment by melohagan** [comment] 2022-04-04 10:24
Table banding also requested in this discussion: https://github.com/Budibase/budibase/discussions/5197

It could effectively be the same as 'Quiet' but applied to even rows only. Call it banded or striped.

**Comment by marco-santulli** [comment] 2022-04-20 09:27
Hi,

can we add a flag to tables to turn-off sorting? at the moment sorting doesn't really work for custom queries where we implement pagination manually.  In that case sorting just sorts the current page.  It should be possible to turn it off?

M

**Comment by melohagan** [comment] 2022-04-26 10:32
Allow linked rows to be opened in new tab, as you can with clickable links within the rows (https://github.com/Budibase/budibase/discussions/5577)

**Comment by melohagan** [comment] 2022-06-16 08:17
Allow individual table cells to be formatted: https://github.com/Budibase/budibase/discussions/6341

**Comment by melohagan** [comment] 2022-06-30 10:56
> Allow linked rows to be opened in new tab, as you can with clickable links within the rows (#5577)

Also want to be able to open Card links in a new tab.

**Comment by melohagan** [comment] 2022-07-15 09:11
![Screenshot 2022-07-15 at 10 11 17](https://user-images.githubusercontent.com/101575380/179192820-6a7a6212-8613-4636-9607-46b62fad9fb1.png)

It'd be nice to have an option to type in a page number to goto.

**Comment by AndrewSav** [comment] 2022-09-21 10:00
Do we need to keep posting +1s to keep this open?

**Comment by melohagan** [comment] 2022-09-21 10:05
Hey @AndrewSav No need to worry, this issue wont be closed until it's completed! The stale bot doesn't auto close.

**Comment by leolivier** [comment] 2023-12-30 12:33
The issue is closed but at least one thing is missing in my opinion:
Column formatting (other than size):   imagine I want to create a column containing an email or a phone number, I'd like to manage the formatting constraint at the column level and not each time I create a field in a form.
Also, it might be a good move to create such predefined basic types as emails, phone number, ...

**Comment by mike12345567** [comment] 2024-07-02 12:07
Closing this issue as new issues specific to the grid would be better - there is quite a lot of discussion here pertaining to our old table format, if there are specific issues pertaining to our grid and data layouts new issues detailing them would be preferred.

**Closed by mike12345567** 2024-07-02 12:07 UTC
Labels: enhancement
