### ISSUE TITLE
In "Data" tab, rich text editor is not showing icons

### ISSUE THREAD

**Issue by sergey-vin** [Budibase/budibase#9696] opened 2023-02-15 06:56 UTC
**Hosting**
- Cloud
  - version 2.1.13

**Describe the bug**

**To Reproduce**
1. Go to Data
2. Create a SQL DB with 1 table
3. Add several fields, including those with type "Long Text Format" and "rich text" enabled
![image](https://user-images.githubusercontent.com/1080493/218954040-432d9e7e-8b9f-46cc-aaf4-1208b6c9ec86.png)

4. Click "Create row"
5. See error
![image](https://user-images.githubusercontent.com/1080493/218954348-a6ad9bc6-a4e9-4e8f-95ec-151e3cd4d2bd.png)

**Expected behavior**
See buttons

**Screenshots**
That's what's shown there when I hover over icons
![image](https://user-images.githubusercontent.com/1080493/218954558-708903ce-b0fa-4020-833e-2748b9eb4e53.png)

**Comment by shogunpurple** [comment] 2023-02-15 08:26
Hi @sergey-vin - it appears you’ve deleted the part of the issue template that confirms you have searched the existing issues and discussions to ensure there’s no duplicates. We put it there for this exact reason:

Closing as duplicate of:
https://github.com/Budibase/budibase/issues/5947

**Closed by shogunpurple** 2023-02-15 08:26 UTC
Labels: bug
