### ISSUE TITLE
Section component does not work with repeater

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#1823] opened 2021-06-24 10:11 UTC
**Describe the bug**
I want to create a card, from scratch, and use data from my data section to populate the cards. I want to lay the cards out in a 3 column layout, so I select the Section component and select the 3 column layout. 

When used with the repeater component, the layout presets do not work - see screenshot.

There's a strong possibility I could be doing this wrong.

![Screenshot 2021-06-24 at 11 11 19](https://user-images.githubusercontent.com/49767913/123245613-e97b5600-d4dc-11eb-9951-8e25bc5f5059.png)

**Comment by aptkingston** [comment] 2021-06-29 17:12
Yea there's not a bug here, it's just how the repeater works. The repeater is a component itself, so it's taking up the first of the 3 columns in the section and just rendering it's children. Are you happy for me to close this now that I've added the container props to the repeater, so that you can now control the repeater layout and make things like a wrapping row?

**Comment by joebudi** [comment] 2021-06-29 17:48
yes!

**Closed** 2021-06-29 18:14 UTC
Labels: bug
