### ISSUE TITLE
State variables created in button group components don't show up elsewhere when trying to reference them in the builder.

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#12784] opened 2024-01-15 10:12 UTC
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.14.7
  - App Version: 2.14.7
**Describe the bug**
When creating state variables in a form block button, they don't show up when trying to reference them elsewhere. You currently have to eject the block before awareness of these state variables can be used elsewhere.

**To Reproduce**
1. Add a `formblock` component
2. Add a button inside the form block with update states actions
3. Name the state actions
4. Try and reference them outside the `Formblock`, notice they don't show up.

**Expected behavior**
Should be able to see all state variables regardless of where they are made. State variables should be able to be used anywhere at anytime.

**Screenshots**
<img width="1390" alt="Screenshot 2024-01-15 at 10 07 32" src="https://github.com/Budibase/budibase/assets/126772285/ba44e5e1-9390-48b6-be8d-f513fce82aea">
<img width="1391" alt="Screenshot 2024-01-15 at 10 07 45" src="https://github.com/Budibase/budibase/assets/126772285/aa63c07d-59d1-48ab-b2d8-4a9176b9f7be">
  
**App Export**
[state-vars-1705313520853.tar.gz](https://github.com/Budibase/budibase/files/13937630/duplication.test-export-1705313520853.tar.gz)

**Comment by ConorWebb96** [comment] 2024-01-15 12:26
Looking at this a bit more in detail it seems to be related to the button group component and not the form block component like originally thought.

**Comment by melohagan** [comment] 2024-01-31 11:16
Re-opening because I can still reproduce this one:
![Screenshot 2024-01-31 at 11 16 07](https://github.com/Budibase/budibase/assets/101575380/fcec91c8-47f1-4edb-8b5c-b829e3617950)

![Screenshot 2024-01-31 at 11 16 21](https://github.com/Budibase/budibase/assets/101575380/d97e7cd8-6116-4dd8-bed1-a9f93ba57cdf)
*Row payload is not shown in notification*.

Works for a regular button outside of a button group/

**Comment by melohagan** [comment] 2024-01-31 11:28
Closing in favour of: https://linear.app/budibase/issue/BUDI-7964/save-row-action-payload-not-useable-within-a-button-group

**Closed by melohagan** 2024-01-31 11:28 UTC
Labels: bug, forms, block, env - production, avalanche, High priority, app-state, bb-components
