### ISSUE TITLE
[BUDI-7511] Support "sort", "limit" and "skip" in MongoDB data source connector.

### ISSUE THREAD

**Issue by hoveychen** [Budibase/budibase#11809] opened 2023-09-19 10:49 UTC
**Describe the feature request**
The current implementation of MongoDB data source have no way to specify parameters for cursor.sort(), cursor.limit() and cursor.skip(). It's really frustrating to build any apps using this data source without the above parameters. 

IMO, it's quite trivial to add support based on the current implementation:
https://github.com/Budibase/budibase/blob/develop/packages/server/src/integrations/mongodb.ts#L508C31-L508C31

https://www.mongodb.com/docs/manual/reference/method/cursor.sort/
https://www.mongodb.com/docs/manual/reference/method/cursor.limit/
https://www.mongodb.com/docs/manual/reference/method/cursor.skip/

**Screenshots**
The current supported fields are just query.
![image](https://github.com/Budibase/budibase/assets/1111905/6c2b0175-561b-4011-8765-6d64e311b491)

<sub>[BUDI-7511](https://linear.app/budibase/issue/BUDI-7511/support-sort-limit-and-skip-in-mongodb-data-source-connector)</sub>

**Comment by mslourens** [comment] 2023-10-30 21:18
In order to use $skip and $sort, you have to choose Function `Aggregate` and Query Type `Pipeline`. This will give you the ability to add steps like so:
 
![image](https://github.com/Budibase/budibase/assets/1907152/029355c3-723d-4b33-83aa-4b51edd34ea4)

**Comment by melohagan** [comment] 2024-01-12 09:43
Closing as duplicate of: https://github.com/Budibase/budibase/issues/5387

**Closed by melohagan** 2024-01-12 09:43 UTC
Labels: enhancement, mongodb, linear, Low priority
