### ISSUE TITLE
Boolean picker MySQL

### ISSUE THREAD

**Issue by lcslouis** [Budibase/budibase#3606] opened 2021-11-30 19:18 UTC
**Describe the feature request**
A Boolean picker that uses the tinyint in MySQL is needed for forms it also needs to be text adjustable where 

You can have:

True
False 
Or 
Yes
No

MySQL tinyint values true = 1 false = 0

**Comment by shogunpurple** [comment] 2021-12-17 10:51
Closing as dupe of https://github.com/Budibase/budibase/issues/3080

**Closed by shogunpurple** 2021-12-17 10:51 UTC
Labels: enhancement
