### ISSUE TITLE
Sorting and searching through variables

### ISSUE THREAD

**Issue by joachimBrindeau** [Budibase/budibase#14132] opened 2024-07-10 08:51 UTC
Hello 👋

**Describe the feature request**
This feature request is for faster building and easy of use.
It would be more convenient to:
1.  have variables sorted alphabetically
2. be able to search with an autocomplete

**Screenshots**

I would see the autocomplete field here:
<img width="1034" alt="image" src="https://github.com/Budibase/budibase/assets/6870905/52036b1f-abd2-4034-b67d-7e94d212591b">

This is my first feedback, thank you for taking it in consideration! 🙏

**Comment by ConorWebb96** [comment] 2024-07-10 08:55
Hey @joachimBrindeau,

Closing as this is a duplicate of: https://github.com/Budibase/budibase/issues/11124

**Closed by ConorWebb96** 2024-07-10 08:55 UTC
Labels: enhancement, bb-filtering, bb-bindings
