### ISSUE TITLE
[BUDI-7788] "Can only search by string.email or equal._id"

### ISSUE THREAD

**Issue by andyburgessmd** [Budibase/budibase#12479] opened 2023-11-30 13:41 UTC
**Checklist**

* I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker
  * Budibase Version: 2.13.26 - but issue present from around 2.13.18
  * App Version: 2.13.26 - but issue present from around 2.13.18

**Describe the bug**
I have a data provider (internalDB) which has a filter of Owner (user type) equals binding on a form field which is a user object.

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/df24b0ec-3ef7-47f1-828a-bc1f46a9fd3f/73aea97f-29f7-416c-8152-41ebbfe29a04?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9kZjI0YjBlYy0zZWY3LTQ3ZjEtODI4YS1iYzFmNDZhOWZkM2YvNzNhZWE5N2YtMjlmNy00MTZjLTgxNTItNDFlYmJmZTI5YTA0IiwiaWF0IjoxNzAxMzUzODMwLCJleHAiOjE3MDE0NDAyMzB9.0WAGiwfdGOgkj8UrDVncaLl3qGa40FNht1ITQJ6ArY0)

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/5897fd40-f43a-4708-b147-7afde9161e9c/977fa83f-082b-4a50-9ca4-028f8cd9b466?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC81ODk3ZmQ0MC1mNDNhLTQ3MDgtYjE0Ny03YWZkZTkxNjFlOWMvOTc3ZmE4M2YtMDgyYi00YTUwLTljYTQtMDI4ZjhjZDliNDY2IiwiaWF0IjoxNzAxMzUzODMwLCJleHAiOjE3MDE0NDAyMzB9.88CIHPahCohvZFmRtrxg-1UJaZxbBwCvkhxrWrS_fQI)

But since around 2.13.18 in teh application this now shows the alert notification "Can only search by string.email or equal.\_id"

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/2281410d-fa57-4699-b30c-b73265389218/b49f8c37-c364-4410-9034-38b1d2df3a72?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC8yMjgxNDEwZC1mYTU3LTQ2OTktYjMwYy1iNzMyNjUzODkyMTgvYjQ5ZjhjMzctYzM2NC00NDEwLTkwMzQtMzhiMWQyZGYzYTcyIiwiaWF0IjoxNzAxMzUzODMwLCJleHAiOjE3MDE0NDAyMzB9.CDJJPTYcGomclZCOFdeEOazbY4KIRt7c6jYzdDn1eOc)

I have tested removing the filter on Owner which resolves the issue, however I do need that filter

**To Reproduce**

1. Create a internalDB table which has a User field
2. Create a application page
3. Create a form with a user picker
4. Then add a data provider using the internalDB table created in step 1 as the source
5. Add a filter to the data provider where the user field is equal to the form binding for the user picker from step 3
6. View the page in preview of published version

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/851c3f35-2148-4f31-8e4c-29f5b6ddd933/4c9d1f6e-c94e-4c81-8f1c-f0c1672311d6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC84NTFjM2YzNS0yMTQ4LTRmMzEtOGU0Yy0yOWY1YjZkZGQ5MzMvNGM5ZDFmNmUtYzk0ZS00YzgxLThmMWMtZjBjMTY3MjMxMWQ2IiwiaWF0IjoxNzAxMzUzODMwLCJleHAiOjE3MDE0NDAyMzB9.VefI1-X1oWjY7hfWh6B85mPNBUVSrV_OJdlyoEwCrzc)

Network request:

![image.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/f1464d2b-f758-4464-96ef-0dba578d6399/2fd58575-a137-4198-94e8-d75cd3df05cb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9mMTQ2NGQyYi1mNzU4LTQ0NjQtOTZlZi0wZGJhNTc4ZDYzOTkvMmZkNTg1NzUtYTEzNy00MTk4LTk0ZTgtZDc1Y2QzZGYwNWNiIiwiaWF0IjoxNzAxNDI1Mjk0LCJleHAiOjE3MDE1MTE2OTR9.hapEZZYVfnl74EVo7DNJqfQzAtbvoHk3jhmZyNNB0qY)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7788](https://linear.app/budibase/issue/BUDI-7788/can-only-search-by-stringemail-or-equal-id)</sub>

**Comment by melohagan** [comment] 2023-11-30 15:53
Hey @andyburgessmd 

I'm not able to reproduce this one. Are you able to share an app export?

**Comment by andyburgessmd** [comment] 2023-11-30 16:03
@melohagan yeah, can I send it to you by email though?

**Comment by melohagan** [comment] 2023-11-30 16:04
> @melohagan yeah, can I send it to you by email though?

Yes that would be perfect 👍  support@budibase.com

**Comment by melohagan** [comment] 2023-12-11 12:03
> Any progress on this since the emails?

Hey Andy, I had a quick discussion on this one and we hope to have a fix deployed today 👍

**Comment by melohagan** [comment] 2023-12-12 12:47
Hey @andyburgessmd 

A fix for this has been deployed to **2.13.37** - could you let me know if that has resolved the issue

**Closed** 2023-12-12 13:02 UTC
Labels: bug, bb-filtering, linear, High priority

**Comment by andyburgessmd** [comment] 2024-03-08 16:48
@melohagan this seems to be happening again. I'm seeing it when https://budibase.mistral-data.net/api/global/users/search returns a 400 error
![image](https://github.com/Budibase/budibase/assets/110813989/0bce5ef6-bbe7-4a7b-b7ed-1fbd9950775a)

**Comment by melohagan** [comment] 2024-03-08 17:09
Hey @andyburgessmd 

The original issue was in relation to the user field, whereas this one appears to be the public API. Would you mind raising a new separate bug report please?

**Comment by andyburgessmd** [comment] 2024-03-11 09:18
@melohagan https://github.com/Budibase/budibase/issues/13228
