### ISSUE TITLE
postgres delete column in DB , but still display in app

### ISSUE THREAD

**Issue by wenzhixue** [Budibase/budibase#7010] opened 2022-07-31 15:14 UTC
report bug
1: remove one colum in postgres use shell, 
2: in app source, click fetch table, updated successfuly. 
3: the colum is still existed in the app table

**Comment by insomniacj93** [comment] 2022-08-01 07:07
This issue is related to the discussion #6737 
Happens with both postgres and mysql database connections.

**Comment by mike12345567** [comment] 2022-08-01 16:39
Closing as duplicate of #6737.

**Closed by mike12345567** 2022-08-01 16:39 UTC
Labels: bug
