### ISSUE TITLE
[BUDI-6819] Numeric values with 0 as default value will not show the 0 in forms

### ISSUE THREAD

**Issue by AlejandroFNadal** [Budibase/budibase#10182] opened 2023-03-31 13:49 UTC
**Checklist**
- [x ] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method:  docker compose
  - Budibase Version: 2.4.43.

**Describe the bug**
In a form, with a numeric field, if you set up the default value to be "return 0" in Javascript, it will not show a 0 in the field. It will show it empty.

**To Reproduce**
1. Create a form
2. Add a numeric field
3. Set a random label
4. Set return 0; as default value (in javascript)
5. Preview app and check.

**Expected behavior**
I expect to see a 0

**Screenshots**
![image](https://user-images.githubusercontent.com/32724827/229137290-3a19ca1f-dff5-4fec-8592-2875d574e3f6.png)
  

**Desktop (please complete the following information):**
 - OS: Linux 6.x
 - Browser: firefox
 - Version 102.8.0

<sub>[BUDI-6819](https://linear.app/budibase/issue/BUDI-6819/numeric-values-with-0-as-default-value-will-not-show-the-0-in-forms)</sub>

**Comment by AlejandroFNadal** [comment] 2023-04-04 07:56
For any BB user having to deal with this issue, you can set a placeholder to 0. In that way, whenever the default value doesnt show, the placeholder will show a 0. A temporal workaround, but not a solution.

**Comment by shogunpurple** [comment] 2023-04-04 13:41
Closing as dupe of https://github.com/Budibase/budibase/issues/10118

**Closed by shogunpurple** 2023-04-04 13:41 UTC
Labels: bug, linear

**Comment by AlejandroFNadal** [comment] 2023-04-04 14:00
Hey @shogunpurple , are you sure this is a duplicate? Because the other bug only mentions dynamic filtering, while this bug is just the default value of any numeric field in a form.
