### ISSUE TITLE
Trying to duplicate any screen throws error

### ISSUE THREAD

**Issue by MSrubar** [Budibase/budibase#5820] opened 2022-05-11 11:05 UTC
After updating to new build 1.0.150 I can not duplicate any screen.

**Comment by aptkingston** [comment] 2022-05-11 11:12
Closing as dupe of https://github.com/Budibase/budibase/issues/5809. I'll get this fixed :+1:

**Comment by shogunpurple** [comment] 2022-05-11 11:12
Closing as dupe of https://github.com/Budibase/budibase/issues/5809

**Closed by aptkingston** 2022-05-11 11:12 UTC
Labels: bug
