### ISSUE TITLE
My account stopped working a couple of days after enabling SSO with Azure AD. Can't access with user and pass, cant add one user.

### ISSUE THREAD

**Issue by cnrodrig** [Budibase/budibase#9898] opened 2023-03-06 18:29 UTC
**Checklist**
- [X ] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID:  dforge

**Describe the bug**
I enabled SSO with Azure AD and everything worked fine until today. The Login with Microsoft option dissapeared. 
When i try to go to https://dataforge.budibase.app/builder i get redirected to the main budibase login page.
Then i tried to login with user and pass and received a "invalid credentials" message. 
When i tried to recover password i received the message "unable to reset password". 
I don't know why but i could enter using login with google (my email @dataforge.cl was migrated from google to microsoft two years ago)
I was able to acces my tenant only after i "disable" login with google (but after i come back is enabled by default).
I still can't access using my user and pass. And strangely i can't add the user with email miguel.branada@dataforge.cl
Can't change password

**To Reproduce**
**Screenshots**
 
![image](https://user-images.githubusercontent.com/6564749/223198648-221a5179-c6c2-4466-9970-6e29fa352d03.png)

![image](https://user-images.githubusercontent.com/6564749/223198799-7bced1b6-f582-4caf-bc38-d2eb7543151b.png)

![image](https://user-images.githubusercontent.com/6564749/223203501-dfa5295c-4cb8-4044-bf9e-f4430b753b76.png)

![image](https://user-images.githubusercontent.com/6564749/223204227-23ff8f7d-cc62-4690-ba94-1b55b080468d.png)

![image](https://user-images.githubusercontent.com/6564749/223204327-9c532529-645e-4e90-8117-42b3d5ea3b07.png)

![image](https://user-images.githubusercontent.com/6564749/223204384-4ebb92da-6bc9-46dc-aee5-efae468d033a.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome
 - Version 110.0.5481.178

**Comment by Rory-Powell** [comment] 2023-03-06 20:04
Hi @cnrodrig, I'll try to provider as much clarification on your points as possible:

> When i try to go to https://dataforge.budibase.app i get redirected to the main budibase login page.

This is because there is no sso configuration. The default behaviour is to redirect to the main account portal login page when there is no in-tenant sso configuration. 

> Then i tried to login with user and pass and received a "invalid credentials" message.

This is the expected behaviour for SSO users - passport operations are no longer permitted for security purposes

> When i tried to recover password i received the message "unable to reset password".

As above.

> I don't know why but i could enter using login with google (my email @dataforge.cl was migrated from google to microsoft two years ago)

Login is permitted using any SSO provider. In this case your user has been marked as an OIDC / Microsoft user, and you will also be able to login using other SSO configurations provided the emails match (including the built-in google login at the account portal level)

Also note that logging in at the account portal level is redirecting you into your correct tenant `dforge`. As opposed to `dataforge` above. 

> I was able to acces my tenant only after i "disable" login with google (but after i come back is enabled by default).

Perhaps you haven't pressed the `Save` button on the google configuration after you disabled it? This is a common source of confusion as some of our forms auto save and others require a save. 

I believe the reason why you were able to access your tenant was the logout redirected you to the correct login page https://dforge.budibase.app

> And strangely i can't add the user with email <redacted>

This suggests the user is already in use, in another tenant

**Closed by Rory-Powell** 2023-03-06 20:04 UTC
Labels: bug
