### ISSUE TITLE
"test" helper not showing up in helper list

### ISSUE THREAD

**Issue by aptkingston** [Budibase/budibase#14201] opened 2024-07-19 09:48 UTC
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
Latest master in dev, some self hosted versions? Waiting for a reply in discord. Seems fine in cloud.
https://discord.com/channels/733030666647765003/1022503693867823104/1263778653158899712
Perhaps it's broken in SQS tenants but working in others in cloud.

**Describe the bug**
Formula columns which reference other columns simply return `false` instead of the column value.
A quick example: 
My table has a "test" column with the value of "value" which I'm trying to use in my formula.
![image](https://github.com/user-attachments/assets/8b940d05-bb1f-4015-b365-567e43a5dd80)

This resolves to:
![image](https://github.com/user-attachments/assets/d1136d23-e220-4110-aecf-ca96d3bd46b2)

Using a JS formula works as expected, so it's specifically an issue with HBS:
![image](https://github.com/user-attachments/assets/4159dd2b-ece1-4e2f-9b97-5ee7e507c4a4)

**Comment by mike12345567** [comment] 2024-07-22 15:07
@aptkingston - `test` is a helper - however it doesn't appear to be showing up in the helper list, I believe this is the cause (its used for testing regex against a string, so test with no parameters is always false).

**Comment by aptkingston** [comment] 2024-07-22 15:13
Ah interesting! That would mean that all helper names are technically reserved words then when it comes to column names, as otherwise they would conflict and not work in formula columns... We may need to stop using the column names directly as bindings then, and prefix them with `columns.` or something. Breaking change though.

**Comment by mike12345567** [comment] 2024-07-24 10:03
Closing this issue - if we want to do something about helpers being keywords that are not usable for column names, or prefixing data in bindings to avoid overlap with helpers we should open a separate issue for this.

**Closed by mike12345567** 2024-07-24 10:03 UTC
Labels: bug, firestorm

**Comment by aptkingston** [comment] 2024-07-24 11:15
I'll create a new issue so that we at least ensure people are aware that formula columns don't work if your column names clash with helpers, since it's something people are already hit and we don't want to forget about it.
