### ISSUE TITLE
 Cant set relationship picker default value via app state

### ISSUE THREAD

**Issue by Melliiiii** [Budibase/budibase#12824] opened 2024-01-21 18:50 UTC
I tried to set a default value with prior defined app state. I know the app state is updatetd correctly. but I only receive 'null' as default value. I read a previous issue from 2022 but i cant get it to work. Sorry if i oversee something I am new with budibase

**Comment by ConorWebb96** [comment] 2024-01-22 11:01
Hey @Melliiiii,

Can you re-create and follow the bug template. There isn't really enough information to go off of here. I am closing this for now, as the bug template provides a lot of useful information we would likely need to debug and verify that this is a bug.

Thanks in advance.

**Comment by ConorWebb96** [comment] 2024-01-22 11:02
If its not a bug, then feel free to create a discussion for this [here](https://github.com/Budibase/budibase/discussions/new/choose).

**Closed by ConorWebb96** 2024-01-22 11:01 UTC
