### ISSUE TITLE
Fields with Default Values Not Passing Validity Check on PostgreSQL

### ISSUE THREAD

**Issue by apparentlyjeff** [Budibase/budibase#10279] opened 2023-04-12 19:14 UTC
**Hosting**
- Self
  - Method: docker
  - Budibase Version: 2.5.2
 
**Describe the bug**
A table with default values for non-null fields still results in a budibase error when saving, if those fields haven't been assigned data, in PostgreSQL.  A message is displayed for each field in question that states, "field can't be blank"

**To Reproduce**
1. Create a table with some fields set to NOT NULL and with a DEFAULT value set.
2. Make a Budibase form/button to save to that table, but leave out the fields with the default value set.
3. Clicking on the action you've set to save to the table results in the error.

**Expected behavior**
Prior versions didn't display an error message and simply passed the data through, allowing the default value to fill in for you.

**Comment by melohagan** [comment] 2023-04-14 09:42
Hey @apparentlyjeff 

Thanks for raising, but closing as duplicate of: https://github.com/Budibase/budibase/issues/10271

I have a PR out for the fix.

**Comment by melohagan** [comment] 2023-04-14 10:05
I may have jumped the gun on this one actually. I'm quite sure it is related to the other issue, but not quite the same, and the fix won't necessarily work in this case unless the fields in question are options pickers?

Could you clarify a couple of things for me please, and some screenshots would be helpful too!

The DEFAULT value. That's in your Postgres schema or in the Budibase fields of the Design section? Could you provide the CREATE script of your Postgres table so that I could test it?

**Comment by apparentlyjeff** [comment] 2023-04-14 13:42
I'm using PostgreSQL tables for the most part, and this is where I've noticed the issue:

CREATE TABLE IF NOT EXISTS public.bb_user_clients
(
    id integer NOT NULL DEFAULT nextval('bb_user_clients_seq'::regclass),
    client_id integer NOT NULL,
    user_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_by character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by character varying(100) COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT bb_user_clients_pkey PRIMARY KEY (id)
)

My save button only fills out the pertinent information, leaving the created_at and updated_at rows empty so the database can fill with the current_timestamp for me.
![image](https://user-images.githubusercontent.com/15859008/232059488-90d93da3-e0d0-4b10-bdc0-c4cc9479cbf2.png)

When using the app and saving, I get this:
![image](https://user-images.githubusercontent.com/15859008/232059728-c00db567-e0ff-4c14-ac98-a1a904b49ecf.png)

**Comment by mike12345567** [comment] 2023-04-14 17:09
Hi @apparentlyjeff I am working on a fix for this issue - this is a duplicate issue.

https://github.com/Budibase/budibase/pull/10312
https://github.com/Budibase/budibase/issues/10221

Going to close this issue.

**Closed by mike12345567** 2023-04-14 17:09 UTC
Labels: bug, awaiting response
