### ISSUE TITLE
Button group actions not working

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#12803] opened 2024-01-17 13:26 UTC
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

Using Budimaster (Cloud)

The action button is not working when using the button group component.
https://vimeo.com/903680667/d6ed88beeb?share=copy

**Comment by joebudi** [comment] 2024-01-17 13:30
Actions do work - but only when you change the Button text. I still believe this is a bug.

**Comment by ConorWebb96** [comment] 2024-01-17 13:35
Closing as its a duplicate of this. https://github.com/Budibase/budibase/issues/12784

**Closed by ConorWebb96** 2024-01-17 13:35 UTC
Labels: bug
