### ISSUE TITLE
When you change a design prop on a component, the parent screen is selected

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#833] opened 2020-11-09 09:18 UTC
**Describe the bug**
When I change a design prop, the parent screen is selected in the navigation panel.

**To Reproduce**
1. Create a screen
2. Create a component
3. Change more than one of the components design props
4. Notice the screen is selected after each design change

**Expected behavior**
The component should continue to be selected

**Screenshots**
https://www.loom.com/share/795a7eda18a64809b8c210fec37c62c0

**Desktop (please complete the following information):**
 - Mac

**Comment by aptkingston** [comment] 2020-11-09 09:48
Looks to be a consequence of setting the selection states to be a screen whenever saving a screen, which is called whenever editing components. 
![bug](https://user-images.githubusercontent.com/9075550/98525613-9b2c8600-2270-11eb-80e9-9937623fa4ca.PNG)
I'll let one of the guys who did the rewrite handle this though since they know it better. 👍

**Comment by shogunpurple** [comment] 2020-11-09 11:35
Should be resolved in the above PR 👍

**Comment by shogunpurple** [comment] 2020-11-09 20:16
Confirmed resolved in 0.3.5

**Closed by shogunpurple** 2020-11-09 20:16 UTC
Labels: bug
