### ISSUE TITLE
How to see the automation logs ?

### ISSUE THREAD

**Issue by newtonlaw95** [Budibase/budibase#5599] opened 2022-04-26 18:38 UTC
How to check the automation logs ? If a automation task has been ran successfully or failed where can i see the this data in budibase ?

**Comment by joebudi** [comment] 2022-04-26 19:31
Hi @newtonlaw95 . This is not possible right now, but it is coming soon:
https://github.com/Budibase/budibase/issues/4977

**Comment by mike12345567** [comment] 2022-05-11 12:18
closing as duplicate of #4977.

**Closed by mike12345567** 2022-05-11 12:18 UTC
Labels: bug
