### ISSUE TITLE
Document Update Conflict - Issue after latest update

### ISSUE THREAD

**Issue by JayP718** [Budibase/budibase#6691] opened 2022-07-13 22:17 UTC
Issue after latest update. Random error where when I refresh the page it states document update conflict. 

Some previous threads state that this is due to nested data providers. However, this only happened recently after the latest update.

![image](https://user-images.githubusercontent.com/42209052/178846315-6eab77d0-b497-47d1-b047-ede5302cf83c.png)

**Comment by aptkingston** [comment] 2022-07-14 08:42
Hi @JayP718. Does this happen just when you're using the builder, or when you're actually using your app as well? Are you saving data as soon as the page loads?

**Comment by poirazis** [comment] 2022-07-14 08:57
Hey @aptkingston 
I can confirm it happens while designing.

**Comment by JayP718** [comment] 2022-07-14 10:05
Hi @aptkingston,

Same happens in both. We aren't saving anything as soon as the page loads.

@poirazis Glad it's not just me. Thanks for chiming in.

**Comment by JayP718** [comment] 2022-07-14 11:03
Does this help?
```

Trace: {
  error: 'conflict',
  reason: 'Document update conflict.',
  status: 409,
  name: 'conflict',
  message: 'Document update conflict.',
  stack: 'Error\n' +
    '    at generateErrorFromResponse (/app/node_modules/pouchdb/lib/index.js:694:18)\n' +
    '    at /app/node_modules/pouchdb/lib/index.js:6816:19\n' +
    '    at runMicrotasks (<anonymous>)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:95:5)',
  docId: 'screen_f3e3d025f4c748ad93659ec41d687a0e'
}
    at /app/dist/api/index.js:74:21
    at Generator.throw (<anonymous>)
    at rejected (/app/dist/api/index.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by PaulMcF1987** [comment] 2022-07-14 15:29
@aptkingston @JayP718 @poirazis 
I have the same issue, I opened a bug issue on it as well - https://github.com/Budibase/budibase/issues/6670

**Comment by JayP718** [comment] 2022-07-14 18:52
@PaulMcF1987 

Thanks for chiming in, glad it's not just me. I'm getting 400 errors too I sent part of the docker logs.

Everything was working smoothly prior to this update, hopefully it's not a tough fix.

**Comment by poirazis** [comment] 2022-07-16 08:02
Hey @aptkingston 
any progress on this ? Should we continue building with v.1.1.4 or do we risk corrupting our app ?

**Comment by shogunpurple** [comment] 2022-07-16 10:23
@poirazis https://github.com/Budibase/budibase/pull/6733 is currently in review and will hopefully address many of the 409 issues mentioned here - since it’s the weekend we will get this one verified and released early next week. 

Thanks

**Comment by JayP718** [comment] 2022-07-22 09:34
Hi @shogunpurple,

Is there a new estimated release date for [6733](https://github.com/Budibase/budibase/pull/6733)

**Comment by shogunpurple** [comment] 2022-07-22 09:36
Hi @JayP718 - this one is released and in the latest version. Are you still having issues?

**Comment by PaulMcF1987** [comment] 2022-07-22 09:38
@shogunpurple I have version 1.1.17 and still having issues. I have checked for updates but it is telling me that I am up to date

**Comment by JayP718** [comment] 2022-07-22 09:38
Yes, unfortunately. @poirazis has the issue been resolved for you?

**Comment by PaulMcF1987** [comment] 2022-07-22 09:41
@shogunpurple Ignore the above, my instance has just updated to 1.1.21.
Ill let you know how I get on with it!

**Comment by PaulMcF1987** [comment] 2022-07-22 09:44
@shogunpurple 
error still happening

![image](https://user-images.githubusercontent.com/75368133/180412782-4cfc6316-3c53-4be7-bd97-44a6280f652a.png)

**Comment by aptkingston** [comment] 2022-07-22 09:57
This particular issue looks like something different - since it's happening inside the actual client apps and looks to be triggering on custom queries and relationships. That's very strange to me because 409s are intrinsic to couch and a custom query on an external datasource should not be affecting couch. Could this be related to something like updating quota usage? Just trying to think what couch writes we would do when executing a custom query.

**Comment by PaulMcF1987** [comment] 2022-07-22 10:00
@aptkingston the bug report that I opened initially shows the erros I have been having - https://github.com/Budibase/budibase/issues/6670

The errors come with custom queries and also `Relationship selectors`. where the relationship drop down does not populate

**Comment by JayP718** [comment] 2022-07-22 10:25
Is there an similarities between our set ups @PaulMcF1987? 

For example, I'm using sql server on the back end and running Budibase on a Linux VM.

**Comment by PaulMcF1987** [comment] 2022-07-22 10:36
@JayP718 I am using a MariaDB self hosted DB and hosting on an Ubuntu 20.04 server.

**Comment by aderici** [comment] 2022-07-22 20:37
We have a dashboard page that loads 4-5 external api requests and we started very oftenly seeing 429 errors on this page. No writes, just loading data from external sources

**Comment by aderici** [comment] 2022-07-26 22:01
updated to 1.1.25 and this might have fixed it. I noticed the "latest" wasnt updated recently so i picked the specific 1.1.25 image when building my single image

**Comment by JayP718** [comment] 2022-07-28 15:38
Looks like the latest update took care of the  issue. Thanks @aptkingston  @shogunpurple

**Comment by shogunpurple** [comment] 2022-07-28 15:39
Excellent news - closing this one for now

**Closed by shogunpurple** 2022-07-28 15:39 UTC
Labels: bug, sev1
