### ISSUE TITLE
REST API connection issue   write EPROTO 0058A848677F0000:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled:../deps/openssl/openssl/ssl/statem/extensions.c:921:

### ISSUE THREAD

**Issue by raventechnologiesinc** [Budibase/budibase#12757] opened 2024-01-10 17:49 UTC
**Checklist**
- [ x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
raventech.budibase.app -->

**Describe the bug**
I am attempting to connect with REST API. (Vietnam Server)

On test environment everything works fine.  POST and GET returns expected response.

https://my-uat.vnpost.vn/MYVNP_API/customer-partner/getOrder?type=2&code=EM990033790VN

Once on the production environment. The underlying error occurs.
https://connect-my.vnpost.vn/customer-partner/getOrder?type=2&code=EM990033790VN

ERROR:

 write EPROTO 0058A848677F0000:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled:../deps/openssl/openssl/ssl/statem/extensions.c:921:

We have given our API host these IP to whitelist.

34.246.43.190
34.255.55.113
3.248.69.251
18.203.209.221

API Tech support have used our credentials to connect with API in country without issues, using PostMan.  Their servers sits in Vietnam.  BB is where?  Is this error related to firewall or something else.

Is whitelisting only thing to do, or is there another step.

**To Reproduce**
Can provide token to test from BB intranet

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome

**Comment by raventechnologiesinc** [comment] 2024-01-12 07:55
![z5058428624887_5f76fc798f6ed66bae8e07b0b3bee33c](https://github.com/Budibase/budibase/assets/156072718/20c52667-6798-427d-9fa2-77f2edf47816)

**Comment by raventechnologiesinc** [comment] 2024-01-15 15:30
Hello can anyone help?

**Comment by calexiou** [comment] 2024-01-15 16:51
> Hello can anyone help?

hey, the error message you're seeing is being thrown from Budibase because of a protocol error. Budibase is Node.js-based based and it uses OpenSSL as the underlying library to make SSL renegotiations. The last part of the error you're seeing is the most indicative of what's hapenning:

`final_renegotiate:unsafe legacy renegotiation disabled`

The error is caused by an attempt to perform an SSL renegotiation using a method that is considered unsafe and legacy. While your test environment has updated SSL settings your production does not.

_An analysis of your test server._
https://www.ssllabs.com/ssltest/analyze.html?d=my-uat.vnpost.vn

_An analysis of your production server._
https://www.ssllabs.com/ssltest/analyze.html?d=connect-my.vnpost.vn

Unfortunately, your production server has no support for secure SSL renegotiation. Here you can find more details about [why this is bad.](https://blog.qualys.com/product-tech/2010/10/06/disabling-ssl-renegotiation-is-a-crutch-not-a-fix-2?_ga=2.153046521.1920107240.1705336971-484109268.1705336971)


It's not something that we can fix at Budibase. Closing this issue. If you update your production server SSL settings and you are still encountering this error, please feel free to reopen an issue with updated information.

**Closed by calexiou** 2024-01-15 16:51 UTC
Labels: bug
