### ISSUE TITLE
Automations run only with Significant Delay

### ISSUE THREAD

**Issue by 3699n** [Budibase/budibase#7323] opened 2022-08-17 08:57 UTC
### Discussed in https://github.com/Budibase/budibase/discussions/7293

<div type='discussions-op-text'>

<sup>Originally posted by **3699n** August 16, 2022</sup>
I have created several on "New Row" and "Update Row" automations. 

- One automation sends an email when a new row is added
- The second automation makes a REST GET request when a new row is added and updates the row with additional data
- The third automation does the same as the first, but on "row update"

When running the tests, the automations work flawlessly. However, once published, the automations only actually execute hours after the respective rows are added or updated. What could be causing this issue? 

I'm using BudibaseDB
When I look at my automation history, all of the automations run succesfully, but only a day later at 07:30
</div>

**Comment by adamjdavies** [comment] 2022-08-17 13:36
I've noticed this today too. My automation runs instantly when testing, but has yet to actually run when triggered on the published version of my app.

**Comment by kasgithub8** [comment] 2022-08-18 08:54
Same problem here, my automations get executed at 14.40 Central European Summer Time.

**Comment by Rory-Powell** [comment] 2022-08-18 09:54
Hi all, could you each confirm if you are using budibase cloud or self hosting please

**Comment by kasgithub8** [comment] 2022-08-18 10:17
> Hi all, could you each confirm if you are using budibase cloud or self hosting please

My team is self hosting.

**Comment by adamjdavies** [comment] 2022-08-18 10:18
> Hi all, could you each confirm if you are using budibase cloud or self hosting please

I'm using Budibase cloud. 

My automation triggers when a new row is created in a Budibase table. It then executes an external data connector to push this new data to an airtable base.

**Comment by 3699n** [comment] 2022-08-18 10:59
I'm using Budibase cloud

**Comment by Rory-Powell** [comment] 2022-08-18 14:29
@3699n @adamjdavies could you confirm the tenant id of your budibase cloud instances?
that'll be the part in the url like <tenantid>.budibase.app

**Comment by adamjdavies** [comment] 2022-08-18 14:34
@Rory-Powell  - mine is **tern**.budibase.app

**Comment by kasgithub8** [comment] 2022-08-18 15:21
Any updates on this matter? It just came out of nowhere and Automations are really important!

**Comment by Rory-Powell** [comment] 2022-08-18 16:24
Hi @kasgithub8, we're looking into the issue. Thanks for your patience. The issue stems from a delay in automations being processed from the main redis queue.

**Comment by kasgithub8** [comment] 2022-08-18 16:37
> Hi @kasgithub8, we're looking into the issue. Thanks for your patience. The issue stems from a delay in automations being processed from the main redis queue.

Oh okay. Thanks for the answer tho!

**Comment by Rory-Powell** [comment] 2022-08-18 16:39
@kasgithub8 did you experience the issue after an update? if so do you know which versions you went to -> from?

**Comment by kasgithub8** [comment] 2022-08-19 06:41
Seems like it's fixed now!

**Comment by 3699n** [comment] 2022-08-19 08:15
@Rory-Powell Mine is fintale.budibase.app

**Comment by Rory-Powell** [comment] 2022-08-22 09:47
Hi all, this should now be resolved. 

Over the weekend we deployed a change to the cloud environment for better handling for stalled jobs, which was the cause of the delay in new automations processing. We've added better monitoring and alerting around this and have been keeping an eye on it, everything appears to be processing smoothly now. 

For self host this change has been released in `1.2.47`

**Closed by Rory-Powell** 2022-08-22 09:47 UTC
Labels: sev2 - severe

**Comment by poirazis** [comment] 2022-08-22 12:42
Hey @Rory-Powell ,
dunno if this is related or not, but I have a Webhhook automation that should Create a new Row upon being called.
when these automation issues first appeared, i was unable to test the automation as i was getting errors as discussed here. #7132 

Now, i have applied the 1.2.47 update, the "Finish and test" work fine, and the row is inserted after the test, but when i call the webhook from outside, the automation doesn't get triggered.

**Comment by Rory-Powell** [comment] 2022-08-22 13:42
Hi @poirazis, the issue shouldn't be related to webhook triggers. 

The first thing I would suggest is to make sure you are using the trigger url and not the schema url for triggering the webhook:
![Screenshot 2022-08-22 at 14 41 05](https://user-images.githubusercontent.com/8755148/185935284-2a0bf164-26e3-419c-9f84-74d1d7a2b5c7.png)

Secondly make sure the app is published and you are viewing the published app to confirm the automation has triggered. 

If this is still an issue please raise another issue and we can debug further.

**Comment by kasgithub8** [comment] 2022-08-23 11:54
@Rory-Powell hey, Idk what's happening but my automations are not working again and files that got attached to rows last week don't exist anymore.

**Comment by Rory-Powell** [comment] 2022-08-23 11:58
Hi @kasgithub8, you can inspect the bull dashboard to view the state of your jobs by visiting 
`http://<app-service-host>:<app-service-host>/bulladmin`. 

Can you check if you have a large amount of jobs in the `waiting` stage. It could be that you have an automation that is backing up the queue. 

To get access to the dashboard you'll have to enable port forwarding to your app-service container

**Comment by kasgithub8** [comment] 2022-08-23 13:45
Hi @Rory-Powell,

its the delay again. 😞

**Comment by Rory-Powell** [comment] 2022-08-23 13:46
@kasgithub8 check out my comment above, there are some debugging steps for self hosted automations

**Comment by dewdeded** [comment] 2022-09-29 11:58
In which container is the bulladmin interface?
We have the old 7 container deployment.
