### ISSUE TITLE
[BUDI-7235] Create automations can't run off one another.

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#11085] opened 2023-06-30 14:14 UTC
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: 2.7.30
  * App Version: 2.7.30

**Describe the bug**
Created two different automations both run of Row Created, however the second one runs of the row creation of the first automation.

**To Reproduce**

 1. Create a new app
 2. Create 3 different tables
 3. Create 2 different automations which run off the Row Create action
 4. Setup the first automation to create a row in the 2nd table
 5. Setup the second automation to target the created row from the 2nd table
 6. Go to the design area
 7. Add a screen
 8. Add a table block
 9. Configure to allow for creating new rows with a side panel
10. Publish app
11. Create a new row in the published app
12. Go back to data area, check the rows, see the rows that have been created
13. See that the 3rd table row hasn't been created.
14. Check automation history, see only one automation has triggered.

**Expected behavior**
Both automations should be trigger and data gets entered into all the tables involved.

**Screenshots**

![Screenshot_2023-06-30_at_14.44.45.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/9266c65d-81fe-48ea-8863-80959d4c7752/fa933f8d-5074-4d09-ae82-a86003b202d4)

![Screenshot_2023-06-30_at_14.44.40.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/07766241-3dd7-402a-a93b-8b3402a1f268/c41da4bf-d490-4313-87d7-e061e7804512)

![Screenshot_2023-06-30_at_14.45.14.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/fa375cf3-b1fe-424b-8f87-4f1fe3448886/dfc1f2ca-ed61-4c73-bce1-b2994ba87353)

**App Export**

[automation-bug.tar.gz](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/f15b6487-a430-4628-bb18-ecbc85144bf2/d810e428-63f9-4707-808f-aa407afa2f01)

**Desktop (please complete the following information):**

* OS: MacOS
* Browser Brave
* Version **v1.52.129**

**Additional context**
Queries used to create the tables in Postgres in this instance.

```
CREATE TABLE posts_unsigned (
    id SERIAL PRIMARY KEY,
    title VARCHAR(100),
    content TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE posts_final (
    id SERIAL PRIMARY KEY,
    title VARCHAR(100),
    content TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMP
);
CREATE TABLE posts_final_backup (
    id SERIAL PRIMARY KEY,
    title VARCHAR(100),
    content TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMP
);
```

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7235](https://linear.app/budibase/issue/BUDI-7235/create-automations-cant-run-off-one-another)</sub>

**Comment by shogunpurple** [comment] 2023-10-25 13:27
Holding off on this until we move automations to their own infra in cloud

**Comment by melohagan** [comment] 2023-11-10 16:09
Closing as duplicate of: https://github.com/Budibase/budibase/issues/10641

**Closed by melohagan** 2023-11-10 16:09 UTC
Labels: bug, firestorm, linear, Medium priority
