### ISSUE TITLE
Hide on validation didn't empty the hidden field

### ISSUE THREAD

**Issue by agruenberg** [Budibase/budibase#7982] opened 2022-09-26 18:07 UTC
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 1.4.7

**Describe the bug**
I have a pick list and a date field. If a certain option is selected, the date field appears. If I change the selection the the date field will be hidden. The hiding process should empty the previous date field entry. But this doesn't happen.

**Expected behavior**
Data in date field should be emptied.

**Comment by kasgithub8** [comment] 2022-09-29 14:00
My guess is that you pre-fill the date field with Default Value?
If so, just add the date field into a "Save row" action on your "Create Button" and leave the value empty.

**Comment by melohagan** [comment] 2022-10-03 15:13
Hey @agruenberg I'm going to close this issue because you have not followed the bug template - reproduction steps, screenshots, app export.

Feel free to re-open if the issue is persisting with the full details!

**Closed by melohagan** 2022-10-03 15:13 UTC
Labels: bug
