### ISSUE TITLE
ERROR [1649359898497] (30 on 5b34a2f13ef1): Datasource is not configured fully.

### ISSUE THREAD

**Issue by KubaSta1** [Budibase/budibase#5305] opened 2022-04-07 19:44 UTC
**Describe the bug**
I configure simple rest GET call which is running on cloud env. I export project and import to my local env.
When i open scrren with table base on rest data source i got Internal Server Error and in logs i see 
 ERROR [1649359898497] (30 on 5b34a2f13ef1): Datasource is not configured fully.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome 
 - Version

**Additional context**

**Comment by mike12345567** [comment] 2022-04-12 17:14
Hi @KubaSta1 - closing this issue as I believe it is a duplicate of #5339 - we will get this fixed soon.

**Closed by mike12345567** 2022-04-12 17:14 UTC
Labels: bug, sev2
