### ISSUE TITLE
Data provider filter not working on google sheets backend

### ISSUE THREAD

**Issue by Franosa** [Budibase/budibase#9850] opened 2023-03-01 19:26 UTC
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker compose
  - Budibase Version: 2.3.17
  - App Version: 2.3.17

**Describe the bug**
Google Sheets table does not filter using the data provider. I have tried to use a typical view button following the docs to use the id to go to the specific row to edit. It is not working because the filter is not working for the google sheet. I then went into a table to try to filter based off of a text value and could not get it to work either. It looks like the filtering on a data provider does not work for google sheets.

**To Reproduce**
1. Setup a google sheets backend
2. input text values into the sheet
3. use a data provider to access the data and filter on any of the text values

**Expected behavior**
I believe the data provider should still allow filtering on google sheets unless I am mistaken. I do not see in the docs that it is not possible.

**Desktop (please complete the following information):**
 - OS: mac
 - Browser: Chrome
 - Version 110

**Comment by mike12345567** [comment] 2023-03-02 14:22
Hi @Franosa - closing as dupe of #8557.

**Closed by mike12345567** 2023-03-02 14:22 UTC
Labels: bug, linear
