### ISSUE TITLE
Table component not showing rows for query based on a external Rest API

### ISSUE THREAD

**Issue by fseixas** [Budibase/budibase#3262] opened 2021-11-06 00:10 UTC
**Describe the bug**
When configuring a table component to show data from a query based on an external REST API, the table component always show "No rows found"

**To Reproduce**
1. Create a data source based on a REST API and create a new Query based on this API. I used http://content.sof.to:1337/Articles
2. Create a new page
3. Add a Data Provider component and set de "Data" property to the query you created on step 1
4. Add a Table component inside the Data Provider you created on step 3
5. The Table component will always show "No rows found"
6. If you add a Repeater component under the Data provider, and add a Card component to this repeater, configure the card title to any column from the data provider, it will show the rows from the provider correctly. 

**Expected behavior**
The Table component should show the data from the data provider

**Screenshots**
![2021-11-05 20_51_22-Window](https://user-images.githubusercontent.com/2001438/140590833-45516fa4-2115-4c48-825e-dd214c0712d0.png)

![2021-11-05 20_51_50-Window](https://user-images.githubusercontent.com/2001438/140590840-7653198a-3515-43ac-9752-ac14e31fc1c1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome Version 95.0.4638.54 (Official Build) (64-bit)
 - Version 95.0.4638.54 (Official Build) (64-bit)

**Comment by aptkingston** [comment] 2021-11-09 15:58
Hey @fseixas. I've just replicated this exact setup (using the API your provided) and it works perfectly for me.
![image](https://user-images.githubusercontent.com/9075550/140958464-9c911dc1-44ca-4264-b37f-e859f38141f0.png)

I've even duplicated what settings I can see from your screenshots. Are there any errors if you open the console in developer tools?

The only thing I can think is that somehow the table has settings that is stopping it from displaying rows, but everything in your screenshot looks fine. Can you try deleting the table and adding a new one, and see if that makes your rows appear?

**Comment by callsoft** [comment] 2021-11-13 16:37
I'm having a similar issue but with an external SQL query.  Same result, table shows no data yet cards in repeater do.   

Deleting and re-adding the table didn't work.  

![image](https://user-images.githubusercontent.com/3580655/141651513-5c17b4fa-076d-49db-8b7c-6dda32607760.png)

**Comment by aptkingston** [comment] 2021-11-15 16:42
Would either one of you be able to provide me with an export of your app so I could debug this? Like I said I've tried to reproduce this using an identical setup but can't reproduce the issue. An export would really help if either of you could provide that.

**Comment by fseixas** [comment] 2021-11-15 20:47
@aptkingston The only error on the dev console is a 404 on favicon.ico. It is not related, of course.

In the Network panel of the dev console, I can see that the JSON was properly downloaded. But still, rows are now showing.

[Softo Hub-export-1637008713072.txt](https://github.com/Budibase/budibase/files/7541555/Softo.Hub-export-1637008713072.txt)

**Comment by aptkingston** [comment] 2021-11-16 10:00
Thanks @fseixas that's a great help. The reason I couldn't reproduce this was actually because I've already fixed the bug that was causing this, but we just haven't released it yet. The bug was that there's an issue determining the schema for some external datasources (including REST API's), and the table needs to know the schema to display rows. This fix will be included in our next release which will probably be towards the start of next week.

**Closed** 2021-12-02 09:23 UTC
Labels: bug
