### ISSUE TITLE
"Allow row selection" not working in tables

### ISSUE THREAD

**Issue by GabrieleLabanca** [Budibase/budibase#7193] opened 2022-08-10 09:51 UTC
**Hosting**
- Self
    - Budibase Version: 1.1.17

**Describe the bug**
When editing a table, selecting the "Allow row selection" option does not have any effect, even reloading the page.

**To Reproduce**
- create a table connected to a SQL data source
- select the "Allow row selection" option.

**Expected behavior**
The rows are selectable.

**Screenshots**
<img width="1318" alt="Screenshot 2022-08-10 at 10 41 56" src="https://user-images.githubusercontent.com/6714239/183871731-78ac716c-94fe-400d-b7c8-14b80cd565d8.png">

**Desktop (please complete the following information):**
 - iOS
 - Chrome
 - Version 104.0.5112.79

**Comment by melohagan** [comment] 2022-08-11 10:27
Hi @GabrieleLabanca 

Is your datasource a custom SQL query?

**Comment by GabrieleLabanca** [comment] 2022-08-23 06:55
@melohagan yes, PostgreSQL to be precise

**Comment by JayP718** [comment] 2022-08-24 17:40
https://github.com/Budibase/budibase/issues/7348 Hi @GabrieleLabanca 

not sure if that's related to my issue here. If your datasource is a custom sql query I don't think **allow row selection** will work. I believe it's only available for SQL tables and internal tables. I also interpreted this as SQL datasource but if you are using a custom query or a view I don't think it will work. It's a huge bummer for us to but hopefully this can be a future enhancements. If you find a work around please let me know!

**Comment by shogunpurple** [comment] 2022-08-30 13:46
@JayP718 @GabrieleLabanca thanks for raising - we're just trying to get an idea of what your use case is with selecting rows on a table driven by a custom SQL query. Are you trying to export the rows, or pass them to an automation? How are you planning to use the rows that you can select?

**Comment by JayP718** [comment] 2022-09-04 17:48
@shogunpurple thanks for asking! So we have some queries (mysql views) which join 3 tables, performs aggregations, and left outer joins. We want the user to select a batch of these records then we are looking to pass a custom sql query which uses these selected rows to make some modication within the database. We also would like to give the user the ability to export these rows as well. 

Looks like these issues are in the same realm

https://github.com/Budibase/budibase/issues/5491
https://github.com/Budibase/budibase/discussions/7517
https://github.com/Budibase/budibase/issues/7005

**Comment by GabrieleLabanca** [comment] 2022-09-06 07:53
@shogunpurple Thanks for asking! In my case, the only goal is to allow the user to export rows from the table (even the option to export them all, without selection, would be a good deal), to a csv file; so @JayP718's use case is a superset of mine.

**Comment by shogunpurple** [comment] 2022-09-06 07:56
Thank you, this is super helpful. It makes sense - we will try to have a look at this one over the next few iterations and drop any updates in here.

**Comment by shogunpurple** [comment] 2022-10-12 14:12
Dupe of https://github.com/Budibase/budibase/issues/7348

**Closed by shogunpurple** 2022-10-12 14:12 UTC
Labels: enhancement, sql

**Comment by GabrieleLabanca** [comment] 2022-10-19 11:16
I still have this issue, and it's actually a bit different from #7348: I don't see the checkboxes at all

**Comment by aptkingston** [comment] 2022-10-19 12:04
@GabrieleLabanca as mentioned above, row selection does not work for custom queries. No checkboxes will appear. It only works for SQL tables or internal tables, as stated in the settings panel:
![image](https://user-images.githubusercontent.com/9075550/196685544-70ccfb67-ed8f-479c-8229-d89f0ad3ea2a.png)
