### ISSUE TITLE
CouchDB older image version

### ISSUE THREAD

**Issue by maiducan** [Budibase/budibase#10580] opened 2023-05-14 15:41 UTC
Hello Budibasers!

I am running older version of budibase images (2.2.3) on self-hosted server and when i want to migrate to another, i encounter some issues with the newer images (couchdb container is restarting all the time) or if i download newer version, there are different issues (cannot load platform at all or other inconsistencies)

Would it be possible to upload some older versions of budibase/couchdb images? There is now only new versions 10 days old .. I would need those that are at least 1-2 months old.

Thanks for help!!
Wish you a great day

**Comment by shogunpurple** [comment] 2023-05-15 09:46
@maiducan the `budibase/couchdb` image is fairly new - we ended up building our own custom image that gets used in later versions of budibase. In your older installation, you should stick with the https://hub.docker.com/r/ibmcom/couchdb3 image.

Closing this as it's not a bug and is infrastructure based

**Closed by shogunpurple** 2023-05-15 09:46 UTC
