### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by twilson9034** [Budibase/budibase#3657] opened 2021-12-02 22:30 UTC
When using auto complete on an option picker the app freezes and have to refresh the screen to be able to do anything.

**Comment by aptkingston** [comment] 2021-12-03 09:09
Hi @twilson9034. Once again I'm unable to reproduce this. Can you please provide more information - like what steps did you take, what does your data look like, what is your relationship picker targeting.

**Comment by twilson9034** [comment] 2021-12-06 17:41
@aptkingston Here is how the screen is set up. "Vehicles" is the data provider for the bb data.
![image](https://user-images.githubusercontent.com/94488623/144893921-4121bb39-2dce-49ba-8d2f-c1bc1b01df9f.png)
That data source has no filters on it and is sorted by the "asset name" column. 
"New option picker" is the option picker with autocomplete turned on. No conditions set up. 
![image](https://user-images.githubusercontent.com/94488623/144894212-c9529df4-cbd9-4cfa-be53-0a65999f3a8e.png)

I can click on a header navigation link and the URL will change to that destination but the actual screen will not.

As soon as I type into the search bar for autocomplete I get this error log.
![image](https://user-images.githubusercontent.com/94488623/144894991-33584790-f5eb-4265-a88b-4cc0bdad3122.png)


Browser is Chrome Version 96.0.4664.45

**Comment by aptkingston** [comment] 2021-12-06 18:14
@twilson9034 thanks for the extra info 👍

**Comment by twilson9034** [comment] 2021-12-08 16:16
@aptkingston I've updated and currently on version 1.0.6, however when I still set the autocomplete on I get a new error log.
![image](https://user-images.githubusercontent.com/94488623/145243559-584118bf-fe0f-422e-938b-17ea45bed0d9.png)

**Comment by aptkingston** [comment] 2021-12-08 16:43
Hey @twilson9034. That's the same error. The fix will be released shortly - I don't believe we've published it yet.

**Comment by twilson9034** [comment] 2021-12-08 16:56
Ok, sounds good, I had an update from 1.0.5 and the info said misc bug fixes so I thought maybe this was a new error.

**Closed** 2022-01-11 10:12 UTC
Labels: bug
