### ISSUE TITLE
Add old row and new row to row updated trigger in automations

### ISSUE THREAD

**Issue by mojoaar** [Budibase/budibase#9275] opened 2023-01-09 06:23 UTC
**Describe the feature request**
I would like to suggest a "changes" condition, either on the actual trigger or on the condition event. 

Use case: if you have ex. an assigned to field and you want to send an email whenever the field changes, it would be beneficial to be able to simply tie that to a condition called "changes" (for this use case the 4 that's in the condition event cant be used). As said, the event could be on the actual trigger or on the condition event.

**Screenshots**
![changes_condition](https://user-images.githubusercontent.com/21560785/211250967-d00c50f7-ae79-4e72-bba2-736bb8e222b8.png)

**Comment by melohagan** [comment] 2023-11-10 16:12
Closing as duplicate of: https://github.com/Budibase/budibase/issues/10035

**Closed by melohagan** 2023-11-10 16:12 UTC
Labels: enhancement, short-term
