### ISSUE TITLE
"Allow multiple users" - not enforced in application

### ISSUE THREAD

**Issue by andyburgessmd** [Budibase/budibase#12302] opened 2023-11-07 09:15 UTC
**Checklist**
- I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker
  - Budibase Version: 2.13.0
  - App Version: 2.13.0

**Describe the bug**
When using the user db type in a table and having the setting "Allow multiple users" set to off I am able to add multiple users to the row in the application.

**To Reproduce**
1. Create a internal db table and add a user object with setting "Allow multiple users" off
2. Create a view with a form to interact with the table
3. Test the form and try selecting more than one user and saving the form
4. Multiple users are added into the db row

**Expected behavior**
I should not be able to select more than one user.

**Comment by melohagan** [comment] 2023-11-07 09:23
Hi @andyburgessmd 

I have a PR out to fix this one: https://github.com/Budibase/budibase/pull/12275

I'll let you know when it's deployed

**Comment by melohagan** [comment] 2023-11-07 09:41
Closing as duplicate of: https://github.com/Budibase/budibase/issues/12272

**Closed by melohagan** 2023-11-07 09:41 UTC
Labels: bug

**Comment by melohagan** [comment] 2023-11-07 15:01
Hey @andyburgessmd That fix has been deployed to **v2.13.2**.

Most likely you will need to re-save your user columns, but you don't need to delete/re-add anything.

Just go to your user column, edit, and click the `Save` button. Then that will update the user field in the Design section with the correct picker:

![Screenshot 2023-11-07 at 15 01 39](https://github.com/Budibase/budibase/assets/101575380/258b756b-eded-4019-bcc7-ae9c15caacc0)

*Save your existing single-option user columns*

**Comment by andyburgessmd** [comment] 2023-11-07 15:50
Thanks @melohagan that has worked.

**Comment by melohagan** [comment] 2023-11-07 16:00
Great to hear Andy, thanks for getting back.
