### ISSUE TITLE
Logging in via SSO or as new user deletes custom column data in Users table

### ISSUE THREAD

**Issue by manwithpowers** [Budibase/budibase#10471] opened 2023-05-02 19:59 UTC
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker single image
  - Budibase Version: 2.5.6
  - App Version: 2.5.6

**Describe the bug**
After logging in via Google SSO, all custom user data for that user in our app's Users table is wiped. Logging in via standard email/password combo doesn't seem to create the same issue EXCEPT on initial login/account creation.

**To Reproduce**
1. Create a custom column in an app's Users table
2. Put some data in that column for a user
3. Log in to Budibase with that user using Google SSO
4. Refresh the Users table and see that the data in the custom column is gone
OR
1. Create a custom column in an app's Users table
2. Create a new user and add them manually (not via invitation)
3. Put some data in that column for that user
4. Log in to Budibase with that user and temporary password
5. Refresh the Users table and see that the data in the custom column is gone

**Expected behavior**
Custom column data is retained regardless of login state or method.

**Desktop (please complete the following information):**
 - OS: Windows/MacOS
 - Browser: Chrome
 - Version: 112.0.5615.138

**Comment by manwithpowers** [comment] 2023-05-17 09:09
Just wanted to bump this issue as it's still presenting a problem for us on version 2.6.11. 
Every time one of our users logs in via Google SSO, the custom column data we have for them gets wiped.

**Comment by melohagan** [comment] 2023-06-21 10:53
Closing as duplicate of: https://github.com/Budibase/budibase/issues/10969

**Closed by melohagan** 2023-06-21 10:53 UTC
Labels: bug
