### ISSUE TITLE
Cannot Save JavaScript and Handlebars Scripts in any Bindings

### ISSUE THREAD

**Issue by kerwal** [Budibase/budibase#4560] opened 2022-02-18 01:47 UTC
**Describe the bug**
(For the online version)
I am now unable to save Javascript wherever there is a Binding field (Formula column, Save Row Action (Button), etc.).
It also won't save the text entered in the Handlebars text-area either. Copy/pasting from the text-area to the input field works tho!

**To Reproduce**
1. Create a new column in a BB table and choose Formula.
2. Click the bolt icon next to Forumla field.
3. Click JavaScript tab.
4. Poduce any script that will return a value. Like: `return 'test';`
5. Click Confirm.
6. The Formula field remains blank. It used to display "(JavaScript Function)".
7. Click Save Column.
8. Create new row.
The new Formula column remainss blank like there's no script.
The JavaScript tab also remains blank when re-entering the dialog.

The same thing happens when entering a Handlebars script in the Handlebars tab.

Entering a Handlebars script directly into the Formula field works.

**This problem does not occur in the self-host version 1.0.46**

**Expected behavior**
"(JavaScript Function)" should display in the Formula field when a JavaScript script is entered in the JavaScript tab of the Binding dialog.
Also, when entering a Handlebars script in the Handlebars tab, it should be copied/previewed in the Formula field.

**Screenshots**
<img width="351" alt="Screen Shot 2022-02-17 at 5 42 31 PM" src="https://user-images.githubusercontent.com/1286722/154601668-a1417879-6903-45fc-a268-aa0e0fd8dde7.png">
<img width="954" alt="Screen Shot 2022-02-17 at 5 42 17 PM" src="https://user-images.githubusercontent.com/1286722/154601671-dd6edc52-f147-465e-83e7-8d221e3d1f4c.png">
<img width="944" alt="Screen Shot 2022-02-17 at 5 42 06 PM" src="https://user-images.githubusercontent.com/1286722/154601674-68a2c963-76da-42ed-ade6-2ed97a03bcb1.png">
<img width="354" alt="Screen Shot 2022-02-17 at 5 41 57 PM" src="https://user-images.githubusercontent.com/1286722/154601675-2d9f57a5-34d7-44cb-be64-a5a87cf49253.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.6.2
 - Browser: Chrome 98.0.4758.102
 - Version: Online at budibase.app

**Comment by Topener** [comment] 2022-02-18 09:31
Hi @kerwal, thanks for reporting this! I appreciate the extensive bug report with reproduction steps, it really helps!

This is a known issue of which the fix is queued to release very soon. You can see more information in issue #4538. I'm closing this also as a duplicate of that ticket.

**Closed by Topener** 2022-02-18 09:31 UTC
Labels: bug
