### ISSUE TITLE
Filtering on auto column does not work for Data provider

### ISSUE THREAD

**Issue by palsivertsen** [Budibase/budibase#8787] opened 2022-11-23 16:33 UTC
**Hosting**
- Cloud

**Describe the bug**
When creating a Data Provider component and attaching a filter on the `_id` column I get an error saying `Unknown column 'devices._id' in 'where clause'`. However if I create a Table block with the same filter, then eject and strip it down to the seemingly identical Data Provider works without an issue.

**To Reproduce**
1. Set up a MySQL datasource with an example table
2. Create a new screen with a URL variable (eg. `/examples/:id`)
3. Add a Data Provider component and point it at your example data, then add a filter on the `_id` column
   ![image](https://user-images.githubusercontent.com/11890143/203592037-ddfd2d58-1432-4718-b692-2b34f818292e.png)
4. Navigate to your screen in preview mode (eg. `/examples/1`) and you should see the error
   ![image](https://user-images.githubusercontent.com/11890143/203592443-2fe54951-a9f4-4f2a-ab82-260790a3814b.png)
5. Go back to design mode and remove the faulty Data Provider
6. Add a Table Block and point it at your example data, then add a filter on the `_id` column
   ![image](https://user-images.githubusercontent.com/11890143/203592037-ddfd2d58-1432-4718-b692-2b34f818292e.png)
7. Click the "Eject block" button to reveal the individual components
   ![image](https://user-images.githubusercontent.com/11890143/203593466-bf7b88ff-5c63-4c88-a821-87630eb95337.png)
8. Prune away all but the Dataprovider component
   ![image](https://user-images.githubusercontent.com/11890143/203593695-d63cfbf2-4d48-4718-ab6d-482057e85f01.png)
9. Now when you navigate to your screen in preview mode there's no longer an error.

**Expected behavior**
I should be able to use the `_id` column for filtering on a regular data provider / All Data Provider components should behave the same.
  
**App Export**
[My app-export-1669221079618.tar.gz](https://github.com/Budibase/budibase/files/10077431/My.app-export-1669221079618.tar.gz)

**Desktop (please complete the following information):**
 - OS: Archlinux / Docker compose
 - Browser Google Chrome
 - Version 107.0.5304.110 (Official Build) (64-bit)

**Additional context**
Database setup with example data:
```
-- MySQL dump 10.13  Distrib 5.6.51, for Linux (x86_64)
--
-- Host: localhost    Database: test
-- ------------------------------------------------------
-- Server version	5.6.51

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `examples`
--

DROP TABLE IF EXISTS `examples`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `examples` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `examples`
--

LOCK TABLES `examples` WRITE;
/*!40000 ALTER TABLE `examples` DISABLE KEYS */;
INSERT INTO `examples` VALUES (1,'Alice'),(2,'Bob');
/*!40000 ALTER TABLE `examples` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2022-11-23 16:29:30

```

**Comment by melohagan** [comment] 2022-11-23 18:05
Thanks for raising the bug @palsivertsen 

It is however a duplicate of: https://github.com/Budibase/budibase/issues/8334

**Closed by melohagan** 2022-11-23 18:05 UTC
Labels: bug
