### ISSUE TITLE
My account is broken!

### ISSUE THREAD

**Issue by khalidsharif** [Budibase/budibase#12499] opened 2023-12-04 15:20 UTC
### Discussed in https://github.com/Budibase/budibase/discussions/12498

<div type='discussions-op-text'>

<sup>Originally posted by **khalidsharif** December  4, 2023</sup>
Dears,

I wonder why I am getting this message now and not able to login !! 

{
    "message": "Account not found for tenant: deenakanoo",
    "status": 500
}

It was working perfectly the day before yesterday, and now I want to continue to develop the APP but I cannot access the dashboard at all.

![image](https://github.com/Budibase/budibase/assets/50369621/697deb96-d36f-4ea1-95b2-3471782ea2e5)
</div>

**Comment by aptkingston** [comment] 2023-12-04 16:40
This is not a bug, so I'm closing this issue. Discussions is the place for this, which I see you've already posted in.

**Closed by aptkingston** 2023-12-04 16:40 UTC
