### ISSUE TITLE
Export CSV Data in Non-Latin Language does not working correctly, UTF8 is preferred

### ISSUE THREAD

**Issue by chinnaponga** [Budibase/budibase#6646] opened 2022-07-11 16:16 UTC
In Budibase 1.0.218 ,  exporting data to CSV in non-latin language,  in my case, Thai language is not working.

I found a fix committed by xnohat as in https://github.com/xnohat/budibase/pull/2. 

However, I tried to pull and re-build bbapps myself and got stuck with "Global DB Not Found" error.  

Is there any advice on how can I apply the fix ?   Or, is there any fixed roadmap / deadline on when the commit as proposed by xnohat will be rolled up to Budibase Official Update ?

Best regards,

**Comment by shogunpurple** [comment] 2022-08-31 15:05
Dupe of https://github.com/Budibase/budibase/issues/3844

**Closed by shogunpurple** 2022-08-31 15:05 UTC
Labels: bug
