### ISSUE TITLE
Possibility of changing the place holder of the Relationship Picker search filter

### ISSUE THREAD

**Issue by JCV67** [Budibase/budibase#11712] opened 2023-09-07 15:18 UTC
It would be good having a way to customize the place holder of the pre-search filter, witch is "Search by 'column label'".  'Search by' is in English and the column label isn't always readable by users. 

 -> Also, in this pre-filter, the search is of the kind "Starts with" a "Like" search type would be much better.

![image](https://github.com/Budibase/budibase/assets/104722906/f0be704e-2fb1-4a77-8311-d3c6d8971072)

**Comment by melohagan** [comment] 2023-09-18 09:11
Closing as duplicate of: https://github.com/Budibase/budibase/issues/11795

**Closed by melohagan** 2023-09-18 09:11 UTC
Labels: enhancement
