### ISSUE TITLE
Allow relationship with same table (for tree hierarchies)

### ISSUE THREAD

**Issue by karol-depka** [Budibase/budibase#10706] opened 2023-05-26 00:52 UTC
**Describe the feature request**
When adding a column of type Relationship, currently it's not possible to select the same table.
This would be essential for creating trees. E.g. category tree (my use case), Org-Chart (boss-underling, etc).

**Screenshots**
<img width="1608" alt="image" src="https://github.com/Budibase/budibase/assets/958486/76145cf0-801e-49ea-b56c-481fb868dedb">
(it does not show the same table; bummer)

**Comment by melohagan** [comment] 2023-05-26 08:50
Closing as duplicate of: https://github.com/Budibase/budibase/issues/5635

**Closed by melohagan** 2023-05-26 08:50 UTC
Labels: enhancement
