### ISSUE TITLE
[BUDI-6827] Formulas get deleted when fetching tables from a MariaDB data source

### ISSUE THREAD

**Issue by FlaminWrap** [Budibase/budibase#10193] opened 2023-04-03 10:42 UTC
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker compose
  - Budibase Version: 2.4.43
  - App Version: 2.4.43

**Describe the bug**
When using Maria DB, when you fetch the data source, the formula fields lose their contents

**To Reproduce**
1. Create a MariaDB database and connect Budibase
2. Create a formula field
3. Enter a formula 
4. Refresh the page to make sure that the formula works
5. Go to the mariadb datasource
6. Press fetch tables
7. Navigate back to formula
8. The formula is empty

**Expected behavior**
The formula does not get removed when fetching tables

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 111.0.1 
 
**Exported App**
[TestMariaDB-export-1680525594982.tar.gz](https://github.com/Budibase/budibase/files/11138317/TestMariaDB-export-1680525594982.tar.gz)

[TestMariaDB.csv](https://github.com/Budibase/budibase/files/11138341/TestMariaDB.csv)

**Gif**
![mariadb](https://user-images.githubusercontent.com/97764630/229512344-de774d39-cc84-446a-940e-320fd9f63a9b.gif)

<sub>[BUDI-6827](https://linear.app/budibase/issue/BUDI-6827/formulas-get-deleted-when-fetching-tables-from-a-mariadb-data-source)</sub>

**Comment by mike12345567** [comment] 2023-04-03 11:33
Hi @FlaminWrap - I've tried this with MySQL - I was not able to replicate this behaviour using the above steps. Just to confirm this was done using the MySQL datasource?

I've tested this on the version which is due to be released today - so if thats the case I expect updating to the version currently being released will fix it.

**Comment by FlaminWrap** [comment] 2023-04-03 12:05
Thanks @mike12345567, I shall do some more testing and report back.

**Comment by FlaminWrap** [comment] 2023-04-03 12:53
Hi @mike12345567,

I have updated budibase to the latest version and the same thing happens. I have tried it on two different instances and it happens on both. I have uploaded a test app, CSV and made a gif of the error to help.

**Comment by FlaminWrap** [comment] 2023-04-03 13:28
Hi, I will setup a mysql instance tonight a do the same tests. Here is a screenshot of the columns from phpMyAdmin

![image](https://user-images.githubusercontent.com/97764630/229523744-10e208fa-97ea-45bd-ae80-8ee0d2e64797.png)

**Comment by mike12345567** [comment] 2023-04-04 09:22
Hi @FlaminWrap - just to confirm, the same issue occurs when using the MySQL instance as well? Could you try the latest version of Budibase v2.4.44?

**Comment by FlaminWrap** [comment] 2023-04-04 11:17
Hi @mike12345567 I have been able to replicate it with mysql 8.0.30

**Comment by FlaminWrap** [comment] 2023-04-04 13:38
Hi @mike12345567 

I did some more testing and it appears that it can also do it when changing another formula column, I have not been able to reproduce this problem reliably though. I have updated our BB instance and app to 2.5.0.

![updateformula](https://user-images.githubusercontent.com/97764630/229806321-9a48a850-4c80-46ab-8a51-e59f6fcb4b7b.gif)

**Comment by shawnweeks** [comment] 2023-05-22 17:46
I'm seeing similar behavior on PostgreSQL. After saving a formula column and going back to that column to edit the formula has been reset to nothing. This is without doing a table refresh.

<img width="448" alt="Screenshot 2023-05-22 at 12 45 25 PM" src="https://github.com/Budibase/budibase/assets/9768773/efe96932-f174-4bdc-aeb7-8f68cbadf731">
<img width="429" alt="Screenshot 2023-05-22 at 12 45 35 PM" src="https://github.com/Budibase/budibase/assets/9768773/694b2537-b00d-4872-ae0c-50626babc993">

**Comment by shawnweeks** [comment] 2023-05-22 19:53
I've also confirmed that fetching the table list from PostgreSQL wipes out calculated formulas even if no columns have changed in the table.

**Comment by manwithpowers** [comment] 2023-05-31 06:50
I can confirm this same problem on 2.6.20 using an external MySQL database. Every time I fetch tables, my formula columns get wiped.

**Comment by adrinr** [comment] 2023-07-04 14:25
Fixed in 2.7.30 https://github.com/Budibase/budibase/issues/10670#issuecomment-1603142791

**Closed** 2023-07-04 14:28 UTC
Labels: bug, firestorm, linear, bb-datasource, bb-data-ui
