### ISSUE TITLE
S3 Upload does not work on public forms - "Session not authenticated"

### ISSUE THREAD

**Issue by jasonford1** [Budibase/budibase#11901] opened 2023-09-26 23:34 UTC
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: newwheel

**Describe the bug**
S3 Upload - Component does not work on public form. Public user gets "Session not authenticated"

**To Reproduce**

1. Add an S3 Upload to a Form
2. Add an upload action
3. Execute upload action as a Public user
4. See error - "Session not authenticated"

**Expected behavior**
Authentication not required when form schema is set to a table with public read/write privileges. In my case the form is set to a PostgreSQL table with public access privleges.

**Screenshots**
![Screenshot 2023-09-26 at 12 56 12 PM](https://github.com/Budibase/budibase/assets/41327322/446a3a49-243d-47b9-b4c4-66a1a13c6fb4)

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.5.2
 - Arc Browser 1.9.2

**Additional context**
I run an electric bike shop with multiple retail locations. We want to move to Budibase for internal tooling with customer input sometimes required. The S3 Upload is our ideal solution if it allows Public upload. The attachment component is a non-starter because the customer gets "Access Denied" when we programmatically share PDFs back to them. Is there a path for allowing public upload and public sharing back to the customer?

**Comment by melohagan** [comment] 2023-09-27 08:59
Closing as a duplicate of: https://github.com/Budibase/budibase/issues/8975 (as you are already familiar with!)

I will take a look at this one when I get a chance, but we are actively busy!

**Closed by melohagan** 2023-09-27 08:59 UTC
Labels: bug

**Comment by jasonford1** [comment] 2023-09-27 15:40
Thanks @melohagan. I appreciate the straightforward answer. Wish you all the best!
