### ISSUE TITLE
Related table columns not displaying in search

### ISSUE THREAD

**Issue by accesstechnology-mike** [Budibase/budibase#9497] opened 2023-02-01 09:40 UTC
**Hosting**
- Self
  - Method: docker
  - Budibase Version: 2.2.19

**Describe the bug**
Search boxes for related table columns not displaying

**To Reproduce**
1. Define relationship between 2 tables
2. Add column of related table
3. Add search field for related table column
4. No search box appears

**Expected behavior**
A search box should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/55278705/216006723-29854c9e-1d3c-4a36-9e5c-31eba9e10b31.png)

**Comment by melohagan** [comment] 2023-02-01 11:43
Hey @accesstechnology-mike 

This is a duplicate of this issue: https://github.com/Budibase/budibase/issues/9379

It may have been closed a little prematurely, but it should be fixed with the new release next Monday!

**Comment by aptkingston** [comment] 2023-02-01 14:14
> Hey @accesstechnology-mike
> 
> This is a duplicate of this issue: #9379
> 
> It may have been closed a little prematurely, but it should be fixed with the new release next Monday!

Just to follow up on this - it also only works with SQL datasources, but not with internal tables. OP here didn't specify their datasource type, so I'm just clarifying that they should only expect this to work if they are using SQL tables.

**Comment by accesstechnology-mike** [comment] 2023-02-01 15:36
Yes, my use case is with a SQL database. Thanks.

**Closed** 2023-02-07 10:47 UTC
Labels: bug
