### ISSUE TITLE
[BUDI-7102] Table elements refresh bug after item deletion

### ISSUE THREAD

**Issue by KevinHamonApp** [Budibase/budibase#10839] opened 2023-06-08 18:38 UTC
**Checklist**
- [X ] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker single image
  - Budibase Version: 2.6.20
  - App Version: 2.6.20

**Describe the bug**
I have a condition on a button integrated in my table rows. I added a condition, If the status of a row is not "TERMINE", the button "Résultats" is disabled. It works well, until I delete a row. The row is deleted, the table is refreshed. However, buttons are still in old state. Meaning that the condition of the button is made by the "old" row data, and not the refreshed one.

**To Reproduce**
1. Make a table
2. Add an component to rows with a condition depending of row data
3. Delete a row dynamically on the same screen
4. watch that component state conditionned is not refreshed

**Expected behavior**
I would expect that the elements conditions are re-evaluated with refreshed data.

**Screenshots**
For example : Here I have 3 rows, I delete the first one
![Capture d’écran du 2023-06-08 20-26-35](https://github.com/Budibase/budibase/assets/74555017/e087d6a1-64c6-4fda-a88d-b340c58d4065)

After deletion, my last item button is disabled. But it should be abled as the last one has a Statut to "TERMINE"
![image](https://github.com/Budibase/budibase/assets/74555017/40558bf6-8051-4265-9a82-de7789e5749a)
  
**App Export**
[cscool-export-1686249333778.tar.gz](https://github.com/Budibase/budibase/files/11691922/cscool-export-1686249333778.tar.gz)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22
 - Browser Firefox
 - Version 113.0.2

<sub>[BUDI-7102](https://linear.app/budibase/issue/BUDI-7102/table-elements-refresh-bug-after-item-deletion)</sub>

**Comment by melohagan** [comment] 2023-06-09 10:29
Hey @KevinHamonApp 

Thanks for the app export - which screen is that table in? I can't find it...

**Comment by KevinHamonApp** [comment] 2023-06-09 10:32
It is in `/projets/:projet/ screen

**Comment by melohagan** [comment] 2023-06-09 11:02
It's worth noting as well that the `Resultats` button beside 'TERMINE' is disabled when sorting the table, not just deletion.

![disabled_bug](https://github.com/Budibase/budibase/assets/101575380/0c0dec68-8c1a-4957-9bb0-8f1a905ad63b)

**Comment by melohagan** [comment] 2023-06-09 11:10
I think this issue is probably a duplicate of: https://github.com/Budibase/budibase/issues/5341

A workaround @KevinHamonApp is to use the **Show/Hide** conditions on two buttons. One that is disabled, and another that is enabled:

![Screenshot 2023-06-09 at 12 09 00](https://github.com/Budibase/budibase/assets/101575380/ae128ad9-461a-4d33-b28f-740c45184fe6)

![Screenshot 2023-06-09 at 12 09 20](https://github.com/Budibase/budibase/assets/101575380/14bb4453-4fb4-44fb-9804-0238daf0220b)

Then the other button will have the same condition, but `Show component` instead. 

![disabled_bug](https://github.com/Budibase/budibase/assets/101575380/6abb5b16-4b63-4f14-bb6b-ccf81558632b)

**Closed by melohagan** 2023-06-09 11:10 UTC
Labels: bug, conditional ui, env - production, linear, bb-components

**Comment by KevinHamonApp** [comment] 2023-06-09 11:13
> I think this issue is probably a duplicate of: #5341
> 
> A workaround @KevinHamonApp is to use the **Show/Hide** conditions on two buttons. One that is disabled, and another that is enabled:
> 
> ![Screenshot 2023-06-09 at 12 09 00](https://user-images.githubusercontent.com/101575380/244675943-ae128ad9-461a-4d33-b28f-740c45184fe6.png)
> 
> ![Screenshot 2023-06-09 at 12 09 20](https://user-images.githubusercontent.com/101575380/244676014-14bb4453-4fb4-44fb-9804-0238daf0220b.png)
> 
> Then the other button will have the same condition, but `Show component` instead.
> 
> ![disabled_bug](https://user-images.githubusercontent.com/101575380/244676304-6abb5b16-4b63-4f14-bb6b-ccf81558632b.gif)

All right, I'll do that ! 
Thanks for the investigation :)

**Comment by melohagan** [comment] 2023-06-09 11:32
You're welcome @KevinHamonApp thanks for highlighting the issue!
