### ISSUE TITLE
Logical Operands (OR / AND) in filter and Ui conditions.

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#5948] opened 2022-05-18 07:00 UTC
When setting up multiple filters on a Data Provider the filters and applied with an AND operand. All filters must be true.
It would be nice to have the ability to set logical OR on filters, so if either filter is true the row should be shown.

The same principle on Conditional UI.

**Comment by shogunpurple** [comment] 2022-06-08 14:22
Closing as dupe of https://github.com/Budibase/budibase/issues/5993

**Closed by shogunpurple** 2022-06-08 14:22 UTC
Labels: enhancement
