### ISSUE TITLE
All of the help menu targets are electron resources

### ISSUE THREAD

**Issue by digiajay** [Budibase/budibase#861] opened 2020-11-14 18:53 UTC
When I wanted to learn more, it was a bit confusing when all the Help menu options take me to electron websites.  Then I found that I have to click the Documentation on the left pane in the home screen of budbase to take me to correct documentation.

**Comment by shogunpurple** [comment] 2020-11-23 11:39
Hi @digiajay, thank you for raising this issue.

I am unable to reproduce this on OSX, or linux. Could you please provide some information about the machine you are using to run budibase?

**Comment by digiajay** [comment] 2020-11-24 10:11
I'm using this on Windows 10
--
Thanks,
Ajay.

**Comment by shogunpurple** [comment] 2020-11-24 10:29
Thanks @digiajay - we've fixed this and it will be in the next release.

**Closed by shogunpurple** 2020-11-24 10:29 UTC
Labels: bug
