### ISSUE TITLE
Unable to change the name of a user role

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#979] opened 2021-01-08 09:51 UTC
**Describe the bug**
I am not a fan of the power, admin user - in my head, I keep thinking Power is above Admin. I wanted to edit the roles and change their names to:
Power - Admin
Admin - Super Admin

**To Reproduce**
https://www.loom.com/share/49147c29edde4ceb8ae5d86cb230b650

**Expected behavior**
I expected the role's name to change.

**Screenshots**
See video above

**Comment by aptkingston** [comment] 2021-01-08 17:35
Was this happening for all roles or just the built in ones? Like if you create your own custom role, does it work if you try to change that?

**Comment by joebudi** [comment] 2021-01-08 18:02
If I create a new role, then change the name, it works.

**Comment by yashank09** [comment] 2021-01-29 09:16
I'm not too experienced with backend, but this bug seems interesting enough not to be picked up. 
I will look over this on the weekend and see if I reach somewhere :smile:

**Comment by shogunpurple** [comment] 2021-01-29 09:16
Thanks @yashank09, your contribution is really appreciated!

**Comment by yashank09** [comment] 2021-01-30 11:23
So far I can confirm that when a new app is created, and the first request to change the admin role name is made, the server does in fact respond with a 200. However, the next call to fetch updated roles does not reflect the same change. 
Subsequent calls to change the name then return a 409 conflict, probably because the earlier change is now blocking the newer one from happening. 

Screenshot of 200 response when the first call is made:
![sprusr_200_nochange](https://user-images.githubusercontent.com/37672190/106354892-af00ea80-62a9-11eb-8ac7-f3a79ac38f85.png)

Screenshot of next fetch not reflecting the update:
![sprusr_res_nochange](https://user-images.githubusercontent.com/37672190/106354934-ec657800-62a9-11eb-9cab-9de4f82d46e0.png)

Screenshot of next call getting 409'd:
![spradmn_409](https://user-images.githubusercontent.com/37672190/106354973-2f275000-62aa-11eb-87ac-d372c9258e4a.png)

**Comment by yashank09** [comment] 2021-01-30 14:18
I **think** I have found a root cause here. 
All the roles are combined and displayed by `api/controllers/role.js` as:

  _const customRoles = body.rows.map(row => row.doc)
  const staticRoles = [
    BUILTIN_ROLES.ADMIN,
    BUILTIN_ROLES.POWER,
    BUILTIN_ROLES.BASIC,
    BUILTIN_ROLES.PUBLIC,
   ]
  ctx.body = [...staticRoles, ...customRoles]_
  
  While `BUILTIN_ROLES.ADMIN` is created in `utilities/security/roles.js` as:
  
_exports.BUILTIN_ROLES = {
  ADMIN: new Role(BUILTIN_IDS.ADMIN, "Admin")
    .addPermission(BUILTIN_PERMISSION_IDS.ADMIN)
    .addInheritance(BUILTIN_IDS.POWER)
    }_
 
thereby overwriting the changed Admin name back to Admin. 
Does this look right? If so, I will start looking into how to resolve this next :)

**Comment by shogunpurple** [comment] 2021-01-31 09:34
@yashank09 thanks for investigating this one. This is a problem because the "built in" roles have hardcoded names and IDs as you mentioned.

I think the solution to this one is to just prevent editing the names of any of the built in roles in the UI. The problem Joe was having was more around the naming of the roles - maybe we could think about renaming power user to something else.

If we prevent editing of the names of built in roles in the builder, we can close this out.

**Closed** 2021-01-31 12:40 UTC
Labels: bug
