### ISSUE TITLE
Can't delete view with slash in the name

### ISSUE THREAD

**Issue by wolftune** [Budibase/budibase#7959] opened 2022-09-25 19:43 UTC
**Hosting**
- Cloud
  - Tenant ID: wolftune

**Describe the bug**

I made a view with a slash in the name "This/that" style. Unexpectedly, it pushed me into the Design stage. When I realized the issue, and tried to delete the view, it gave me an error message "Error deleting view".

**To Reproduce**

1. Make a view with a slash in the name
2. Try to delete the view

**Expected behavior**

The view should be deleted successfully
  
**Desktop (please complete the following information):**
 - OS: Ubuntu-based
 - Browser: Firefox 104

**Comment by wolftune** [comment] 2022-09-25 19:44
Note that renaming *works* and after renaming, deletion then works. So, I have no problem, but this is still a bug.

**Comment by melohagan** [comment] 2022-10-03 16:03
Closing as duplicate of: https://github.com/Budibase/budibase/issues/6912

**Closed by melohagan** 2022-10-03 16:03 UTC
Labels: bug
