### ISSUE TITLE
Deleting a relationship row in the UI it will be removed row but say there is an error 

### ISSUE THREAD

**Issue by AndrewJRamay** [Budibase/budibase#2563] opened 2021-09-07 15:58 UTC
Hi, I am running the latest version 0.9.122

I am receiving an error when deleting one of my rows that contains a relationship. the row will delete but will show a red error box at the top. 
below are the errors I am getting
![image](https://user-images.githubusercontent.com/80058238/132375333-03dd274e-ee52-438f-8114-ac3e800df05b.png)

to recreate. 
have 2+ SQL tables 
in BB create a 1 to many relationship with them.
add data into your app via the UI
navigate to the edit screen and delete the newly added data.

**Comment by shogunpurple** [comment] 2021-09-07 16:00
Thanks @AndrewJRamay - is this a duplicate of https://github.com/Budibase/budibase/issues/2496?

The above issue is fixed and will be out in the next release.

**Comment by AndrewJRamay** [comment] 2021-09-07 16:07
@shogunpurple Thank you sir sorry for the duplicate!!

**Closed** 2021-09-07 16:08 UTC
Labels: bug
