### ISSUE TITLE
[BUDI-7128] Multiple errors trying to edit a pre-existing app after upgrading to 2.7.7+

### ISSUE THREAD

**Issue by manwithpowers** [Budibase/budibase#10911] opened 2023-06-14 16:12 UTC
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker single image
  * Budibase Version: 2.7.7+

**Describe the bug**
I'm running into the same issue as here [https://github.com/Budibase/budibase/issues/10825#issuecomment-1581559782](https://github.com/Budibase/budibase/issues/10825#issuecomment-1581559782) after upgrading to v2.7.7+ from v2.6.11. I can log in but am unable to edit my app.

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/3d6f702e-1666-40af-9b22-3466bd796905/ac44f284-7ce9-4315-8c0b-ef1f9c34b1d4)

I am not using Azure File Share so I've created a new issue here. I'm running the docker single image on an Oracle Cloud (arm64) instance.
Rolling back to 2.6.11 resolves the issue.
Happy to email logs/app export.

**To Reproduce**

1. Upgrade from 2.6.11 to anything past 2.7.7
2. Click on edit or manage for a pre-existing app
3. Multiple errors appear and I'm unable to edit or manage the app

**Desktop (please complete the following information):**

* OS: MacOS/Windows
* Browser Chrome

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7128](https://linear.app/budibase/issue/BUDI-7128/multiple-errors-trying-to-edit-a-pre-existing-app-after-upgrading-to)</sub>

**Comment by melohagan** [comment] 2023-06-16 14:37
Closing as duplicate of: https://github.com/Budibase/budibase/issues/10924

**Closed by melohagan** 2023-06-16 14:37 UTC
Labels: bug, linear
