### ISSUE TITLE
Budibase Docker v2.7.6 is Broken

### ISSUE THREAD

**Issue by MarleTangible** [Budibase/budibase#10825] opened 2023-06-07 18:16 UTC
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker single image
  - Budibase Version: 2.7.6

**Describe the bug**
Running the docker single image results "ENOENT" error.

**To Reproduce**
``` Bash
docker run -d -t \
  --name=budibase \
  -p 10000:80 \
  -v /local/path/data:/data \
  --restart unless-stopped \
  budibase/budibase:latest
```

**Expected behavior**
An initial setup screen to be presented.

**Screenshots**
``` JSON
{"message":"ENOENT: no such file or directory, stat '/builder/index.html'","status":404,"error":{"code":"ENOENT"}}
```
  
**App Export**
N/A

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Browser: Chrome
 - Version: 114

**Additional context**
N/A

**Comment by shawnweeks** [comment] 2023-06-07 18:45
Just confirmed this on Rocky 8 as well, it also looks like v2.6.20 was never pushed to docker hub as the latest out there is v2.6.11 which still works fine.

**Comment by adrinr** [comment] 2023-06-07 20:49
I can confirm the issue. We just released a new version (v2.7.7) that should get rid of the error.
Can you please confirm? @MarleTangible @shawnweeks

**Comment by amrtdc1** [comment] 2023-06-07 21:55
I can confirm v2.7.7 gets me back into the app (resolves to the login screen and permits login), but now I'm unable to edit any apps.  All attempts result in the following error messages...
![v2 7 7 App Edit Errors](https://github.com/Budibase/budibase/assets/20376150/9f7d7a84-27de-4d98-915e-b1d40af5d311)

**Comment by mike12345567** [comment] 2023-06-08 09:01
Hi @amrtdc1 are there any docker logs you can provide for the container?

I have tried upgrading from v2.6.11 to v2.7.7 with a list of apps and was unable to replicate this behaviour, is there anymore information you can provide to help look into this?

**Comment by MarleTangible** [comment] 2023-06-08 10:14
@adrinr It looks like v2.7.7 resolved the initial issue. I didn't have any pre-existing apps so I cannot say anything about the other issue mentioned.

**Comment by mike12345567** [comment] 2023-06-08 14:43
Ah - sadly these docker logs don't tell us much - it only seems to include the CouchDB logs and not the application logs - just to confirm, are you using the Azure App Service versions of the image or are you using the standard image?

From here there's a couple of things we would need to be able to debug this at all:
1. The network logs from your browser when attempting to edit an app - this might give an an indication as to what has gone wrong with the application itself
2. Checking whether its possible to create new apps - is it only an issue with old apps
3. If possible, can you connect into your running container and attempt to check the logs of the services themselves? This can be done by connecting to the running container and then running `pm2 logs` to look into what the services have logged.

**Comment by amrtdc1** [comment] 2023-06-08 14:43
Mike, I'm going to delete the duplicated autoID records in my BBDatabase tables and see if that helps resolve the issue.  I just exported my app from v2.6.11 and imported it into another instance of BB running v2.7.7.  The first attempt failed and the tar.gz included all database rows.  The second attempt excluded internal BBDatabase table data and it worked fine.  I'm wondering if the duplicated AutoIDs that were generated in my v2.6.11 instance are causing the issue in v2.7.7

**Comment by mike12345567** [comment] 2023-06-08 14:48
Hi @amrtdc1 - I don't believe this could be an issue - if at all possible it would be great if you could provide an app export which fails to import to v2.7.7 - although understand if its not possible to share real apps and there are no minimal apps that show it! You can email exports to support@budibase.com (or upload to say google drive and email a link if larger)

**Comment by mike12345567** [comment] 2023-06-08 17:13
After some discussion via email, we have discovered this is a specific issue with Azure File Share - going to close this issue for now as the problem is unrelated to the single image itself.

**Closed by mike12345567** 2023-06-08 17:13 UTC
Labels: bug

**Comment by manwithpowers** [comment] 2023-06-12 12:51
I hate to resurrect this issue, but I'm running into the same issue as here https://github.com/Budibase/budibase/issues/10825#issuecomment-1581559782 after upgrading to v2.7.11 from v2.6.11. I can log in but am unable to edit my app.
![Screenshot 2023-06-12 at 14 43 26](https://github.com/Budibase/budibase/assets/5508635/02e42eb6-772c-48a8-aeb3-076cdbd567a6)
I'm self-hosted on arm64 (Oracle Cloud) using the docker single image. I am not using Azure File Share.
Happy to email logs/app export.
