### ISSUE TITLE
Select multiple components in the Form Design Cataloque at once

### ISSUE THREAD

**Issue by byebb** [Budibase/budibase#13945] opened 2024-06-14 09:23 UTC
**Describe the feature request**

I want to be able to select multiple components in a form in the Design Component at once:

Currently, it is very tedious to delete multiple components in a template at once.

In the provided screenshot to the left, I want to select multiple row elements to delete them all at once or maybe even apply similar styles, removing the tedium of going through every single component manually...

**Screenshots**
![image](https://github.com/Budibase/budibase/assets/4288893/e1f42152-41b2-42ba-87d1-6f1a8e5346ff)

**Comment by ConorWebb96** [comment] 2024-06-14 09:38
Closing: duplicate of this feature request https://github.com/Budibase/budibase/issues/13580

**Closed by ConorWebb96** 2024-06-14 09:38 UTC
Labels: enhancement
