### ISSUE TITLE
creating a new screen using "New row(empty)" template

### ISSUE THREAD

**Issue by shaikhashraf709** [Budibase/budibase#1151] opened 2021-02-22 04:54 UTC
Description:
I cannot create a new screen using "New row(empty)" template whenever i try to do so the create screen button disables and nothing happens, it doesn't respond.

**To Reproduce**
just try to Create a screen using "New row(empty)" template 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser BudiBase
 - Version 0.7.8

![Untitled](https://user-images.githubusercontent.com/78905650/108664100-118b8600-74f8-11eb-98b7-9c786c0c0a78.png)

**Comment by aptkingston** [comment] 2021-02-22 15:48
Hi @shaikhashraf709 , thanks for the report. The "Empty" templates have actually been removed because they didn't really serve any purpose - so going forwards there will just be a "Create from scratch" template and create, edit and list templates for each of your backend tables. I can confirm there definitely won't be any issue with creating screens using these templates (I just double checked). This will be released in our next update.

**Closed by aptkingston** 2021-02-22 15:48 UTC
Labels: bug
