### ISSUE TITLE
MongoDB Read requests seem to be broken

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#2696] opened 2021-09-21 13:30 UTC
I get an error when I try run a MongoDb `find` : 

![image](https://user-images.githubusercontent.com/3524181/134178790-093aff77-cc4d-4d19-9d6c-d33bc4f00636.png)

Looking at the source, I think that we are missing an `await` call on all of these requests: https://github.com/Budibase/budibase/blob/62307b0b55f731d8dade780cd7acd0d07d8d03ce/packages/server/src/integrations/mongodb.ts#L115

The Mongo/Nodejs docs show that a `cursor` is returned. Then `await cursor.forEach(..)` must be called. https://docs.mongodb.com/drivers/node/current/usage-examples/find/

**Comment by mslourens** [comment] 2021-09-21 15:00
The cursor returned by find is an object with a method called `toArray`, which converts the result cursor into an array of results: [https://docs.mongodb.com/manual/reference/method/cursor.toArray/](https://docs.mongodb.com/manual/reference/method/cursor.toArray/). This method returns a promise, which in turn is returned by the Mongo integration. 
Somehow your connection got closed before the data was read.I am not sure why, because I just created a MongoDb connection and was able to run a read request from the query page of the Mongodb datasource.

**Comment by mjashanks** [comment] 2021-09-21 15:10
I pushed this to a branch: https://github.com/Budibase/budibase/commit/3c2b21abecca0d25288cdd0def503312ceda059b

Not sure how it's broken for me, but not for you. It does seem strange that it has not been raised before.

Will look into the other commands as well.

**Comment by mjashanks** [comment] 2021-09-21 15:18
Could it just be that your result returns before `await this.client.close()` - its in the `finally` statement, so always gets run directly after the return.

My DB is in Mongo Atlas, so there is plenty of latency there to be delayed.

**Comment by mslourens** [comment] 2021-09-21 21:18
that's probably why you get that message, it closes the connection before the data is loaded from Atlas. I run a local MongoDb instance, so that's much faster. I thought the promise from the returned query is always resolved in order to get the results, but apparently the finally is run first. 
At least this will fix your issue and any other timing issues.

**Comment by spmurrayzzz** [comment] 2021-10-04 23:25
Just to add some additional context here for future posterity (as I ran into the same problem). The issue is not around timing at all, I can repro this 100% of the time using local mongo with large datasets. Its just an async issue.

This is a side effect of how the mongo driver implements the [dual promise-or-callback behavior](https://mongodb.github.io/node-mongodb-native/3.6/api/lib_cursor.js.html#line816) of `Cursor#toArray()`. That method doing the recursive `_next()` invocation there is being spread across multiple ticks of the event loop. So even though your query controller is awaiting the `read()` promise, the `finally {}` block puts `this.client.close()` on the stack before the cursor can flush the rest of the data events.

**Closed** 2021-11-04 10:35 UTC
Labels: bug
