### ISSUE TITLE
"Session not authenticated" error when using button with trigger activation

### ISSUE THREAD

**Issue by Rootse** [Budibase/budibase#6890] opened 2022-07-25 17:21 UTC
**Hosting**

- Self
  - Method: docker compose
  - Budibase Version: 1.0.158

**Describe the bug**
If you add a button to the repeater on a public page with the activation of a trigger that updates the rows in the table, then when you click it, the error "Session not authenticated" appears even if the table has public permissions

**To Reproduce**
1. Create public page
2. Create Budibase table with public access
3. Create Data Provider->Repeater->Container->Button
4.  Create Automation App Action and add Update Row
5. Define an action on a Button Trigger Automation on the trigger from the last step
6. Publish
7. Click on the button from the public page

**Expected behavior**
The trigger will fire and update the table

**Screenshots**
![Screenshot_36](https://user-images.githubusercontent.com/28269608/180836774-98a66489-3fa0-46a2-a302-34fe0e3f7b16.png)
![Screenshot_34](https://user-images.githubusercontent.com/28269608/180836780-3939e835-539a-4229-ae51-71abd59f0d61.png)
![Screenshot_35](https://user-images.githubusercontent.com/28269608/180836789-e414b4e0-98fe-489b-a193-00d91488abab.png)
  
**App Export**
[bug-export-1658769558582.txt](https://github.com/Budibase/budibase/files/9183434/bug-export-1658769558582.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10 (21H1)
 - Browser FireFox
 - Version 102.0.1

**Comment by mike12345567** [comment] 2022-08-02 09:28
Hi @Rootse - I see you're using quite an old version of Budibase, could you try this again after updating? There has been some bug fixes in this area that were released as part of 1.1.X updates.

**Comment by proton029** [comment] 2022-08-04 10:13
Hi @mike12345567  The same issue occurs for me as well. When clicking on the view button on the publish icon the app loads perfect but when I copy the link to another browser say in Edge on the same machine I'm getting this issue. Im using BB1.2.2

**Comment by mike12345567** [comment] 2022-08-04 10:27
Hi @proton029 - just to confirm, you've built and published a public app, when you try to access it from another browser you cannot? Or is it to do with running an automation from a button, within the public app?

In the latest release you need to set the role of the app action to public, like so:
![image](https://user-images.githubusercontent.com/4407001/182825520-cc53051c-1b96-4254-88be-99d87c6b55ce.png)

**Comment by proton029** [comment] 2022-08-04 10:36
HI @mike12345567  sorry that it was a mistake from my side that i have i updated the app but i was checking it from the publihsed version before update. Its working now. Thats why i deleted my comment

**Comment by mike12345567** [comment] 2022-08-04 10:38
Going to close this issue as it is a duplicate of: https://github.com/Budibase/budibase/issues/6709 - which was fixed in recent releases.

**Closed by mike12345567** 2022-08-04 10:38 UTC
Labels: bug
