### ISSUE TITLE
Relationships are not displayed when using Current User.Relationship as a datasource

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#2479] opened 2021-08-26 15:41 UTC
This comment describes it well - i reproduced it exactly as described: https://github.com/Budibase/budibase/discussions/2365#discussioncomment-1237995

1. Create a Lessons table
2. Create a Students table
3. Create a `Teacher` column on `Lessons` (teacher is a `User`) - `One user has many lessons`
4. Create a `Student` column on `Lessons` - `One Student has many lessons`
5. Create a data provider and set datasource to `Current User.Lessons`
6. Put a table below
RESULT: The Student or the Teacher values are not loaded in the table

**Comment by aptkingston** [comment] 2021-09-17 11:33
Closing this now in favour of #2284 as I think the issue is already solved, but these are definitely the same thing.

**Closed by aptkingston** 2021-09-17 11:33 UTC
Labels: bug
