### ISSUE TITLE
Feature Request: URL Params via Handlebar

### ISSUE THREAD

**Issue by hlipnick** [Budibase/budibase#1108] opened 2021-02-09 19:39 UTC
**Describe the Feature Request**
I would like to be able to pull URL params and/or window.location through Handlebars in the Design side of BudiBase.  

I could, for example, link to ...app/projects/5, then pull that project id (5) via something like {{ window.location.pathname }} (or whatever syntax is deemed appropriate).

**Suggested behavior**
A handlebar syntax to pull URL path and params.  Ideally accessible as an array, if able.

**Additional context**
Original brief discussion of feature idea on Discord at [https://discord.com/channels/733030666647765003/733030667797004351/808781936058695761](https://discord.com/channels/733030666647765003/733030667797004351/808781936058695761)

**Comment by shogunpurple** [comment] 2021-02-09 19:41
Possible dupe of https://github.com/Budibase/budibase/issues/954

We will be implementing this one over the next week or two. It's been requested a lot by the community and I've found myself needing it a lot too. Thanks for the link to the discord discussion too - that's very helpful.

**Comment by aptkingston** [comment] 2021-02-09 19:50
Yea this is pretty much part of #954, but given that it's not really possible to view the equivalent of a `RowDetail` for external sources at the minute I'd be keen to get this in as a standalone feature soon, because this part is actually super quick to implement.

**Closed** 2021-02-16 16:33 UTC
Labels: feature
