### ISSUE TITLE
[BUDI-6751] Automation List doesn't show scrollbar

### ISSUE THREAD

**Issue by Onchulee** [Budibase/budibase#9999] opened 2023-03-13 12:11 UTC
**Checklist**
- [✔️] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: K8S
  - Budibase Version: 2.4.14
  - App Version: 2.4.14
  - Cloud: GKE

**Describe the bug**
Automation UI doesn't display correctly.
1. Automation list doesn't show scrollbar.
2. Automation container height is overflow the screen display

**To Reproduce**
It's happened after version updating from 2.3.15 to 2.4.14
1. Upgrade version to 2.4.14
2. Open project, then go to Automate screen

**Expected behavior**
1. Automation list should properly show scrollbar if its height over the screen height
2. Automation container should show scrollbar height within screen height
  
**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome 
 - Version 111.0.5563.65

**Additional context**
This issue can be fixed by add height : calc(100vh - [top menu height]) in css .automations-list. 
This change also help fixing a container height too.

<sub>[BUDI-6751](https://linear.app/budibase/issue/BUDI-6751/automation-list-doesnt-show-scrollbar)</sub>

**Comment by aptkingston** [comment] 2023-03-13 12:13
Hi @Onchulee. A screenshot would be very helpful for a visual issue like this. In my quick testing scrolling works as expected, so a screenshot of what you mean would really help. Thanks.

**Comment by Onchulee** [comment] 2023-03-13 12:34
Hi Andrew ***@***.***>
I desired to record the screen of this issue which also occurred after clearing all cache and hard reload the site and the solution which I found.
It also happened to my co-worker too.

Thank you

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows


________________________________

**Comment by melohagan** [comment] 2023-05-11 08:48
Closing as duplicate of: https://github.com/Budibase/budibase/issues/10535

**Closed by melohagan** 2023-05-11 08:48 UTC
Labels: bug, bb-automations, linear
