### ISSUE TITLE
[BUDI-7385] Time Picker field value is sometimes one hour behind selection

### ISSUE THREAD

**Issue by andz-bb** [Budibase/budibase#11507] opened 2023-08-11 17:50 UTC
**Checklist**

* [X] I have searched Budibase discussions and GitHub issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker-compose
  * Budibase Version: 2.9.23
  * App Version: 2.9.23

**Describe the bug**
The first time you use the date picker component the actual field value that is set is one hour behind the value you select. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Make a form with a time-only date picker component
2. Open it and select a time (e.g. 12:00)
3. Close the time picker - the time in the field will be 11:00 instead

**Expected behaviour**
Field value should be consistent with what is selected in the picker

**Screenshots**
selecting 12pm:

![image.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/e7df02bb-2de1-42bc-9644-9ea990d99ac2/eca30c45-5bfd-4c00-a5b3-96f0d890e779?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9lN2RmMDJiYi0yZGUxLTQyYmMtOTY0NC05ZWE5OTBkOTlhYzIvZWNhMzBjNDUtNWJmZC00YzAwLWE1YjMtOTZmMGQ4OTBlNzc5IiwiaWF0IjoxNjkxNzc2MjU2LCJleHAiOjE2OTE4NjI2NTZ9.uPj7hoQZ2yQQXe_-rYEpPQ7MrQrOjk_TXAM3tzaWeJs)

after closing time picker:

![image.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/ea19d87e-f5a9-4375-83b1-bedb71c5e172/55204d55-e836-4c0f-9cc4-4d2c45330e6d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9lYTE5ZDg3ZS1mNWE5LTQzNzUtODNiMS1iZWRiNzFjNWUxNzIvNTUyMDRkNTUtZTgzNi00YzBmLTljYzQtNGQyYzQ1MzMwZTZkIiwiaWF0IjoxNjkxNzc2MjU2LCJleHAiOjE2OTE4NjI2NTZ9.M6bujvVD-ZwzABJiIfZGU15wuE6uKu7h1qi5AxUdfIU)

**Context**

Raised by a business customer

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7385](https://linear.app/budibase/issue/BUDI-7385/time-picker-field-value-is-sometimes-one-hour-behind-selection)</sub>

**Comment by shogunpurple** [comment] 2023-10-25 13:19
\+1 for replacing flatpickr

**Comment by melohagan** [comment] 2023-12-20 16:57
Closing as duplicate of: https://github.com/Budibase/budibase/issues/11894

**Closed by melohagan** 2023-12-20 16:57 UTC
Labels: bug, Medium priority, bb-components
