### ISSUE TITLE
Airtable Create query failing

### ISSUE THREAD

**Issue by adamjdavies** [Budibase/budibase#7322] opened 2022-08-17 08:39 UTC
Hello - I've seem to be having some trouble with setting up a **Create** query on the airtable integration. 

In this first example, I can successfully create a new record in my airtable if I enter the record variables directly in the query body. 
<img width="1570" alt="Screenshot 2022-08-15 at 17 31 40" src="https://user-images.githubusercontent.com/64409787/184676251-e30de840-ef72-40ba-bf4a-8abc515e2ff9.png">

In this second example, I've used bindings in place of the 'hard-coded' variables and set default values for all. If I try to run the query I get the error shown in the image. 
<img width="1526" alt="Screenshot 2022-08-15 at 17 31 20" src="https://user-images.githubusercontent.com/64409787/184676708-0e0e1371-2f60-49b9-a066-432af4a72788.png">

Any ideas? I don't think I've missed anything out of the query in the second example. 

Thanks

_Originally posted by @adamjdavies in https://github.com/Budibase/budibase/discussions/7280_

**Comment by melohagan** [comment] 2022-08-18 10:16
Closing as duplicate of: https://github.com/Budibase/budibase/issues/7343

**Closed by melohagan** 2022-08-18 10:16 UTC
Labels: bug, sev4 - moderate
