### ISSUE TITLE
Signature component doesn't work when applying its value directly an on button click save.

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#14812] opened 2024-10-17 08:53 UTC
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.33.2
  - App Version: 2.33.2

**Describe the bug**
Error thrown when trying to bind and save the value of a signature field on a button click. The error thrown is `{"message":"Unexpected error," "status":400,"error":"Unexpected error"}`. The only difference I can see is in the payload. One is a straight JS object, and the other passes a stringified version. I'm assuming the error is being thrown because of this.

**To Reproduce**
1. Import the attached app
2. Go to the home screen
3. Click on a record and add a signature
4. Click save
5. See error

**Expected behavior**
If I want to do this on a specific step, I should be able to save a signature on its own.

**Screenshots**
<img width="1423" alt="Screenshot 2024-10-17 at 09 44 06" src="https://github.com/user-attachments/assets/4cf2b23f-8a8e-4be8-992f-09cde32abb11">

**Normal payload**
<img width="705" alt="Screenshot 2024-10-17 at 09 52 51" src="https://github.com/user-attachments/assets/5e07b4d4-151e-48d4-9703-480bdceec9aa">

**Action save payload**
<img width="703" alt="Screenshot 2024-10-17 at 09 49 23" src="https://github.com/user-attachments/assets/eba76346-b737-4fdd-ab33-9386b65e6a9b">

**App Export**
[signature issue-export-1729155203158.tar.gz](https://github.com/user-attachments/files/17409170/signature.issue-export-1729155203158.tar.gz)

**Comment by aptkingston** [comment] 2024-10-31 16:37
I'm assuming you're using a normal binding like `{{ Form.Fields.Signature }}` here, while adding the field manually in a save row action? If so you'll just need to use the `literal` helper to ensure it's kept as an object (or use JS). I don't think this is a bug because it's just how bindings have always worked - everything is a string by default.

Going to close this since it's working as intended and you just need the `literal` helper 👍 Appreciate it's not very obvious that this is the case, but there's nothing we can really do to change this at it's fundamentally a limitation of how handlebars works.

**Closed by aptkingston** 2024-10-31 16:37 UTC
Labels: bug, forms, actions, avalanche, bb-components
