### ISSUE TITLE
Cannot Nest Forms within Designer

### ISSUE THREAD

**Issue by apparentlyjeff** [Budibase/budibase#10386] opened 2023-04-22 18:21 UTC
**Hosting**
- Self
  - Method: docker
  - Budibase Version: <version> 
  - App Version: 2.5.6

When in the designer, if you're within a tree that contains a Form component above your position, when clicking on the Add Component you'll find the "Form" component is no longer available.  You have to be outside of any Form component to add a new form.  I needed to nest a couple of forms to get attachments to work correctly.

**To Reproduce**
1. Create a form.
2. Click on '+' to Add a component
3. Scroll down the component list to the form section and find that the Form component now has disappeared.

**Expected behavior**
You should be able to nest a form under another form.

**Comment by aptkingston** [comment] 2023-04-23 11:39
Hey @apparentlyjeff. This is by design - you aren't allowed to nest forms inside other forms. If you need functionality similar to this then I'd advise just having a button which opens a new screen in a modal and lets you do whatever other row update that needs done while you're in the middle of your current form. If you need help designing your app then feel free to open a thread in discussions and you can get some support there, but I'm closing this one off since it isn't a bug.

**Closed by aptkingston** 2023-04-23 11:39 UTC
Labels: bug
