### ISSUE TITLE
MondoDB integration in budibase

### ISSUE THREAD

**Issue by shaikhashraf709** [Budibase/budibase#1135] opened 2021-02-19 07:24 UTC
Description:
When i try to run a query for a MongoDB data source  i get this error

Steps to Reproduse:
just create a Datasource using mongoDB 
write a JSON query and try to run it

**Desktop (please complete the following information):**
 - OS: windows 7
 - Budibase for Windows
 - Latest Version

Does the same for SQL datasource
![Error](https://user-images.githubusercontent.com/78905650/108471519-8620b380-72b1-11eb-8063-c87926f0e7c8.png)

**Comment by shogunpurple** [comment] 2021-02-22 16:49
Should be resolved in the latest release - we have made some updates to external data sources and I cannot reproduce this issue with our latest code on windows or any other OS.

**Closed by shogunpurple** 2021-02-22 16:49 UTC
Labels: bug
