### ISSUE TITLE
JSON (Key / Value) type

### ISSUE THREAD

**Issue by Grayda** [Budibase/budibase#2568] opened 2021-09-08 09:09 UTC
**Describe the feature request**
I'm migrating a custom app I wrote to Budibase, and one of the fields I had was a key / value pair for neatly storing arbitrary data. The data was just stored as a simple JSON object. It looks like Budibase doesn't have that type available, and it might be useful to have

I've created some mockups of how it'd look:

**Screenshots**
[Creating the column](https://user-images.githubusercontent.com/4891563/132457937-0a56db63-f54a-43b0-b92b-cfede3463b66.png)
[Editing the data](https://user-images.githubusercontent.com/4891563/132462689-905713b6-9e51-4cbf-9afc-ce5c06af98e4.png)
[Viewing the column in the data tab](https://user-images.githubusercontent.com/4891563/132480811-7f75419b-b86e-48dc-b1ca-11cd3d28d7ea.png)

**Comment by mslourens** [comment] 2021-09-17 11:34
Can't you just use a stringified JSON (`JSON.stringify(json)`? Because Budibase is not able to set/update an individual key/value pair, it will always update the whole field. After retrieving the data you could convert the string easily back to key/value JSON object with `JSON.parse(jsonString)`.

**Comment by Grayda** [comment] 2021-09-22 07:44
I've had a look through Budibase (I'm learning as I'm porting over my custom app), but I'm not sure where I'd use JSON.parse, as I don't think mustache supports that (I tried). I also thought a repeater would work, but that's only for a table, not a row. I also thought about making another table called "Metadata", setting up a relationship, then putting a data source, followed by a repeater, into a column at the end of the table, but it didn't quite feel like a good way to do it. 

To add some more context, here's how the field looks in my custom app (it's a key / value addon for Laravel Nova):

![image](https://user-images.githubusercontent.com/4891563/134301321-16e7f2b6-a234-4e93-9ffe-5b92a2a0d426.png)

And when I hit save, the values shown are saved in a JSON (text) field like so:

```json
{
  "Model Number": "ABC-001",
  "Colour": "Red",
  "Firmware version": "1.23A"
}
```

When I view the item, it looks the same as in edit mode, but just non-editable.

**Comment by jalberto** [comment] 2021-11-03 15:52
Postgres support JSON and arrays as native data types so will be great to at least have a way to edit/view those columns safely

**Comment by shogunpurple** [comment] 2021-11-24 09:31
Closing as dupe of https://github.com/Budibase/budibase/issues/3381

**Closed by shogunpurple** 2021-11-24 09:31 UTC
Labels: enhancement
