### ISSUE TITLE
Field Group based on Data Provider with REST API source can't properly "update form from fields"

### ISSUE THREAD

**Issue by sergey-vin** [Budibase/budibase#7523] opened 2022-08-30 21:48 UTC
**Hosting**
- Cloud

**Describe the bug**
A "Field Group" component can not detect fields properly when working with data sources based on REST API. It detects bindings, not fields of schema.

**To Reproduce**
1. Go to "Data", create a REST data source
2. Create a GET query for this REST source, with no binding. Potentially add a transformer to prettify the schema.
3. Go to "Design" -> "New screen"
4. Create a hierarchy of components: 
- Data Provider (with Data set to this REST query and optionally - filters to narrow down to a single record)
- Repeater (with Provider set to just created Data Provider)
- Form (Type = Update; Scheme = REST query's schema)
- Field Group
5. In the Field Group - click on "Update form fields", then ack the confirmation modal
6. See nothing created, no fields

Alternatively:
- if on step 2 you added some bindings, even some random ones, not included into any path args / query parameters, etc., 
- then on step 6 you'd see some form fields created, which are matching REST bindings.

**Expected behavior**
See the fields created according to the REST query's schema, not REST query bindings.

**Additional tests**
In order to check if providers and queries work, I've created a Table component inside a provider, and it showed data perfectly fine.

**Screenshots**
REST query, it's bindings and schema:
![image](https://user-images.githubusercontent.com/1080493/187547497-5a1696e8-f383-4c67-92d1-321b47bbea28.png)

Designed screen which shows "working" Table and "not working" field group:
![image](https://user-images.githubusercontent.com/1080493/187547790-0ef746f8-2df4-47db-9bd5-b16a04d07b84.png)

**Additional context**
Typically, auto generated screens (generated from DB tables) consist of 3 screens: `/xxx`, `/xxx:id` and `/xxx/new/new`, where
- `/xxx` shows a table
- while `/xxx:id` and `/xxx/new/new` show a field group with form fields.
 
I already have an app built using this concept, where I have several auto-generated and slightly modified screens with Tables for List views and Forms for Detailed views.
I wanted to enrich some of the Detailed views (`/xxx:id` screens) with additional data from a REST source, so that REST data are represented in the same form->fields format, below the main content.
I wasn't able to do so because of the current issue - a form + field group pair doesn't seem to be able to render REST data.

A Table component, on the other hand, can render REST data perfectly, but that's not what needs to be displayed on Detail pages (`/xxx:id`. Table is good for List type of screens (`/xxx`).

I understand that this issue may be coming from the idea that a form can be used to control rest parameters, that's why it binds to `Bindings`, not `Schema`, but there should be a way for a designer to chose what the form applies to.

**Comment by melohagan** [comment] 2022-09-02 07:25
@sergey-vin Closing as duplicate of: https://github.com/Budibase/budibase/issues/6238

Apologies for the lack of clarity. I'll try to make this clearer in the docs.

**Closed by melohagan** 2022-09-02 07:25 UTC
Labels: bug

**Comment by sergey-vin** [comment] 2022-09-05 05:16
So, Am I right that there's no way to use "form fields" to represent REST data? Only table format?

**Comment by melohagan** [comment] 2022-09-05 08:17
Hey @sergey-vin That's right, form fields cannot map to the schema of REST query, however it can map to the bindings: https://github.com/Budibase/budibase/discussions/7492#discussioncomment-3534009
