### ISSUE TITLE
[BUDI-7106] FireFox Issue: Mirrored table columns, sorted in opposite direction as defined in design

### ISSUE THREAD

**Issue by DAVNRW** [Budibase/budibase#10689] opened 2023-05-24 17:50 UTC
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Cloud
  * Tenant ID: pepdev
  * App ID: app_pepdev_d581f2eaf43d46cd82bd4903f66b71f0

**Describe the bug**
The columns in the table component are shown in mirrored order. Means from right to left.
Firefox Version is 111.0.1 (32 Bit)

**To Reproduce**

1. Open Firefox
2. Log in to budibase
3. Show table component in designer, preview or published version
4. In all cases the column order is wrong

**Expected behavior**
The column should been shown in the defined order and not longer in mirrored order.

**Screenshots**

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/b3cad18c-6e3c-479d-ab64-686ea690e88b/2552ce69-6221-4fea-883e-b6b7f537c72c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9iM2NhZDE4Yy02ZTNjLTQ3OWQtYWI2NC02ODZlYTY5MGU4OGIvMjU1MmNlNjktNjIyMS00ZmVhLTg4M2UtYjZiN2Y1MzdjNzJjIiwiaWF0IjoxNjkwODAwNTcyLCJleHAiOjE2OTA4ODY5NzJ9.AoyMY67Ny01Z7Kqb2rYMEKqiIGyehkITmktL41SJoqA)

**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**

* OS: Windows 10
* Browser: Firefox
* Version 111.0.1 (32 Bit)

**Additional context**

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7106](https://linear.app/budibase/issue/BUDI-7106/firefox-issue-mirrored-table-columns-sorted-in-opposite-direction-as)</sub>

**Comment by melohagan** [comment] 2023-06-09 13:44
Re-opening as this is a slightly different issue.

**Comment by melohagan** [comment] 2023-08-18 15:32
Tested on Budibase version ** 2.9.5** and Firefox version **116**, and I could not reproduce.

Previously I had been able to reproduce, so perhaps there has been an update on the Firefox side of things, or the order issue will no longer apply to newly added tables / table blocks.

Closing.

**Closed by melohagan** 2023-08-18 15:32 UTC
Labels: bug, env - production, linear, bb-components

**Comment by shawnweeks** [comment] 2023-08-19 15:04
@melohagan Still showing as reversed in my test app.

<img width="1279" alt="Screenshot 2023-08-19 at 10 03 03 AM" src="https://github.com/Budibase/budibase/assets/9768773/bfba0dbc-88a3-4883-9837-1123488c03a5">

<img width="890" alt="Screenshot 2023-08-19 at 10 03 10 AM" src="https://github.com/Budibase/budibase/assets/9768773/0e5cf37f-8542-4b42-8eff-12964aac6f27">

[Column Order Bug-export-1692457398977.tar.gz](https://github.com/Budibase/budibase/files/12386171/Column.Order.Bug-export-1692457398977.tar.gz)

**Comment by melohagan** [comment] 2023-08-21 08:57
Thanks for the app export @shawnweeks 

I'll take another look!

**Comment by melohagan** [comment] 2023-08-21 14:10
Fixed in version **2.9.30**

**Comment by shawnweeks** [comment] 2023-08-21 15:05
@melohagan Thank you it's working correctly now.
