### ISSUE TITLE
[ Data ] - Allow definition of Self Referencing relationships for SQL datasources

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#12467] opened 2023-11-29 17:26 UTC
This has already beed discussed in #5635 and in other places so i am just making this a more formal feature request.

**Comment by melohagan** [comment] 2023-11-29 19:05
Hey @poirazis Thanks for linking the issue. I know it's an old one, but I'm going to close this as a duplicate of the other issue :)

**Closed by melohagan** 2023-11-29 19:05 UTC
Labels: enhancement
