### ISSUE TITLE
Renaming a column from an external MySQL table truncates data

### ISSUE THREAD

**Issue by RixzZ** [Budibase/budibase#4662] opened 2022-02-23 12:30 UTC
**Describe the bug**
On a project with an external MySQL instance, if you rename a column from a table that already contains data, that column data is truncated on the process. The content of that column becomes NULL if seen from the DB itself.

This doesn't seem to happen with the built-in DB.

**To Reproduce**
1. Create a new project.
2. Add an external MySQL DB as source.
3. Create a table.
4. Create a column on that table (on my tests I created a Text column with 20 chars as limit).
5. Add one or more rows of data with information on the test column.
6. Click on the pencil icon next to the column name and rename it.
7. The column is renamed but all information is missing.

**Expected behavior**
The information should never be lost on this process.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser: Google Chrome
 - Version: 98.0.4758.102

**Additional context**
I'm using Budibase v1.0.73 on Docker. The external DB used for testing is MariaDB 10.6 on another docker container.

**Comment by mslourens** [comment] 2022-03-08 10:26
Duplicate of #4811 and fixed by #4834

**Comment by mike12345567** [comment] 2022-03-16 11:44
Closing duplicate - this is fixed in latest release of Budibase.

**Closed by mike12345567** 2022-03-16 11:44 UTC
Labels: bug
