### ISSUE TITLE
Support for composite keys when defining an existing relationship

### ISSUE THREAD

**Issue by ardnaskela** [Budibase/budibase#4158] opened 2022-01-23 22:32 UTC
As of now the platforms permits using a single column as a primary/foreign key when defining a relationship.
A combination of fields should also be supported in order to map relationships created using composite keys.

**Comment by mike12345567** [comment] 2022-01-24 10:01
Hi @ardnaskela - thanks for the issue - I'm going to close this as its a duplicate of #1738 - we are aware of the composite key issue.

**Closed by mike12345567** 2022-01-24 10:01 UTC
Labels: enhancement
