### ISSUE TITLE
Default value for Relationship Picker

### ISSUE THREAD

**Issue by emrahcetiner** [Budibase/budibase#4320] opened 2022-02-04 00:10 UTC
All forms components have a default value feature but the relationship picker doesn't. I want a form for creating a new row but some fields should fill with last time choices. Before saving the form I write its value to app state then read from app state and set it as default value.

How can I do this for the Relationship Picker without the default value property?

**Comment by aptkingston** [comment] 2022-02-04 11:04
Hey @emrahcetiner. I've just merged a PR to add this! It will be included in our next release which will be soon.

**Closed by aptkingston** 2022-02-04 11:04 UTC
Labels: enhancement

**Comment by peterhuppertz** [comment] 2023-02-08 09:46
I have a problem setting the default value of the relationship picker:
1) If I set the default value with a string it's selected fine: e.g. %5B'us_c81da6f7f3f04e70bcb46cbd69ea44d0'%5D
2) If I set the default value including a variable, it does not work. E.g. %5B'{{db.Rows.0.fk_users}}'%5D

I tested and the resulting string is EXACTLY the same, so I don't understand why the "normal" string selects the correct value, while the string including the result from the DB does not. Any idea?

**Comment by BernardTeske** [comment] 2023-03-28 09:29
Hello! The problem is that the data is loaded asynchronously. I have used a javascript in my default value.

```
const serverID = String($("serversDataProvider.Rows.0._id"));
console.log(serverID);
return serverID;
```

I also have this output via console.log. I get first "undefined" and then the correct value.

In my case it helped to use the ID from the request string. I pass the id=3 in the URL (as "server"). The default value for the field is now:

`%5B{{URL.server}}%5D`

I don't know if this always works, but for me this workaround worked.
